# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `alba` gem.
# Please instead update this file by running `bin/tapioca gem alba`.


# Core module
# This file includes public constants to prevent circular dependencies.
#
# pkg:gem/alba#lib/alba/version.rb:3
module Alba
  class << self
    # pkg:gem/alba#lib/alba.rb:14
    def backend; end

    # Set the backend, which actually serializes object into JSON
    #
    # @param backend [#to_sym, nil] the name of the backend
    #   Possible values are `oj`, `active_support`, `default`, `json` and nil
    # @return [Proc] the proc to encode object into JSON
    # @raise [Alba::UnsupportedBackend] if backend is not supported
    #
    # pkg:gem/alba#lib/alba.rb:35
    def backend=(backend); end

    # Detect if object is a collection or not.
    # Types in {.non_collection_types} (default: Struct, Range, Hash) are
    # considered non-collection even if they include Enumerable.
    #
    # @api private
    #
    # pkg:gem/alba#lib/alba.rb:96
    def collection?(object); end

    # Set the default superclass for resource classes created with {.resource_class}
    #
    # @param value [Class, String, Symbol] the default superclass
    # @example
    #   Alba.default_superclass = '::MyApp::BaseResource'
    #
    # pkg:gem/alba#lib/alba.rb:27
    def default_superclass=(_arg0); end

    # Disable inference for key and resource name
    #
    # @deprecated Use {.inflector=} instead
    #
    # pkg:gem/alba#lib/alba.rb:115
    def disable_inference!; end

    # Enable inference for key and resource name
    #
    # @param with [Symbol, Class, Module] inflector
    #   When it's a Symbol, it sets inflector with given name
    #   When it's a Class or a Module, it sets given object to inflector
    # @deprecated Use {.inflector=} instead
    #
    # pkg:gem/alba#lib/alba.rb:106
    def enable_inference!(with:); end

    # pkg:gem/alba#lib/alba.rb:14
    def encoder; end

    # Set encoder, a Proc object that accepts an object and generates JSON from it
    # Set backend as `:custom` which indicates no preset encoder is used
    #
    # @param encoder [Proc]
    # @raise [ArgumentError] if given encoder is not a Proc or its arity is not one
    #
    # pkg:gem/alba#lib/alba.rb:45
    def encoder=(encoder); end

    # Find type by name
    #
    # @return [Alba::Type]
    #
    # pkg:gem/alba#lib/alba.rb:223
    def find_type(name); end

    # Hashify the object with inline definitions
    #
    # @param object [Object] the object to be serialized
    # @param with [:inference, Proc, Class<Alba::Resource>] determines how to get resource class for each object
    # @param root_key [Symbol, nil, true]
    # @param block [Block] resource block
    # @return [String] serialized JSON string
    # @raise [ArgumentError] if both object and block are not given
    #
    # pkg:gem/alba#lib/alba.rb:80
    def hashify(object = T.unsafe(nil), with: T.unsafe(nil), root_key: T.unsafe(nil), &block); end

    # @param name [String] a String Alba infers resource name with
    # @param nesting [String, nil] namespace Alba tries to find resource class in
    # @return [Class<Alba::Resource>] resource class
    #
    # pkg:gem/alba#lib/alba.rb:154
    def infer_resource_class(name, nesting: T.unsafe(nil)); end

    # @deprecated Use {.inflector} instead
    # @return [Boolean] whether inference is enabled or not
    #
    # pkg:gem/alba#lib/alba.rb:123
    def inferring; end

    # Getter for inflector, a module responsible for inflecting strings
    #
    # pkg:gem/alba#lib/alba.rb:17
    def inflector; end

    # Set an inflector
    #
    # @param inflector [Symbol, Class, Module] inflector
    #   When it's a Symbol, it accepts `:default`, `:active_support` or `:dry`
    #   When it's a Class or a Module, it should have some methods, see {Alba::DefaultInflector}
    #
    # pkg:gem/alba#lib/alba.rb:133
    def inflector=(inflector); end

    # @return [Array<Class>] classes that include Enumerable but should not be treated as collections
    #
    # pkg:gem/alba#lib/alba.rb:20
    def non_collection_types; end

    # Register types, used for both builtin and custom types
    #
    # @see Alba::Type
    # @return [void]
    #
    # pkg:gem/alba#lib/alba.rb:216
    def register_type(name, check: T.unsafe(nil), converter: T.unsafe(nil), auto_convert: T.unsafe(nil)); end

    # Regularize key to be either Symbol or String depending on @symbolize_keys
    # Returns nil if key is nil
    #
    # @param key [String, Symbol, nil]
    # @return [Symbol, String, nil]
    #
    # pkg:gem/alba#lib/alba.rb:182
    def regularize_key(key); end

    # Reset config variables
    # Useful for test cleanup
    #
    # pkg:gem/alba#lib/alba.rb:231
    def reset!; end

    # @param helper [Module] helper module to include
    # @param key_transformation [Symbol] key transformation type
    # @param block [Block] resource body
    # @return [Class<Alba::Resource>] resource class
    #
    # pkg:gem/alba#lib/alba.rb:142
    def resource_class(helper: T.unsafe(nil), key_transformation: T.unsafe(nil), &block); end

    # Get a resource object from arguments
    # If block is given, it creates a resource class with the block
    # Otherwise, it behaves depending on `with` argument
    #
    # @param object [Object] the object whose class name is used for inferring resource class
    # @param params [Hash] user-given Hash for arbitrary data
    # @param with [:inference, Proc, Class<Alba::Resource>] determines how to get resource class for `object`
    #   When it's `:inference`, it infers resource class from `object`'s class name
    #   When it's a Proc, it calls the Proc with `object` as an argument
    #   When it's a Class, it uses the Class as a resource class
    #   Otherwise, it raises an ArgumentError
    # @return [Alba::Resource] resource class with `object` as its target object
    # @raise [ArgumentError] if `with` argument is not one of `:inference`, Proc or Class
    #
    # pkg:gem/alba#lib/alba.rb:262
    def resource_for(object, params: T.unsafe(nil), with: T.unsafe(nil), &block); end

    # @deprecated Use resource_for instead
    #
    # pkg:gem/alba#lib/alba.rb:244
    def resource_with(object, with: T.unsafe(nil), &block); end

    # Serialize the object with inline definitions
    #
    # @param object [Object] the object to be serialized
    # @param with [:inference, Proc, Class<Alba::Resource>] determines how to get resource class for each object
    # @param root_key [Symbol, nil, true]
    # @param block [Block] resource block
    # @return [String] serialized JSON string
    # @raise [ArgumentError] if both object and block are not given
    #
    # pkg:gem/alba#lib/alba.rb:60
    def serialize(object = T.unsafe(nil), with: T.unsafe(nil), root_key: T.unsafe(nil), &block); end

    # Configure Alba to stringify (not symbolize) keys
    #
    # pkg:gem/alba#lib/alba.rb:172
    def stringify_keys!; end

    # Configure Alba to symbolize keys
    #
    # pkg:gem/alba#lib/alba.rb:166
    def symbolize_keys!; end

    # Transform a key with given transform_type
    #
    # @param key [String] a target key
    # @param transform_type [Symbol] a transform type, either one of `camel`, `lower_camel`, `dash` or `snake`
    # @return [String]
    #
    # pkg:gem/alba#lib/alba.rb:194
    def transform_key(key, transform_type:); end

    private

    # pkg:gem/alba#lib/alba.rb:268
    def _resource_for(object, params: T.unsafe(nil), with: T.unsafe(nil), &block); end

    # pkg:gem/alba#lib/alba.rb:329
    def default_encoder; end

    # pkg:gem/alba#lib/alba.rb:335
    def hashify_collection(collection, with, root_key, &block); end

    # pkg:gem/alba#lib/alba.rb:283
    def inflector_from(name_or_module); end

    # pkg:gem/alba#lib/alba.rb:361
    def register_default_types; end

    # pkg:gem/alba#lib/alba.rb:353
    def reset_transform_keys; end

    # pkg:gem/alba#lib/alba.rb:357
    def resolved_default_superclass; end

    # pkg:gem/alba#lib/alba.rb:296
    def set_encoder_from_backend; end

    # pkg:gem/alba#lib/alba.rb:321
    def try_active_support; end

    # pkg:gem/alba#lib/alba.rb:308
    def try_oj(mode:); end

    # pkg:gem/alba#lib/alba.rb:345
    def validate_inflector(inflector); end
  end
end

# Representing association
# @api private
#
# pkg:gem/alba#lib/alba/association.rb:6
class Alba::Association
  # @param name [Symbol, String] name of the method to fetch association
  # @param condition [Proc, nil] a proc filtering data
  # @param resource [Class<Alba::Resource>, Proc, String, Symbol, nil]
  #   a resource class for the association, a proc returning a resource class or a name of the resource
  # @param source [Proc, nil] a proc to specify the source of the association
  # @param with_traits [Symbol, Array<Symbol>, nil] specified traits
  # @param params [Hash] params override for the association
  # @param nesting [String] a namespace where source class is inferred with
  # @param key_transformation [Symbol] key transformation type
  # @param helper [Module] helper module to include
  # @param block [Block] used to define resource when resource arg is absent
  #
  # pkg:gem/alba#lib/alba/association.rb:26
  def initialize(name:, condition: T.unsafe(nil), resource: T.unsafe(nil), source: T.unsafe(nil), with_traits: T.unsafe(nil), params: T.unsafe(nil), nesting: T.unsafe(nil), key_transformation: T.unsafe(nil), helper: T.unsafe(nil), &block); end

  # This is the same API in `NestedAttribute`
  #
  # @param type [String, Symbol] one of `snake`, `:camel`, `:lower_camel`, `:dash` and `none`
  # @return [void]
  #
  # pkg:gem/alba#lib/alba/association.rb:53
  def key_transformation=(type); end

  # pkg:gem/alba#lib/alba/association.rb:13
  def name; end

  # Recursively converts an object into a Hash
  #
  # @param target [Object] the object having an association method
  # @param within [Hash] determines what associations to be serialized. If not set, it serializes all associations.
  # @param params [Hash] user-given Hash for arbitrary data
  # @return [Hash]
  #
  # pkg:gem/alba#lib/alba/association.rb:63
  def to_h(target, within: T.unsafe(nil), params: T.unsafe(nil)); end

  private

  # pkg:gem/alba#lib/alba/association.rb:102
  def assign_resource(nesting, key_transformation, block, helper); end

  # pkg:gem/alba#lib/alba/association.rb:89
  def constantize(resource); end

  # pkg:gem/alba#lib/alba/association.rb:79
  def object_from(target, params); end

  # pkg:gem/alba#lib/alba/association.rb:118
  def to_h_with_constantize_resource(object, within, params); end

  # pkg:gem/alba#lib/alba/association.rb:112
  def to_h_with_each_resource(object, within, params); end

  class << self
    # cache for `const_get`
    #
    # pkg:gem/alba#lib/alba/association.rb:10
    def const_cache; end
  end
end

# Represents attribute with `if` option
# @api private
#
# pkg:gem/alba#lib/alba/conditional_attribute.rb:9
class Alba::ConditionalAttribute
  # @param body [Symbol, Proc, Alba::Association, Alba::TypedAttribute, Alba::NestedAttribute] real attribute wrapped with condition
  # @param condition [Symbol, Proc] condition to check
  #
  # pkg:gem/alba#lib/alba/conditional_attribute.rb:12
  def initialize(body:, condition:); end

  # Returns attribute body if condition passes
  #
  # @param resource [Alba::Resource]
  # @param object [Object] needed for collection, each object from collection
  # @return [Alba::REMOVE_KEY, Object] REMOVE_KEY if condition is unmet, fetched attribute otherwise
  #
  # pkg:gem/alba#lib/alba/conditional_attribute.rb:22
  def with_passing_condition(resource:, object: T.unsafe(nil)); end

  private

  # pkg:gem/alba#lib/alba/conditional_attribute.rb:35
  def condition_passes?(resource, object); end

  # pkg:gem/alba#lib/alba/conditional_attribute.rb:53
  def second_object(object, resource); end

  # pkg:gem/alba#lib/alba/conditional_attribute.rb:49
  def with_two_arity_proc_condition?; end
end

# This module has two purposes.
# One is that we require `active_support/inflector` in this module so that we don't do that all over the place.
# Another is that `ActiveSupport::Inflector` doesn't have `camelize_lower` method that we want it to have, so this module works as an adapter.
#
# pkg:gem/alba#lib/alba/default_inflector.rb:14
module Alba::DefaultInflector
  class << self
    # pkg:gem/alba#lib/alba/default_inflector.rb:28
    def camelize(*_arg0, **_arg1, &_arg2); end

    # Camelizes a key, 1st letter lowercase
    #
    # @param key [String] key to be camelized
    # @return [String] camelized key
    #
    # pkg:gem/alba#lib/alba/default_inflector.rb:35
    def camelize_lower(key); end

    # pkg:gem/alba#lib/alba/default_inflector.rb:28
    def classify(table_name, &_arg1); end

    # pkg:gem/alba#lib/alba/default_inflector.rb:28
    def dasherize(underscored_word, &_arg1); end

    # pkg:gem/alba#lib/alba/default_inflector.rb:28
    def demodulize(path, &_arg1); end

    # pkg:gem/alba#lib/alba/default_inflector.rb:28
    def pluralize(*_arg0, **_arg1, &_arg2); end

    # pkg:gem/alba#lib/alba/default_inflector.rb:28
    def underscore(camel_cased_word, &_arg1); end
  end
end

# Module for printing deprecation warning
# @api private
#
# pkg:gem/alba#lib/alba/deprecation.rb:6
module Alba::Deprecation
  private

  # Similar to {#warn} but prints caller as well
  #
  # @param message [String] main message to print
  # @return void
  #
  # pkg:gem/alba#lib/alba/deprecation.rb:11
  def warn(message); end

  class << self
    # pkg:gem/alba#lib/alba/deprecation.rb:15
    def warn(message); end
  end
end

# Base class for Errors
#
# pkg:gem/alba#lib/alba/errors.rb:5
class Alba::Error < ::StandardError; end

# Layout serialization
# @api private
#
# pkg:gem/alba#lib/alba/layout.rb:9
class Alba::Layout
  extend ::Forwardable

  # @param file [String] name of the layout file
  # @param inline [Proc] a proc returning JSON string or a Hash representing JSON
  #
  # pkg:gem/alba#lib/alba/layout.rb:16
  def initialize(file:, inline:); end

  # pkg:gem/alba#lib/alba/layout.rb:12
  def object(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/alba#lib/alba/layout.rb:12
  def params(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/alba#lib/alba/layout.rb:12
  def serializable_hash(*_arg0, **_arg1, &_arg2); end

  # Serialize within layout
  #
  # @param resource [Alba::Resource] the original resource calling this layout
  # @param serialized_json [String] JSON string for embedding
  # @param binding [Binding] context for serialization
  #
  # pkg:gem/alba#lib/alba/layout.rb:31
  def serialize(resource:, serialized_json:, binding:); end

  # pkg:gem/alba#lib/alba/layout.rb:12
  def to_h(*_arg0, **_arg1, &_arg2); end

  private

  # pkg:gem/alba#lib/alba/layout.rb:46
  def check_and_return(obj, message, klass); end

  # This methods exists here instead of delegation because
  # `Alba::Resource#encode` is private and it prints warning if we use `def_delegators`
  #
  # pkg:gem/alba#lib/alba/layout.rb:68
  def encode(hash); end

  # pkg:gem/alba#lib/alba/layout.rb:56
  def serialize_within_inline_layout; end

  # pkg:gem/alba#lib/alba/layout.rb:52
  def serialize_within_string_layout(bnd); end

  # pkg:gem/alba#lib/alba/layout.rb:44
  def serialized_json; end
end

# Representing nested attribute
# @api private
#
# pkg:gem/alba#lib/alba/nested_attribute.rb:6
class Alba::NestedAttribute
  # @param klass [Class<Alba::Resource>] the parent for this nested attribute
  # @param key_transformation [Symbol] determines how to transform keys
  # @param block [Proc] class body
  #
  # pkg:gem/alba#lib/alba/nested_attribute.rb:13
  def initialize(klass:, key_transformation: T.unsafe(nil), &block); end

  # Setter for key_transformation, used when it's changed after class definition
  #
  # pkg:gem/alba#lib/alba/nested_attribute.rb:8
  def key_transformation=(_arg0); end

  # @param object [Object] the object being serialized
  # @param params [Hash] params Hash inherited from Resource
  # @param within [Object, nil, false, true] determines what associations to be serialized. If not set, it serializes all associations.
  # @return [Hash] hash serialized from running the class body in the object
  #
  # pkg:gem/alba#lib/alba/nested_attribute.rb:23
  def value(object:, params:, within:); end
end

# pkg:gem/alba#lib/alba/constants.rb:5
Alba::REMOVE_KEY = T.let(T.unsafe(nil), Object)

# Rails integration
#
# pkg:gem/alba#lib/alba/railtie.rb:5
class Alba::Railtie < ::Rails::Railtie; end

# This module represents what should be serialized
#
# pkg:gem/alba#lib/alba/resource.rb:14
module Alba::Resource
  include ::Alba::Resource::InstanceMethods

  mixes_in_class_methods ::Alba::Resource::ClassMethods

  class << self
    # `setup` method is meta-programmatically defined here for performance.
    # @api private
    #
    # pkg:gem/alba#lib/alba/resource.rb:28
    def included(base); end
  end
end

# Class methods
#
# pkg:gem/alba#lib/alba/resource.rb:352
module Alba::Resource::ClassMethods
  # pkg:gem/alba#lib/alba/resource.rb:353
  def _attributes; end

  # pkg:gem/alba#lib/alba/resource.rb:353
  def _collection_key; end

  # pkg:gem/alba#lib/alba/resource.rb:353
  def _helper; end

  # pkg:gem/alba#lib/alba/resource.rb:353
  def _key; end

  # pkg:gem/alba#lib/alba/resource.rb:353
  def _key_for_collection; end

  # pkg:gem/alba#lib/alba/resource.rb:353
  def _key_transformation_cascade; end

  # pkg:gem/alba#lib/alba/resource.rb:353
  def _layout; end

  # pkg:gem/alba#lib/alba/resource.rb:353
  def _meta; end

  # pkg:gem/alba#lib/alba/resource.rb:353
  def _on_error; end

  # pkg:gem/alba#lib/alba/resource.rb:353
  def _on_nil; end

  # pkg:gem/alba#lib/alba/resource.rb:353
  def _resource_methods; end

  # pkg:gem/alba#lib/alba/resource.rb:353
  def _select_arity; end

  # pkg:gem/alba#lib/alba/resource.rb:353
  def _traits; end

  # pkg:gem/alba#lib/alba/resource.rb:353
  def _transform_type; end

  # pkg:gem/alba#lib/alba/resource.rb:353
  def _transforming_root_key; end

  # Set association
  #
  # @param name [String, Symbol] name of the association, used as key when `key` param doesn't exist
  # @param condition [Proc, nil] a Proc to modify the association
  # @param resource [Class<Alba::Resource>, String, Proc, nil] representing resource for this association
  # @param serializer [Class<Alba::Resource>, String, Proc, nil] alias for `resource`
  # @param source [Proc, nil] a Proc to customize the association source
  # @param key [String, Symbol, nil] used as key when given
  # @param with_traits [Symbol, Array<Symbol>, nil] specified traits
  # @param params [Hash] params override for the association
  # @param options [Hash<Symbol, Proc>]
  # @option options [Proc, Symbol, nil] if a condition to decide if this association should be serialized
  #   When it's Proc, it's called to check condition
  #   When it's Symbol, it's treated as a method name on the Resource and the method is called
  # @param block [Block]
  # @return [void]
  # @see Alba::Association#initialize
  #
  # pkg:gem/alba#lib/alba/resource.rb:454
  def association(name, condition = T.unsafe(nil), resource: T.unsafe(nil), serializer: T.unsafe(nil), source: T.unsafe(nil), key: T.unsafe(nil), with_traits: T.unsafe(nil), params: T.unsafe(nil), **options, &block); end

  # Set an attribute with the given block
  #
  # @param name [String, Symbol] key name
  # @param if [Proc] condition to decide if it should serialize these attributes
  # @param block [Block] the block called during serialization
  # @raise [ArgumentError] if block is absent
  # @return [void]
  #
  # pkg:gem/alba#lib/alba/resource.rb:424
  def attribute(name = T.unsafe(nil), if: T.unsafe(nil), **name_with_type, &block); end

  # Set multiple attributes at once
  #
  # @param attrs [Array<String, Symbol>]
  # @param if [Proc] condition to decide if it should serialize these attributes
  # @param attrs_with_types [Hash{Symbol, String => Array<Symbol, Proc>, Symbol}]
  #   attributes with name in its key and type and optional type converter in its value
  # @return [void]
  #
  # pkg:gem/alba#lib/alba/resource.rb:391
  def attributes(*attrs, if: T.unsafe(nil), **attrs_with_types); end

  # Sets key for collection serialization
  #
  # @param key [String, Symbol]
  # @return [void]
  #
  # pkg:gem/alba#lib/alba/resource.rb:593
  def collection_key(key); end

  # pkg:gem/alba#lib/alba/resource.rb:467
  def has_many(name, condition = T.unsafe(nil), resource: T.unsafe(nil), serializer: T.unsafe(nil), source: T.unsafe(nil), key: T.unsafe(nil), with_traits: T.unsafe(nil), params: T.unsafe(nil), **options, &block); end

  # pkg:gem/alba#lib/alba/resource.rb:466
  def has_one(name, condition = T.unsafe(nil), resource: T.unsafe(nil), serializer: T.unsafe(nil), source: T.unsafe(nil), key: T.unsafe(nil), with_traits: T.unsafe(nil), params: T.unsafe(nil), **options, &block); end

  # Define helper methods
  #
  # @param mod [Module] a module to extend
  # @return [void]
  #
  # pkg:gem/alba#lib/alba/resource.rb:633
  def helper(mod = T.unsafe(nil), &block); end

  # @api private
  #
  # pkg:gem/alba#lib/alba/resource.rb:377
  def inherited(subclass); end

  # Set layout
  #
  # @param file [String] name of the layout file
  # @param inline [Proc] a proc returning JSON string or a Hash representing JSON
  # @return [void]
  #
  # pkg:gem/alba#lib/alba/resource.rb:547
  def layout(file: T.unsafe(nil), inline: T.unsafe(nil)); end

  # pkg:gem/alba#lib/alba/resource.rb:465
  def many(name, condition = T.unsafe(nil), resource: T.unsafe(nil), serializer: T.unsafe(nil), source: T.unsafe(nil), key: T.unsafe(nil), with_traits: T.unsafe(nil), params: T.unsafe(nil), **options, &block); end

  # Set metadata
  # @return [void]
  #
  # pkg:gem/alba#lib/alba/resource.rb:538
  def meta(key = T.unsafe(nil), &block); end

  # This `method_added` is used for defining "resource methods"
  #
  # pkg:gem/alba#lib/alba/resource.rb:356
  def method_added(method_name); end

  # pkg:gem/alba#lib/alba/resource.rb:493
  def nested(name, **options, &block); end

  # Set a nested attribute with the given block
  #
  # @param name [String, Symbol] key name
  # @param options [Hash<Symbol, Proc>]
  # @option options [Proc] if a condition to decide if this attribute should be serialized
  # @param block [Block] the block called during serialization
  # @raise [ArgumentError] if block is absent
  # @return [void]
  #
  # pkg:gem/alba#lib/alba/resource.rb:486
  def nested_attribute(name, **options, &block); end

  # Set error handler
  # If this is set it's used as a error handler overriding global one
  #
  # @param handler [Symbol] `:raise`, `:ignore` or `:nullify`
  # @param block [Block]
  # @return [void]
  #
  # pkg:gem/alba#lib/alba/resource.rb:603
  def on_error(handler = T.unsafe(nil), &block); end

  # Set nil handler
  #
  # @param block [Block]
  # @return [void]
  #
  # pkg:gem/alba#lib/alba/resource.rb:625
  def on_nil(&block); end

  # pkg:gem/alba#lib/alba/resource.rb:464
  def one(name, condition = T.unsafe(nil), resource: T.unsafe(nil), serializer: T.unsafe(nil), source: T.unsafe(nil), key: T.unsafe(nil), with_traits: T.unsafe(nil), params: T.unsafe(nil), **options, &block); end

  # DSL for alias, purely for readability
  # @return [void]
  #
  # pkg:gem/alba#lib/alba/resource.rb:649
  def prefer_object_method!; end

  # DSL for alias, purely for readability
  # @return [void]
  #
  # pkg:gem/alba#lib/alba/resource.rb:643
  def prefer_resource_method!; end

  # Set root key
  #
  # @param key [String, Symbol]
  # @param key_for_collection [String, Symbol]
  # @raise [NoMethodError] when key doesn't respond to `to_sym` method
  # @return [void]
  #
  # pkg:gem/alba#lib/alba/resource.rb:514
  def root_key(key, key_for_collection = T.unsafe(nil)); end

  # Set root key to true
  # @return [void]
  #
  # pkg:gem/alba#lib/alba/resource.rb:531
  def root_key!; end

  # Set root key for collection
  #
  # @param key [String, Symbol]
  # @raise [NoMethodError] when key doesn't respond to `to_sym` method
  # @return [void]
  #
  # pkg:gem/alba#lib/alba/resource.rb:524
  def root_key_for_collection(key); end

  # Set a trait
  #
  # @param name [String, Symbol] name of the trait
  # @param block [Block] the "content" of the trait
  # @raise [ArgumentError] if block is absent
  # @return [void]
  #
  # pkg:gem/alba#lib/alba/resource.rb:501
  def trait(name, &block); end

  # Transform keys as specified type
  #
  # @param type [String, Symbol] one of `snake`, `:camel`, `:lower_camel`, `:dash` and `none`
  # @param root [Boolean] decides if root key also should be transformed
  # @param cascade [Boolean] decides if key transformation cascades into inline association
  #   Default is true but can be set false for old (v1) behavior
  # @raise [Alba::Error] when type is not supported
  # @return [void]
  #
  # pkg:gem/alba#lib/alba/resource.rb:559
  def transform_keys(type, root: T.unsafe(nil), cascade: T.unsafe(nil)); end

  # Transform keys as specified type AFTER the class is defined
  # Note that this is an experimental API and may be removed/changed
  #
  # @see #transform_keys
  #
  # pkg:gem/alba#lib/alba/resource.rb:575
  def transform_keys!(type); end

  private

  # pkg:gem/alba#lib/alba/resource.rb:397
  def assign_attributes(attrs, if_value); end

  # pkg:gem/alba#lib/alba/resource.rb:406
  def assign_attributes_with_types(attrs_with_types, if_value, &block); end

  # pkg:gem/alba#lib/alba/resource.rb:469
  def nesting; end

  # pkg:gem/alba#lib/alba/resource.rb:610
  def validated_error_handler(handler); end
end

# pkg:gem/alba#lib/alba/resource.rb:23
Alba::Resource::EMPTY_HASH = T.let(T.unsafe(nil), Hash)

# @!parse include InstanceMethods
# @!parse extend ClassMethods
#
# pkg:gem/alba#lib/alba/resource.rb:17
Alba::Resource::INTERNAL_VARIABLES = T.let(T.unsafe(nil), Hash)

# Instance methods
#
# pkg:gem/alba#lib/alba/resource.rb:46
module Alba::Resource::InstanceMethods
  # @param object [Object] the object to be serialized
  # @param params [Hash] user-given Hash for arbitrary data
  # @param within [Alba::WITHIN_DEFAULT, Hash, Array, nil, false, true]
  #   determines what associations to be serialized. If not set, it serializes all associations.
  # @param with_traits [Symbol, Array<Symbol>, nil] specified traits
  # @param select [Method] DEPRECATED noop
  #
  # pkg:gem/alba#lib/alba/resource.rb:55
  def initialize(object, params: T.unsafe(nil), within: T.unsafe(nil), with_traits: T.unsafe(nil), select: T.unsafe(nil)); end

  # Returns a Hash corresponding {#serialize}
  #
  # @param _options [Hash] dummy parameter for Rails compatibility
  # @param root_key [Symbol, nil]
  # @param meta [Hash] metadata for this serialization
  # @return [Hash]
  #
  # pkg:gem/alba#lib/alba/resource.rb:96
  def as_json(_options = T.unsafe(nil), root_key: T.unsafe(nil), meta: T.unsafe(nil)); end

  # pkg:gem/alba#lib/alba/resource.rb:47
  def object; end

  # pkg:gem/alba#lib/alba/resource.rb:47
  def params; end

  # A Hash for serialization
  #
  # @return [Hash]
  #
  # pkg:gem/alba#lib/alba/resource.rb:110
  def serializable_hash; end

  # Serialize object into JSON string
  #
  # @param root_key [Symbol, nil]
  # @param meta [Hash] metadata for this serialization
  # @return [String] serialized JSON string
  #
  # pkg:gem/alba#lib/alba/resource.rb:69
  def serialize(root_key: T.unsafe(nil), meta: T.unsafe(nil)); end

  # pkg:gem/alba#lib/alba/resource.rb:113
  def to_h; end

  # For Rails compatibility
  # The first options is a dummy parameter
  #
  # @see #serialize
  # @see https://github.com/rails/rails/blob/7-0-stable/actionpack/lib/action_controller/metal/renderers.rb#L156
  #
  # pkg:gem/alba#lib/alba/resource.rb:78
  def to_json(options = T.unsafe(nil), root_key: T.unsafe(nil), meta: T.unsafe(nil)); end

  private

  # pkg:gem/alba#lib/alba/resource.rb:309
  def _fetch_attribute_from_object_first(obj, attribute); end

  # pkg:gem/alba#lib/alba/resource.rb:317
  def _fetch_attribute_from_resource_first(obj, attribute); end

  # pkg:gem/alba#lib/alba/resource.rb:193
  def _key; end

  # pkg:gem/alba#lib/alba/resource.rb:188
  def _key_for_collection; end

  # pkg:gem/alba#lib/alba/resource.rb:154
  def _metadata(block, meta); end

  # This is default behavior for getting attributes for serialization
  # Override this method to filter certain attributes
  #
  # @deprecated in favor of `select`
  #
  # pkg:gem/alba#lib/alba/resource.rb:243
  def attributes; end

  # pkg:gem/alba#lib/alba/resource.rb:228
  def attributes_to_hash(obj, hash); end

  # pkg:gem/alba#lib/alba/resource.rb:338
  def check_within(association_name); end

  # pkg:gem/alba#lib/alba/resource.rb:219
  def collection_converter; end

  # pkg:gem/alba#lib/alba/resource.rb:213
  def converter; end

  # pkg:gem/alba#lib/alba/resource.rb:130
  def deprecated_serializable_hash; end

  # pkg:gem/alba#lib/alba/resource.rb:170
  def deprecated_serializable_hash_for_collection; end

  # pkg:gem/alba#lib/alba/resource.rb:262
  def do_select(key, value, attribute); end

  # pkg:gem/alba#lib/alba/resource.rb:290
  def fetch_attribute(obj, key, attribute); end

  # pkg:gem/alba#lib/alba/resource.rb:305
  def fetch_attribute_from_object_and_resource(obj, attribute); end

  # @return [String]
  #
  # pkg:gem/alba#lib/alba/resource.rb:183
  def fetch_key; end

  # pkg:gem/alba#lib/alba/resource.rb:269
  def handle_error(error, obj, key, attribute, hash); end

  # pkg:gem/alba#lib/alba/resource.rb:117
  def hash_from_traits(obj); end

  # pkg:gem/alba#lib/alba/resource.rb:141
  def hash_with_metadata(hash, meta); end

  # pkg:gem/alba#lib/alba/resource.rb:329
  def nil_handler; end

  # pkg:gem/alba#lib/alba/resource.rb:198
  def resource_name(pluralized: T.unsafe(nil)); end

  # Default implementation for selecting attributes
  # Override this method to filter attributes based on key and value
  #
  # pkg:gem/alba#lib/alba/resource.rb:249
  def select(_key, _value, _attribute); end

  # pkg:gem/alba#lib/alba/resource.rb:158
  def serializable_hash_for_collection; end

  # pkg:gem/alba#lib/alba/resource.rb:134
  def serialize_with(hash); end

  # pkg:gem/alba#lib/alba/resource.rb:253
  def set_key_and_attribute_body_from(obj, key, attribute, hash); end

  # pkg:gem/alba#lib/alba/resource.rb:284
  def transform_key(key); end

  # pkg:gem/alba#lib/alba/resource.rb:209
  def transforming_root_key?; end

  # pkg:gem/alba#lib/alba/resource.rb:333
  def yield_if_within(association_name); end
end

# pkg:gem/alba#lib/alba/resource.rb:20
Alba::Resource::WITHIN_DEFAULT = T.let(T.unsafe(nil), Object)

# pkg:gem/alba#lib/alba/resource.rb:655
Alba::Serializer = Alba::Resource

# Representing type itself, combined with {Alba::TypedAttribute}
#
# pkg:gem/alba#lib/alba/type.rb:5
class Alba::Type
  # @param name [Symbol, String] name of the type
  # @param check [Proc, Boolean] proc to check type
  #   If false, type check is skipped
  # @param converter [Proc] proc to convert type
  # @param auto_convert [Boolean] whether to convert type automatically
  #
  # pkg:gem/alba#lib/alba/type.rb:14
  def initialize(name, check:, converter:, auto_convert: T.unsafe(nil)); end

  # pkg:gem/alba#lib/alba/type.rb:7
  def auto_convert=(_arg0); end

  # Enable auto convert with given converter
  # @param converter [Proc] proc to convert type
  #
  # pkg:gem/alba#lib/alba/type.rb:40
  def auto_convert_with(converter); end

  # Type check
  #
  # @param value [Object] value to check
  # @return [Boolean] the result of type check
  #
  # pkg:gem/alba#lib/alba/type.rb:25
  def check(value); end

  # Type convert
  # If @auto_convert is true, @convert proc is called with obj
  # Otherwise, it raises an exception that is caught by {Alba::TypedAttribute}
  #
  # @param obj [Object] object to convert
  #
  # pkg:gem/alba#lib/alba/type.rb:34
  def convert(obj); end

  # pkg:gem/alba#lib/alba/type.rb:6
  def name; end
end

# Representing typed attributes to encapsulate logic about types
# @api private
#
# pkg:gem/alba#lib/alba/typed_attribute.rb:6
class Alba::TypedAttribute
  # @param name [Symbol, String]
  # @param type [Symbol, Class]
  # @param converter [Proc, true, false, nil]
  #
  # pkg:gem/alba#lib/alba/typed_attribute.rb:12
  def initialize(name:, type:, converter:, &block); end

  # pkg:gem/alba#lib/alba/typed_attribute.rb:7
  def name; end

  # @return [String, Integer, Boolean] type-checked or type-converted object
  #
  # pkg:gem/alba#lib/alba/typed_attribute.rb:25
  def value(object: T.unsafe(nil)); end

  private

  # pkg:gem/alba#lib/alba/typed_attribute.rb:35
  def display_value_for(value); end
end

# Error class for backend which is not supported
#
# pkg:gem/alba#lib/alba/errors.rb:8
class Alba::UnsupportedBackend < ::Alba::Error; end

# Error class for type which is not supported
#
# pkg:gem/alba#lib/alba/errors.rb:11
class Alba::UnsupportedType < ::Alba::Error; end

# pkg:gem/alba#lib/alba/version.rb:4
Alba::VERSION = T.let(T.unsafe(nil), String)
