# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `amazing_print` gem.
# Please instead update this file by running `bin/tapioca gem amazing_print`.


class ActionView::Base
  include ::ERB::Escape
  include ::ActiveSupport::CoreExt::ERBUtil
  include ::ActiveSupport::CoreExt::ERBUtilPrivate
  include ::ActiveSupport::Benchmarkable
  include ::ActionView::Helpers::ActiveModelHelper
  include ::ActionView::Helpers::AssetUrlHelper
  include ::ActionView::Helpers::CaptureHelper
  include ::ActionView::Helpers::OutputSafetyHelper
  include ::ActionView::Helpers::TagHelper
  include ::ActionView::Helpers::AssetTagHelper
  include ::ActionView::Helpers::AtomFeedHelper
  include ::ActionView::Helpers::CacheHelper
  include ::ActionView::Helpers::ContentExfiltrationPreventionHelper
  include ::ActionView::Helpers::ControllerHelper
  include ::ActionView::Helpers::CspHelper
  include ::ActionView::Helpers::CsrfHelper
  include ::ActionView::Helpers::DateHelper
  include ::ActionView::Helpers::DebugHelper
  include ::ActionView::ModelNaming
  include ::ActionView::RecordIdentifier
  include ::Lexxy::FormHelper
  include ::ActionView::Helpers::FormOptionsHelper
  include ::ActionView::Helpers::JavaScriptHelper
  include ::ActionView::Helpers::NumberHelper
  include ::ActionView::Helpers::RenderingHelper
  include ::AmazingPrint::ActionView
end

# Copyright (c) 2010-2016 Michael Dvorkin and contributors
#
# AmazingPrint is freely distributable under the terms of MIT license.
# See LICENSE file or http://www.opensource.org/licenses/mit-license.php
# ------------------------------------------------------------------------------
#
# Helper module for hash_format: :json
#
# pkg:gem/amazing_print#lib/amazing_print/custom_defaults.rb:3
module AmazingPrint
  class << self
    # pkg:gem/amazing_print#lib/amazing_print/custom_defaults.rb:14
    def console?; end

    # pkg:gem/amazing_print#lib/amazing_print/custom_defaults.rb:5
    def defaults; end

    # pkg:gem/amazing_print#lib/amazing_print/custom_defaults.rb:5
    def defaults=(_arg0); end

    # pkg:gem/amazing_print#lib/amazing_print/custom_defaults.rb:22
    def diet_rb; end

    # pkg:gem/amazing_print#lib/amazing_print/custom_defaults.rb:5
    def force_colors; end

    # Class accessor to force colorized output (ex. forked subprocess where TERM
    # might be dumb).
    # ---------------------------------------------------------------------------
    #
    # pkg:gem/amazing_print#lib/amazing_print/custom_defaults.rb:10
    def force_colors!(colors: T.unsafe(nil)); end

    # pkg:gem/amazing_print#lib/amazing_print/custom_defaults.rb:5
    def force_colors=(_arg0); end

    # pkg:gem/amazing_print#lib/amazing_print/custom_defaults.rb:40
    def irb!; end

    # pkg:gem/amazing_print#lib/amazing_print/custom_defaults.rb:46
    def pry!; end

    # pkg:gem/amazing_print#lib/amazing_print/custom_defaults.rb:18
    def rails_console?; end

    # pkg:gem/amazing_print#lib/amazing_print/custom_defaults.rb:56
    def rdbg!; end

    # Reload the cached custom configurations.
    #
    # pkg:gem/amazing_print#lib/amazing_print/custom_defaults.rb:88
    def reload!; end

    # pkg:gem/amazing_print#lib/amazing_print/custom_defaults.rb:30
    def usual_rb; end

    # pkg:gem/amazing_print#lib/amazing_print/version.rb:9
    def version; end

    private

    # Takes a value and returns true unless it is false or nil
    # This is an alternative to the less readable !!(value)
    # https://github.com/bbatsov/ruby-style-guide#no-bang-bang
    #
    # pkg:gem/amazing_print#lib/amazing_print/custom_defaults.rb:97
    def boolean(value); end
  end
end

# pkg:gem/amazing_print#lib/amazing_print/ext/action_view.rb:9
module AmazingPrint::ActionView
  # pkg:gem/amazing_print#lib/amazing_print/ext/action_view.rb:20
  def ap(object, options = T.unsafe(nil)); end

  # Use HTML colors and add default "debug_dump" class to the resulting HTML.
  #
  # pkg:gem/amazing_print#lib/amazing_print/ext/action_view.rb:11
  def ap_debug(object, options = T.unsafe(nil)); end
end

# pkg:gem/amazing_print#lib/amazing_print/ext/active_record.rb:9
module AmazingPrint::ActiveRecord
  # Add ActiveRecord class names to the dispatcher pipeline.
  # ------------------------------------------------------------------------------
  #
  # pkg:gem/amazing_print#lib/amazing_print/ext/active_record.rb:17
  def cast_with_active_record(object, type); end

  private

  # Format ActiveModel class object.
  # ------------------------------------------------------------------------------
  #
  # pkg:gem/amazing_print#lib/amazing_print/ext/active_record.rb:93
  def awesome_active_model_class(object); end

  # Format ActiveModel error object.
  # ------------------------------------------------------------------------------
  #
  # pkg:gem/amazing_print#lib/amazing_print/ext/active_record.rb:106
  def awesome_active_model_error(object); end

  # Format ActiveModel instance object.
  # ------------------------------------------------------------------------------
  #
  # pkg:gem/amazing_print#lib/amazing_print/ext/active_record.rb:80
  def awesome_active_model_instance(object); end

  # Format ActiveRecord class object.
  # ------------------------------------------------------------------------------
  #
  # pkg:gem/amazing_print#lib/amazing_print/ext/active_record.rb:67
  def awesome_active_record_class(object); end

  # Format ActiveRecord instance object.
  #
  # NOTE: by default only instance attributes (i.e. columns) are shown. To format
  # ActiveRecord instance as regular object showing its instance variables and
  # accessors use :raw => true option:
  #
  # ap record, :raw => true
  #
  # ------------------------------------------------------------------------------
  #
  # pkg:gem/amazing_print#lib/amazing_print/ext/active_record.rb:48
  def awesome_active_record_instance(object); end

  class << self
    # pkg:gem/amazing_print#lib/amazing_print/ext/active_record.rb:10
    def included(base); end
  end
end

# pkg:gem/amazing_print#lib/amazing_print/ext/active_support.rb:9
module AmazingPrint::ActiveSupport
  # Format ActiveSupport::TimeWithZone as standard Time.
  # ------------------------------------------------------------------------------
  #
  # pkg:gem/amazing_print#lib/amazing_print/ext/active_support.rb:29
  def awesome_active_support_time(object); end

  # Format HashWithIndifferentAccess as standard Hash.
  # ------------------------------------------------------------------------------
  #
  # pkg:gem/amazing_print#lib/amazing_print/ext/active_support.rb:35
  def awesome_hash_with_indifferent_access(object); end

  # pkg:gem/amazing_print#lib/amazing_print/ext/active_support.rb:15
  def cast_with_active_support(object, type); end

  class << self
    # pkg:gem/amazing_print#lib/amazing_print/ext/active_support.rb:10
    def included(base); end
  end
end

# pkg:gem/amazing_print#lib/amazing_print/colorize.rb:8
module AmazingPrint::Colorize
  # Pick the color and apply it to the given string as necessary.
  # ------------------------------------------------------------------------------
  #
  # pkg:gem/amazing_print#lib/amazing_print/colorize.rb:11
  def colorize(str, type); end
end

# pkg:gem/amazing_print#lib/amazing_print/colors.rb:4
module AmazingPrint::Colors
  private

  # pkg:gem/amazing_print#lib/amazing_print/colors.rb:25
  def blue(str, html = T.unsafe(nil)); end

  # pkg:gem/amazing_print#lib/amazing_print/colors.rb:32
  def blueish(str, html = T.unsafe(nil)); end

  # pkg:gem/amazing_print#lib/amazing_print/colors.rb:25
  def cyan(str, html = T.unsafe(nil)); end

  # pkg:gem/amazing_print#lib/amazing_print/colors.rb:32
  def cyanish(str, html = T.unsafe(nil)); end

  # pkg:gem/amazing_print#lib/amazing_print/colors.rb:25
  def gray(str, html = T.unsafe(nil)); end

  # pkg:gem/amazing_print#lib/amazing_print/colors.rb:32
  def grayish(str, html = T.unsafe(nil)); end

  # pkg:gem/amazing_print#lib/amazing_print/colors.rb:25
  def green(str, html = T.unsafe(nil)); end

  # pkg:gem/amazing_print#lib/amazing_print/colors.rb:32
  def greenish(str, html = T.unsafe(nil)); end

  # pkg:gem/amazing_print#lib/amazing_print/colors.rb:25
  def purple(str, html = T.unsafe(nil)); end

  # pkg:gem/amazing_print#lib/amazing_print/colors.rb:32
  def purpleish(str, html = T.unsafe(nil)); end

  # pkg:gem/amazing_print#lib/amazing_print/colors.rb:25
  def red(str, html = T.unsafe(nil)); end

  # pkg:gem/amazing_print#lib/amazing_print/colors.rb:32
  def redish(str, html = T.unsafe(nil)); end

  # pkg:gem/amazing_print#lib/amazing_print/colors.rb:25
  def white(str, html = T.unsafe(nil)); end

  # pkg:gem/amazing_print#lib/amazing_print/colors.rb:32
  def whiteish(str, html = T.unsafe(nil)); end

  # pkg:gem/amazing_print#lib/amazing_print/colors.rb:25
  def yellow(str, html = T.unsafe(nil)); end

  # pkg:gem/amazing_print#lib/amazing_print/colors.rb:32
  def yellowish(str, html = T.unsafe(nil)); end

  class << self
    # pkg:gem/amazing_print#lib/amazing_print/colors.rb:25
    def blue(str, html = T.unsafe(nil)); end

    # pkg:gem/amazing_print#lib/amazing_print/colors.rb:32
    def blueish(str, html = T.unsafe(nil)); end

    # pkg:gem/amazing_print#lib/amazing_print/colors.rb:25
    def cyan(str, html = T.unsafe(nil)); end

    # pkg:gem/amazing_print#lib/amazing_print/colors.rb:32
    def cyanish(str, html = T.unsafe(nil)); end

    # pkg:gem/amazing_print#lib/amazing_print/colors.rb:25
    def gray(str, html = T.unsafe(nil)); end

    # pkg:gem/amazing_print#lib/amazing_print/colors.rb:32
    def grayish(str, html = T.unsafe(nil)); end

    # pkg:gem/amazing_print#lib/amazing_print/colors.rb:25
    def green(str, html = T.unsafe(nil)); end

    # pkg:gem/amazing_print#lib/amazing_print/colors.rb:32
    def greenish(str, html = T.unsafe(nil)); end

    # pkg:gem/amazing_print#lib/amazing_print/colors.rb:25
    def purple(str, html = T.unsafe(nil)); end

    # pkg:gem/amazing_print#lib/amazing_print/colors.rb:32
    def purpleish(str, html = T.unsafe(nil)); end

    # pkg:gem/amazing_print#lib/amazing_print/colors.rb:25
    def red(str, html = T.unsafe(nil)); end

    # pkg:gem/amazing_print#lib/amazing_print/colors.rb:32
    def redish(str, html = T.unsafe(nil)); end

    # pkg:gem/amazing_print#lib/amazing_print/colors.rb:25
    def white(str, html = T.unsafe(nil)); end

    # pkg:gem/amazing_print#lib/amazing_print/colors.rb:32
    def whiteish(str, html = T.unsafe(nil)); end

    # pkg:gem/amazing_print#lib/amazing_print/colors.rb:25
    def yellow(str, html = T.unsafe(nil)); end

    # pkg:gem/amazing_print#lib/amazing_print/colors.rb:32
    def yellowish(str, html = T.unsafe(nil)); end
  end
end

# Attempt to load extensions up to 3 times since this library may be required
# before dependencies that we have extensions for.
#
# pkg:gem/amazing_print#lib/amazing_print/ext_loader.rb:8
class AmazingPrint::ExtLoader
  class << self
    # pkg:gem/amazing_print#lib/amazing_print/ext_loader.rb:13
    def call; end
  end
end

# pkg:gem/amazing_print#lib/amazing_print/ext_loader.rb:9
AmazingPrint::ExtLoader::EXT_LOAD_ATTEMPT_LIMIT = T.let(T.unsafe(nil), Integer)

# pkg:gem/amazing_print#lib/amazing_print/formatter.rb:11
class AmazingPrint::Formatter
  include ::AmazingPrint::Colorize
  include ::AmazingPrint::ActiveRecord
  include ::AmazingPrint::ActiveSupport
  include ::AmazingPrint::Nokogiri
  include ::AmazingPrint::OpenStruct

  # pkg:gem/amazing_print#lib/amazing_print/formatter.rb:18
  def initialize(inspector); end

  # Hook this when adding custom formatters. Check out lib/amazing_print/ext
  # directory for custom formatters that ship with amazing_print.
  # ------------------------------------------------------------------------------
  #
  # pkg:gem/amazing_print#lib/amazing_print/formatter.rb:37
  def cast(object, type); end

  # pkg:gem/amazing_print#lib/amazing_print/ext/active_record.rb:11
  def cast_without_active_record(_object, type); end

  # pkg:gem/amazing_print#lib/amazing_print/ext/active_support.rb:11
  def cast_without_active_support(object, type); end

  # pkg:gem/amazing_print#lib/amazing_print/ext/nokogiri.rb:11
  def cast_without_nokogiri(object, type); end

  # pkg:gem/amazing_print#lib/amazing_print/ext/ostruct.rb:11
  def cast_without_ostruct(object, type); end

  # Main entry point to format an object.
  # ------------------------------------------------------------------------------
  #
  # pkg:gem/amazing_print#lib/amazing_print/formatter.rb:25
  def format(object, type = T.unsafe(nil)); end

  # pkg:gem/amazing_print#lib/amazing_print/formatter.rb:14
  def inspector; end

  # pkg:gem/amazing_print#lib/amazing_print/formatter.rb:14
  def options; end

  private

  # pkg:gem/amazing_print#lib/amazing_print/formatter.rb:71
  def awesome_array(a); end

  # pkg:gem/amazing_print#lib/amazing_print/formatter.rb:55
  def awesome_bigdecimal(n); end

  # pkg:gem/amazing_print#lib/amazing_print/formatter.rb:96
  def awesome_class(c); end

  # pkg:gem/amazing_print#lib/amazing_print/formatter.rb:104
  def awesome_dir(d); end

  # pkg:gem/amazing_print#lib/amazing_print/formatter.rb:100
  def awesome_file(f); end

  # pkg:gem/amazing_print#lib/amazing_print/formatter.rb:79
  def awesome_hash(h); end

  # pkg:gem/amazing_print#lib/amazing_print/formatter.rb:91
  def awesome_method(m); end

  # pkg:gem/amazing_print#lib/amazing_print/formatter.rb:83
  def awesome_object(o); end

  # pkg:gem/amazing_print#lib/amazing_print/formatter.rb:61
  def awesome_rational(n); end

  # Catch all method to format an arbitrary object.
  # ------------------------------------------------------------------------------
  #
  # pkg:gem/amazing_print#lib/amazing_print/formatter.rb:45
  def awesome_self(object, type); end

  # pkg:gem/amazing_print#lib/amazing_print/formatter.rb:75
  def awesome_set(s); end

  # pkg:gem/amazing_print#lib/amazing_print/formatter.rb:67
  def awesome_simple(o, type, inspector = T.unsafe(nil)); end

  # pkg:gem/amazing_print#lib/amazing_print/formatter.rb:87
  def awesome_struct(s); end

  # pkg:gem/amazing_print#lib/amazing_print/formatter.rb:94
  def awesome_unboundmethod(m); end

  # Utility methods.
  # ------------------------------------------------------------------------------
  #
  # pkg:gem/amazing_print#lib/amazing_print/formatter.rb:110
  def convert_to_hash(object); end
end

# pkg:gem/amazing_print#lib/amazing_print/formatter.rb:16
AmazingPrint::Formatter::CORE_FORMATTERS = T.let(T.unsafe(nil), Array)

# pkg:gem/amazing_print#lib/amazing_print/formatters.rb:4
module AmazingPrint::Formatters; end

# pkg:gem/amazing_print#lib/amazing_print/formatters/array_formatter.rb:8
class AmazingPrint::Formatters::ArrayFormatter < ::AmazingPrint::Formatters::BaseFormatter
  include ::AmazingPrint::JSONHelper

  # pkg:gem/amazing_print#lib/amazing_print/formatters/array_formatter.rb:13
  def initialize(array, inspector); end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/array_formatter.rb:11
  def array; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/array_formatter.rb:20
  def format; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/array_formatter.rb:11
  def inspector; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/array_formatter.rb:11
  def options; end

  private

  # pkg:gem/amazing_print#lib/amazing_print/formatters/array_formatter.rb:64
  def array_prefix(iteration, width); end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/array_formatter.rb:118
  def find_method(name); end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/array_formatter.rb:54
  def generate_printable_array; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/array_formatter.rb:76
  def generate_printable_tuples; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/array_formatter.rb:109
  def generate_tuple(name); end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/array_formatter.rb:134
  def generic_prefix(iteration, width, padding = T.unsafe(nil)); end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/array_formatter.rb:68
  def methods_array; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/array_formatter.rb:32
  def methods_array?; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/array_formatter.rb:44
  def multiline_array; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/array_formatter.rb:99
  def name_and_args_width; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/array_formatter.rb:36
  def simple_array; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/array_formatter.rb:105
  def tuple_prefix(iteration, width); end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/array_formatter.rb:84
  def tuple_template(item); end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/array_formatter.rb:95
  def tuples; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/array_formatter.rb:142
  def width(items); end
end

# pkg:gem/amazing_print#lib/amazing_print/formatters/base_formatter.rb:7
class AmazingPrint::Formatters::BaseFormatter
  include ::AmazingPrint::Colorize

  # pkg:gem/amazing_print#lib/amazing_print/formatters/base_formatter.rb:130
  def align(value, width); end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/base_formatter.rb:146
  def colorless(string); end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/base_formatter.rb:151
  def colorless_size(string); end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/base_formatter.rb:36
  def get_limit_size; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/base_formatter.rb:120
  def indent(n = T.unsafe(nil)); end

  # Indentation related methods
  # -----------------------------------------
  #
  # pkg:gem/amazing_print#lib/amazing_print/formatters/base_formatter.rb:109
  def indentation; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/base_formatter.rb:113
  def indented(&); end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/base_formatter.rb:45
  def limited(data, width, is_hash: T.unsafe(nil)); end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/base_formatter.rb:67
  def method_tuple(method); end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/base_formatter.rb:124
  def outdent; end

  # To support limited output, for example:
  #
  # ap ('a'..'z').to_a, :limit => 3
  # [
  #     [ 0] "a",
  #     [ 1] .. [24],
  #     [25] "z"
  # ]
  #
  # ap (1..100).to_a, :limit => true # Default limit is 7.
  # [
  #     [ 0] 1,
  #     [ 1] 2,
  #     [ 2] 3,
  #     [ 3] .. [96],
  #     [97] 98,
  #     [98] 99,
  #     [99] 100
  # ]
  # ------------------------------------------------------------------------------
  #
  # pkg:gem/amazing_print#lib/amazing_print/formatters/base_formatter.rb:32
  def should_be_limited?; end
end

# pkg:gem/amazing_print#lib/amazing_print/formatters/base_formatter.rb:10
AmazingPrint::Formatters::BaseFormatter::DEFAULT_LIMIT_SIZE = T.let(T.unsafe(nil), Integer)

# precompute common indentations
#
# pkg:gem/amazing_print#lib/amazing_print/formatters/base_formatter.rb:118
AmazingPrint::Formatters::BaseFormatter::INDENT_CACHE = T.let(T.unsafe(nil), Array)

# pkg:gem/amazing_print#lib/amazing_print/formatters/class_formatter.rb:7
class AmazingPrint::Formatters::ClassFormatter < ::AmazingPrint::Formatters::BaseFormatter
  # pkg:gem/amazing_print#lib/amazing_print/formatters/class_formatter.rb:10
  def initialize(klass, inspector); end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/class_formatter.rb:17
  def format; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/class_formatter.rb:8
  def inspector; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/class_formatter.rb:8
  def klass; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/class_formatter.rb:8
  def options; end
end

# pkg:gem/amazing_print#lib/amazing_print/formatters/dir_formatter.rb:10
class AmazingPrint::Formatters::DirFormatter < ::AmazingPrint::Formatters::BaseFormatter
  # pkg:gem/amazing_print#lib/amazing_print/formatters/dir_formatter.rb:13
  def initialize(dir, inspector); end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/dir_formatter.rb:11
  def dir; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/dir_formatter.rb:20
  def format; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/dir_formatter.rb:25
  def info; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/dir_formatter.rb:11
  def inspector; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/dir_formatter.rb:11
  def options; end
end

# pkg:gem/amazing_print#lib/amazing_print/formatters/file_formatter.rb:10
class AmazingPrint::Formatters::FileFormatter < ::AmazingPrint::Formatters::BaseFormatter
  # pkg:gem/amazing_print#lib/amazing_print/formatters/file_formatter.rb:13
  def initialize(file, inspector); end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/file_formatter.rb:11
  def file; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/file_formatter.rb:20
  def format; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/file_formatter.rb:25
  def info; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/file_formatter.rb:11
  def inspector; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/file_formatter.rb:11
  def options; end
end

# pkg:gem/amazing_print#lib/amazing_print/formatters/hash_formatter.rb:8
class AmazingPrint::Formatters::HashFormatter < ::AmazingPrint::Formatters::BaseFormatter
  include ::AmazingPrint::JSONHelper

  # pkg:gem/amazing_print#lib/amazing_print/formatters/hash_formatter.rb:17
  def initialize(hash, inspector); end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/hash_formatter.rb:29
  def format; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/hash_formatter.rb:15
  def hash; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/hash_formatter.rb:15
  def inspector; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/hash_formatter.rb:15
  def options; end

  private

  # pkg:gem/amazing_print#lib/amazing_print/formatters/hash_formatter.rb:41
  def empty_hash; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/hash_formatter.rb:149
  def format_key(key); end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/hash_formatter.rb:117
  def json_format?; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/hash_formatter.rb:121
  def json_syntax(key, value, width); end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/hash_formatter.rb:83
  def key_size(key); end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/hash_formatter.rb:77
  def left_width(keys); end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/hash_formatter.rb:93
  def max_key_width(keys); end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/hash_formatter.rb:49
  def multiline_hash; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/hash_formatter.rb:45
  def multiline_hash?; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/hash_formatter.rb:157
  def no_colors; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/hash_formatter.rb:143
  def pre_ruby19_syntax(key, value, width); end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/hash_formatter.rb:57
  def printable_hash; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/hash_formatter.rb:97
  def printable_keys; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/hash_formatter.rb:133
  def ruby19_syntax(key, value, width); end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/hash_formatter.rb:53
  def simple_hash; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/hash_formatter.rb:165
  def single_line; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/hash_formatter.rb:109
  def string?(key); end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/hash_formatter.rb:113
  def symbol?(key); end
end

# pkg:gem/amazing_print#lib/amazing_print/formatters/hash_formatter.rb:13
class AmazingPrint::Formatters::HashFormatter::InvalidHashFormatError < ::StandardError; end

# pkg:gem/amazing_print#lib/amazing_print/formatters/hash_formatter.rb:11
AmazingPrint::Formatters::HashFormatter::VALID_HASH_FORMATS = T.let(T.unsafe(nil), Array)

# pkg:gem/amazing_print#lib/amazing_print/formatters/method_formatter.rb:7
class AmazingPrint::Formatters::MethodFormatter < ::AmazingPrint::Formatters::BaseFormatter
  # pkg:gem/amazing_print#lib/amazing_print/formatters/method_formatter.rb:10
  def initialize(method, inspector); end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/method_formatter.rb:17
  def format; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/method_formatter.rb:8
  def inspector; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/method_formatter.rb:8
  def method; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/method_formatter.rb:8
  def options; end
end

# pkg:gem/amazing_print#lib/amazing_print/formatters/object_formatter.rb:7
class AmazingPrint::Formatters::ObjectFormatter < ::AmazingPrint::Formatters::BaseFormatter
  # pkg:gem/amazing_print#lib/amazing_print/formatters/object_formatter.rb:10
  def initialize(object, inspector); end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/object_formatter.rb:18
  def format; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/object_formatter.rb:8
  def inspector; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/object_formatter.rb:8
  def object; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/object_formatter.rb:8
  def options; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/object_formatter.rb:8
  def variables; end

  private

  # pkg:gem/amazing_print#lib/amazing_print/formatters/object_formatter.rb:64
  def awesome_instance; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/object_formatter.rb:74
  def left_aligned; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/object_formatter.rb:60
  def valid_instance_var?(variable_name); end
end

# pkg:gem/amazing_print#lib/amazing_print/formatters/simple_formatter.rb:7
class AmazingPrint::Formatters::SimpleFormatter < ::AmazingPrint::Formatters::BaseFormatter
  # pkg:gem/amazing_print#lib/amazing_print/formatters/simple_formatter.rb:10
  def initialize(string, type, inspector); end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/simple_formatter.rb:18
  def format; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/simple_formatter.rb:8
  def inspector; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/simple_formatter.rb:8
  def options; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/simple_formatter.rb:8
  def string; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/simple_formatter.rb:8
  def type; end
end

# pkg:gem/amazing_print#lib/amazing_print/formatters/struct_formatter.rb:7
class AmazingPrint::Formatters::StructFormatter < ::AmazingPrint::Formatters::BaseFormatter
  # pkg:gem/amazing_print#lib/amazing_print/formatters/struct_formatter.rb:10
  def initialize(struct, inspector); end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/struct_formatter.rb:18
  def format; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/struct_formatter.rb:8
  def inspector; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/struct_formatter.rb:8
  def options; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/struct_formatter.rb:8
  def struct; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/struct_formatter.rb:8
  def variables; end

  private

  # pkg:gem/amazing_print#lib/amazing_print/formatters/struct_formatter.rb:60
  def awesome_instance; end

  # pkg:gem/amazing_print#lib/amazing_print/formatters/struct_formatter.rb:71
  def left_aligned; end
end

# pkg:gem/amazing_print#lib/amazing_print/indentator.rb:4
class AmazingPrint::Indentator
  # pkg:gem/amazing_print#lib/amazing_print/indentator.rb:7
  def initialize(indentation); end

  # pkg:gem/amazing_print#lib/amazing_print/indentator.rb:12
  def indent; end

  # pkg:gem/amazing_print#lib/amazing_print/indentator.rb:5
  def indentation; end

  # pkg:gem/amazing_print#lib/amazing_print/indentator.rb:5
  def shift_width; end
end

# pkg:gem/amazing_print#lib/amazing_print/inspector.rb:15
class AmazingPrint::Inspector
  # pkg:gem/amazing_print#lib/amazing_print/inspector.rb:29
  def initialize(options = T.unsafe(nil)); end

  # Dispatcher that detects data nesting and invokes object-aware formatter.
  # ---------------------------------------------------------------------------
  #
  # pkg:gem/amazing_print#lib/amazing_print/inspector.rb:88
  def awesome(object); end

  # Return true if we are to colorize the output.
  # ---------------------------------------------------------------------------
  #
  # pkg:gem/amazing_print#lib/amazing_print/inspector.rb:103
  def colorize?; end

  # pkg:gem/amazing_print#lib/amazing_print/inspector.rb:78
  def current_indentation; end

  # pkg:gem/amazing_print#lib/amazing_print/inspector.rb:82
  def increase_indentation(&); end

  # pkg:gem/amazing_print#lib/amazing_print/inspector.rb:16
  def indentator; end

  # pkg:gem/amazing_print#lib/amazing_print/inspector.rb:16
  def indentator=(_arg0); end

  # pkg:gem/amazing_print#lib/amazing_print/inspector.rb:16
  def options; end

  # pkg:gem/amazing_print#lib/amazing_print/inspector.rb:16
  def options=(_arg0); end

  private

  # pkg:gem/amazing_print#lib/amazing_print/inspector.rb:192
  def dotfile_readable?(dotfile); end

  # pkg:gem/amazing_print#lib/amazing_print/inspector.rb:172
  def find_dotfile; end

  # This method needs to be mocked during testing so that it always loads
  # predictable values
  # ---------------------------------------------------------------------------
  #
  # pkg:gem/amazing_print#lib/amazing_print/inspector.rb:185
  def load_dotfile; end

  # Load ~/.aprc file with custom defaults that override default options.
  # ---------------------------------------------------------------------------
  #
  # pkg:gem/amazing_print#lib/amazing_print/inspector.rb:200
  def merge_custom_defaults!; end

  # Update @options by first merging the :color hash and then the remaining
  # keys.
  # ---------------------------------------------------------------------------
  #
  # pkg:gem/amazing_print#lib/amazing_print/inspector.rb:165
  def merge_options!(options = T.unsafe(nil)); end

  # Format nested data, for example:
  #   arr = [1, 2]; arr << arr
  #   => [1,2, [...]]
  #   hash = { :a => 1 }; hash[:b] = hash
  #   => { :a => 1, :b => {...} }
  # ---------------------------------------------------------------------------
  #
  # pkg:gem/amazing_print#lib/amazing_print/inspector.rb:128
  def nested(object); end

  # Turn class name into symbol, ex: Hello::World => :hello_world. Classes
  # that inherit from Array, Hash, File, Dir, and Struct are treated as the
  # base class.
  # ---------------------------------------------------------------------------
  #
  # pkg:gem/amazing_print#lib/amazing_print/inspector.rb:146
  def printable(object); end

  # ---------------------------------------------------------------------------
  #
  # pkg:gem/amazing_print#lib/amazing_print/inspector.rb:138
  def unnested(object); end

  class << self
    # Unload the cached dotfile and load it again.
    #
    # pkg:gem/amazing_print#lib/amazing_print/inspector.rb:23
    def reload_dotfile; end
  end
end

# pkg:gem/amazing_print#lib/amazing_print/inspector.rb:18
AmazingPrint::Inspector::AP = T.let(T.unsafe(nil), Symbol)

# pkg:gem/amazing_print#lib/amazing_print/json_helper.rb:7
module AmazingPrint::JSONHelper
  # pkg:gem/amazing_print#lib/amazing_print/json_helper.rb:10
  def json_awesome(object, is_key: T.unsafe(nil)); end
end

# pkg:gem/amazing_print#lib/amazing_print/json_helper.rb:8
AmazingPrint::JSONHelper::VALUE_CLASSES_NOT_TO_CONVERT = T.let(T.unsafe(nil), Array)

# pkg:gem/amazing_print#lib/amazing_print/core_ext/logger.rb:9
module AmazingPrint::Logger
  # Add ap method to logger
  # ------------------------------------------------------------------------------
  #
  # pkg:gem/amazing_print#lib/amazing_print/core_ext/logger.rb:12
  def ap(object, options = T.unsafe(nil)); end
end

# pkg:gem/amazing_print#lib/amazing_print/ext/nokogiri.rb:9
module AmazingPrint::Nokogiri
  # ------------------------------------------------------------------------------
  #
  # pkg:gem/amazing_print#lib/amazing_print/ext/nokogiri.rb:27
  def awesome_nokogiri_xml_node(object); end

  # Add Nokogiri XML Node and NodeSet names to the dispatcher pipeline.
  # ------------------------------------------------------------------------------
  #
  # pkg:gem/amazing_print#lib/amazing_print/ext/nokogiri.rb:17
  def cast_with_nokogiri(object, type); end

  class << self
    # pkg:gem/amazing_print#lib/amazing_print/ext/nokogiri.rb:10
    def included(base); end
  end
end

# pkg:gem/amazing_print#lib/amazing_print/ext/ostruct.rb:9
module AmazingPrint::OpenStruct
  # pkg:gem/amazing_print#lib/amazing_print/ext/ostruct.rb:21
  def awesome_open_struct_instance(object); end

  # pkg:gem/amazing_print#lib/amazing_print/ext/ostruct.rb:15
  def cast_with_ostruct(object, type); end

  class << self
    # pkg:gem/amazing_print#lib/amazing_print/ext/ostruct.rb:10
    def included(base); end
  end
end

# Copyright (c) 2010-2016 Michael Dvorkin and contributors
#
# AmazingPrint is freely distributable under the terms of MIT license.
# See LICENSE file or http://www.opensource.org/licenses/mit-license.php
# ------------------------------------------------------------------------------
#
# The following makes it possible to invoke amazing_print while performing
# operations on method arrays, ex:
#
#   ap [].methods - Object.methods
#   ap ''.methods.grep(/!|\?/)
#
# If you could think of a better way please let me know :-)
#
# pkg:gem/amazing_print#lib/amazing_print/core_ext/awesome_method_array.rb:17
module AwesomeMethodArray
  # pkg:gem/amazing_print#lib/amazing_print/core_ext/awesome_method_array.rb:24
  def &(other); end

  # pkg:gem/amazing_print#lib/amazing_print/core_ext/awesome_method_array.rb:18
  def -(other); end

  # Intercepting Array#grep needs a special treatment since grep accepts
  # an optional block.
  #
  # pkg:gem/amazing_print#lib/amazing_print/core_ext/awesome_method_array.rb:34
  def grep(pattern, &blk); end
end

# Copyright (c) 2010-2016 Michael Dvorkin and contributors
#
# AmazingPrint is freely distributable under the terms of MIT license.
# See LICENSE file or http://www.opensource.org/licenses/mit-license.php
# ------------------------------------------------------------------------------
#
# pkg:gem/amazing_print#lib/amazing_print/core_ext/kernel.rb:8
module Kernel
  # pkg:gem/amazing_print#lib/amazing_print/core_ext/kernel.rb:9
  def ai(options = T.unsafe(nil)); end

  # pkg:gem/amazing_print#lib/amazing_print/core_ext/kernel.rb:24
  def amazing_print(object, options = T.unsafe(nil)); end

  # pkg:gem/amazing_print#lib/amazing_print/core_ext/kernel.rb:18
  def awesome_inspect(options = T.unsafe(nil)); end

  private

  # pkg:gem/amazing_print#lib/amazing_print/core_ext/kernel.rb:20
  def ap(object, options = T.unsafe(nil)); end

  class << self
    # pkg:gem/amazing_print#lib/amazing_print/core_ext/kernel.rb:26
    def ap(object, options = T.unsafe(nil)); end
  end
end

class Logger
  include ::Honeybadger::Breadcrumbs::LogHelper
  include ::AmazingPrint::Logger
end
