# typed: false

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `fedipub` gem.
# Please instead update this file by running `bin/tapioca gem fedipub`.


# This module includes classes and methods related to Ruby on Rails: engine configuration, models, controllers, etc.
# rbs_inline: enabled
#
# pkg:gem/fedipub#lib/fedipub/version.rb:4
module Fedipub
  # pkg:gem/fedipub#lib/fedipub.rb:27
  def configuration; end

  class << self
    # @return [Hash] The configuration for the given actor entity
    #
    # pkg:gem/fedipub#lib/fedipub.rb:75
    sig { params(class_or_instance: ::Object).returns(T::Hash[::Symbol, ::Object]) }
    def actor_entity(class_or_instance); end

    # @return [Boolean] True if the given model is a possible actor
    #
    # @example
    #   puts "Follow #{some_actor.name}" if actor_entity? current_user
    #
    # pkg:gem/fedipub#lib/fedipub.rb:69
    sig { params(class_or_instance: ::Object).returns(T::Boolean) }
    def actor_entity?(class_or_instance); end

    # pkg:gem/fedipub#lib/fedipub.rb:43
    sig { params(name: T.any(::String, ::Symbol)).void }
    def config_from(name); end

    # pkg:gem/fedipub#lib/fedipub.rb:27
    def configuration; end

    # pkg:gem/fedipub#lib/fedipub.rb:31
    def configure(&); end

    # @return [Boolean] True if the given model is a possible data entity
    #
    # pkg:gem/fedipub#lib/fedipub.rb:84
    sig { params(class_or_instance: ::Object).returns(T::Boolean) }
    def data_entity?(class_or_instance); end

    # @return [Hash] The configuration for the given data entity
    #
    # pkg:gem/fedipub#lib/fedipub.rb:128
    sig { params(class_or_instance: ::Object).returns(T::Hash[::Symbol, ::Object]) }
    def data_entity_configuration(class_or_instance); end

    # Finds configured data type from route path segment
    #
    # @param route_path_segment [Symbol, String] Route path segment, as configured with `:route_path_segment`
    # @return [Hash, nil] Entity configuration
    #
    # @example
    #   data_entity_handled_on :articles
    #
    # pkg:gem/fedipub#lib/fedipub.rb:121
    def data_entity_handled_on(route_path_segment); end

    # Finds the configured handler for a given ActivityPub object
    #
    # @param hash [Hash] ActivityPub object hash
    #
    # @return [Hash, nil] Data entity configuration
    #
    # pkg:gem/fedipub#lib/fedipub.rb:104
    def data_entity_handler_for(hash); end

    # Finds configured data types from ActivityPub type
    #
    # @param type [String] ActivityPub object type, as configured with `:handles`
    # @return [Array] List of data entity configurations
    #
    # @example
    #   data_entity_handlers_for 'Note'
    #
    # pkg:gem/fedipub#lib/fedipub.rb:95
    def data_entity_handlers_for(type); end

    # pkg:gem/fedipub#lib/fedipub.rb:37
    sig { returns(::Logger) }
    def logger; end

    # pkg:gem/fedipub#lib/fedipub/engine.rb:11
    def railtie_helpers_paths; end

    # pkg:gem/fedipub#lib/fedipub/engine.rb:11
    def railtie_namespace; end

    # pkg:gem/fedipub#lib/fedipub/engine.rb:11
    def railtie_routes_url_helpers(include_path_helpers = T.unsafe(nil)); end

    # pkg:gem/fedipub#lib/fedipub/engine.rb:11
    def table_name_prefix; end

    # pkg:gem/fedipub#lib/fedipub/engine.rb:11
    def use_relative_model_naming?; end

    private

    # @return [String] Class name of the provided class or instance
    #
    # pkg:gem/fedipub#lib/fedipub.rb:139
    sig { params(class_or_instance: ::Object).returns(T.nilable(::String)) }
    def class_or_instance_name(class_or_instance); end
  end
end

class Fedipub::Activity < ::Fedipub::ApplicationRecord
  include ::Fedipub::Activity::GeneratedAttributeMethods
  include ::Fedipub::Activity::GeneratedAssociationMethods
  include ::Fedipub::HasUuid
  extend ::Fedipub::HasUuid::ClassMethods

  def _run_commit_callbacks(&block); end
  def _run_save_callbacks(&block); end
  def autosave_associated_records_for_actor(*args); end
  def autosave_associated_records_for_entity(*args); end

  sig { returns(T.nilable(::ActiveRecord::Base)) }
  def entity; end

  def undo!; end

  private

  sig { returns(T::Boolean) }
  def deliverable?; end

  sig { void }
  def post_to_inboxes; end

  sig { void }
  def set_default_addressing; end

  class << self
    def feed_for(*args, **); end

    private

    def __class_attr___callbacks; end
    def __class_attr___callbacks=(new_value); end
    def __class_attr__reflections; end
    def __class_attr__reflections=(new_value); end
    def __class_attr__validators; end
    def __class_attr__validators=(new_value); end
    def __class_attr_defined_enums; end
    def __class_attr_defined_enums=(new_value); end
  end
end

module Fedipub::Activity::GeneratedAssociationMethods
  def actor; end
  def actor=(value); end
  def actor_changed?; end
  def actor_previously_changed?; end
  def build_actor(*args, &block); end
  def create_actor(*args, &block); end
  def create_actor!(*args, &block); end
  def entity; end
  def entity=(value); end
  def entity_changed?; end
  def entity_previously_changed?; end
  def reload_actor; end
  def reload_entity; end
  def reset_actor; end
  def reset_entity; end
end

module Fedipub::Activity::GeneratedAttributeMethods; end

class Fedipub::Actor < ::Fedipub::ApplicationRecord
  include ::Fedipub::Actor::GeneratedAttributeMethods
  include ::Fedipub::Actor::GeneratedAssociationMethods
  include ::Fedipub::HasUuid
  include ::Fedipub::HandlesDeleteRequests
  include ::Fedipub::Likeable
  include ::Fedipub::Announceable
  include ::Fedipub::ApplicationActor
  extend ::Fedipub::HasUuid::ClassMethods
  extend ::Fedipub::HandlesDeleteRequests::ClassMethods
  extend ::Fedipub::ApplicationActor::ClassMethods

  def _on_fedipub_delete_requested_callbacks; end
  def _on_fedipub_undelete_requested_callbacks; end
  def _run_create_callbacks(&block); end
  def _run_destroy_callbacks(&block); end
  def _run_on_fedipub_delete_requested_callbacks(&block); end
  def _run_on_fedipub_delete_requested_callbacks!(&block); end
  def _run_on_fedipub_undelete_requested_callbacks(&block); end
  def _run_on_fedipub_undelete_requested_callbacks!(&block); end
  def _run_save_callbacks(&block); end
  def _run_update_callbacks(&block); end

  sig { returns(::String) }
  def acct_uri; end

  sig { returns(T.nilable(::String)) }
  def actor_type; end

  sig { params(prefix: ::String).returns(::String) }
  def at_address(prefix: T.unsafe(nil)); end

  def autosave_associated_records_for_accepted_followers(*args); end
  def autosave_associated_records_for_accepted_following_followers(*args); end
  def autosave_associated_records_for_accepted_following_follows(*args); end
  def autosave_associated_records_for_accepted_follows(*args); end
  def autosave_associated_records_for_activities(*args); end
  def autosave_associated_records_for_activities_as_entity(*args); end
  def autosave_associated_records_for_entity(*args); end
  def autosave_associated_records_for_featured_items(*args); end
  def autosave_associated_records_for_featured_tags(*args); end
  def autosave_associated_records_for_followers(*args); end
  def autosave_associated_records_for_following_followers(*args); end
  def autosave_associated_records_for_following_follows(*args); end
  def autosave_associated_records_for_follows(*args); end
  def autosave_associated_records_for_host(*args); end

  sig { returns(T::Boolean) }
  def distant?; end

  sig { returns(T::Hash[::Symbol, T.untyped]) }
  def entity_configuration; end

  sig { params(federated_url: ::String).returns(::Fedipub::FeaturedItem) }
  def feature(federated_url); end

  sig { returns(T.nilable(::String)) }
  def federated_url; end

  sig { params(actor: ::Fedipub::Actor).returns(T.any(::FalseClass, ::Fedipub::Following)) }
  def followed_by?(actor); end

  sig { returns(T.nilable(::String)) }
  def followers_url; end

  sig { returns(T.nilable(::String)) }
  def followings_url; end

  sig { params(actor: ::Fedipub::Actor).returns(T.any(::FalseClass, ::Fedipub::Following)) }
  def follows?(actor); end

  sig { returns(T.nilable(::String)) }
  def inbox_url; end

  sig { returns(::String) }
  def key_id; end

  sig { returns(T.nilable(::String)) }
  def name; end

  sig { returns(T.nilable(::String)) }
  def outbox_url; end

  sig { returns(T.nilable(::String)) }
  def private_key; end

  sig { returns(T.nilable(::String)) }
  def profile_url; end

  sig { returns(T.nilable(::String)) }
  def public_key; end

  sig { returns(T.nilable(::String)) }
  def server; end

  sig { returns(T.nilable(::String)) }
  def shared_inbox_url; end

  sig { returns(::String) }
  def short_at_address; end

  sig { returns(T::Boolean) }
  def sync!; end

  sig { returns(::Fedipub::Actor) }
  def tombstone!; end

  sig { returns(T::Boolean) }
  def tombstoned?; end

  sig { params(federated_url: ::String).returns(T.nilable(::Fedipub::FeaturedItem)) }
  def unfeature(federated_url); end

  sig { void }
  def untombstone!; end

  sig { returns(T.nilable(::String)) }
  def username; end

  def validate_associated_records_for_accepted_followers(*args); end
  def validate_associated_records_for_accepted_following_followers(*args); end
  def validate_associated_records_for_accepted_following_follows(*args); end
  def validate_associated_records_for_accepted_follows(*args); end
  def validate_associated_records_for_activities(*args); end
  def validate_associated_records_for_activities_as_entity(*args); end
  def validate_associated_records_for_featured_items(*args); end
  def validate_associated_records_for_featured_tags(*args); end
  def validate_associated_records_for_followers(*args); end
  def validate_associated_records_for_following_followers(*args); end
  def validate_associated_records_for_following_follows(*args); end
  def validate_associated_records_for_follows(*args); end

  private

  def create_fedipub_activity(action, actor: T.unsafe(nil), to: T.unsafe(nil), cc: T.unsafe(nil)); end

  sig { void }
  def ensure_key_pair_exists!; end

  sig { returns(T::Hash[::Symbol, ::String]) }
  def generate_key_pair; end

  sig { returns(T::Boolean) }
  def use_entity_attributes?; end

  class << self
    def _on_fedipub_delete_requested_callbacks; end
    def _on_fedipub_delete_requested_callbacks=(value); end
    def _on_fedipub_undelete_requested_callbacks; end
    def _on_fedipub_undelete_requested_callbacks=(value); end
    def distant(*args, **); end

    sig { params(account: ::String).returns(::Fedipub::Actor) }
    def find_by_account(account); end

    sig { params(federated_url: T.nilable(::String)).returns(T.nilable(::Fedipub::Actor)) }
    def find_by_federation_url(federated_url); end

    sig { params(federated_url: T.nilable(::String)).returns(::Fedipub::Actor) }
    def find_by_federation_url!(federated_url); end

    sig { params(username: ::String).returns(T.nilable(::Fedipub::Actor)) }
    def find_local_by_username(username); end

    sig { params(username: ::String).returns(::Fedipub::Actor) }
    def find_local_by_username!(username); end

    sig { params(account: ::String).returns(::Fedipub::Actor) }
    def find_or_create_by_account(account); end

    sig { params(url: T.nilable(::String)).returns(::Fedipub::Actor) }
    def find_or_create_by_federation_url(url); end

    sig { params(object: ::Object).returns(::Fedipub::Actor) }
    def find_or_create_by_object(object); end

    def local(*args, **); end
    def not_tombstoned(*args, **); end
    def tombstoned(*args, **); end

    private

    def __class_attr___callbacks; end
    def __class_attr___callbacks=(new_value); end
    def __class_attr__reflections; end
    def __class_attr__reflections=(new_value); end
    def __class_attr__validators; end
    def __class_attr__validators=(new_value); end
    def __class_attr_defined_enums; end
    def __class_attr_defined_enums=(new_value); end
  end
end

module Fedipub::Actor::GeneratedAssociationMethods
  def accepted_follow_ids; end
  def accepted_follow_ids=(ids); end
  def accepted_follower_ids; end
  def accepted_follower_ids=(ids); end
  def accepted_followers; end
  def accepted_followers=(value); end
  def accepted_following_follow_ids; end
  def accepted_following_follow_ids=(ids); end
  def accepted_following_follower_ids; end
  def accepted_following_follower_ids=(ids); end
  def accepted_following_followers; end
  def accepted_following_followers=(value); end
  def accepted_following_follows; end
  def accepted_following_follows=(value); end
  def accepted_follows; end
  def accepted_follows=(value); end
  def activities; end
  def activities=(value); end
  def activities_as_entity; end
  def activities_as_entity=(value); end
  def activities_as_entity_ids; end
  def activities_as_entity_ids=(ids); end
  def activity_ids; end
  def activity_ids=(ids); end
  def build_host(*args, &block); end
  def create_host(*args, &block); end
  def create_host!(*args, &block); end
  def entity; end
  def entity=(value); end
  def entity_changed?; end
  def entity_previously_changed?; end
  def featured_item_ids; end
  def featured_item_ids=(ids); end
  def featured_items; end
  def featured_items=(value); end
  def featured_tag_ids; end
  def featured_tag_ids=(ids); end
  def featured_tags; end
  def featured_tags=(value); end
  def follow_ids; end
  def follow_ids=(ids); end
  def follower_ids; end
  def follower_ids=(ids); end
  def followers; end
  def followers=(value); end
  def following_follow_ids; end
  def following_follow_ids=(ids); end
  def following_follower_ids; end
  def following_follower_ids=(ids); end
  def following_followers; end
  def following_followers=(value); end
  def following_follows; end
  def following_follows=(value); end
  def follows; end
  def follows=(value); end
  def host; end
  def host=(value); end
  def host_changed?; end
  def host_previously_changed?; end
  def reload_entity; end
  def reload_host; end
  def reset_entity; end
  def reset_host; end
end

module Fedipub::Actor::GeneratedAttributeMethods; end
class Fedipub::Actor::TombstonedError < ::StandardError; end

module Fedipub::ActorEntity
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::Fedipub::ActorEntity::ClassMethods

  sig { returns(T::Hash[T.any(::String, ::Symbol), T.untyped]) }
  def to_activitypub_object; end

  private

  sig { returns(::Fedipub::Actor) }
  def create_fedipub_actor; end

  sig { returns(T::Boolean) }
  def create_fedipub_actor_as_local?; end

  sig { returns(T.nilable(::Fedipub::Activity)) }
  def create_fedipub_update_activity; end

  sig { returns(T.nilable(::Fedipub::Actor)) }
  def tombstone_fedipub_actor!; end

  sig { void }
  def untombstone_fedipub_actor!; end
end

module Fedipub::ActorEntity::ClassMethods
  sig do
    params(
      name_field: ::Symbol,
      username_field: ::Symbol,
      profile_url_method: T.nilable(::Symbol),
      actor_type: ::String,
      user_count_method: T.nilable(::Symbol),
      auto_create_actors: T::Boolean
    ).void
  end
  def acts_as_fedipub_actor(name_field:, username_field:, profile_url_method: T.unsafe(nil), actor_type: T.unsafe(nil), user_count_method: T.unsafe(nil), auto_create_actors: T.unsafe(nil)); end

  sig { params(activity_type: ::String, object_type: ::String, method_name: ::Symbol).void }
  def after_activity_received(activity_type, object_type, method_name); end

  sig { params(method_name: ::Symbol).returns(::Symbol) }
  def after_follow_accepted(method_name); end

  sig { params(method_name: ::Symbol).returns(::Symbol) }
  def after_followed(method_name); end

  private

  def dispatch_callback(name, instance, *); end

  sig { params(instance: T.untyped, follow: ::Fedipub::Following, follow_activity: ::Fedipub::Activity).void }
  def dispatch_followed_callback(instance, follow, follow_activity:); end
end

Fedipub::ActorEntity::ClassMethods::FOLLOW_ACTIVITY_KWARG_TYPES = T.let(T.unsafe(nil), Array)

module Fedipub::Announceable
  extend ::ActiveSupport::Concern

  def announce!(actor: T.unsafe(nil)); end
end

module Fedipub::ApplicationActor
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::Fedipub::ApplicationActor::ClassMethods

  def application_actor?; end
end

Fedipub::ApplicationActor::APPLICATION_ACTOR_ATTRIBUTES = T.let(T.unsafe(nil), Hash)

module Fedipub::ApplicationActor::ClassMethods
  def application_actor; end
end

class Fedipub::ApplicationJob < ::ActiveJob::Base
  class << self
    private

    def __class_attr_after_discard_procs; end
    def __class_attr_after_discard_procs=(new_value); end
    def __class_attr_queue_name; end
    def __class_attr_queue_name=(new_value); end
    def __class_attr_rescue_handlers; end
    def __class_attr_rescue_handlers=(new_value); end
  end
end

class Fedipub::ApplicationMailer < ::ActionMailer::Base
  private

  def _layout(lookup_context, formats, keys); end

  class << self
    def _routes; end

    private

    def __class_attr__layout; end
    def __class_attr__layout=(new_value); end
    def __class_attr__layout_conditions; end
    def __class_attr__layout_conditions=(new_value); end
    def __class_attr_config; end
    def __class_attr_config=(new_value); end
    def __class_attr_default_params; end
    def __class_attr_default_params=(new_value); end
  end
end

class Fedipub::ApplicationRecord < ::ActiveRecord::Base
  include ::Fedipub::ApplicationRecord::GeneratedAttributeMethods
  include ::Fedipub::ApplicationRecord::GeneratedAssociationMethods

  class << self
    private

    def __class_attr__validators; end
    def __class_attr__validators=(new_value); end
    def __class_attr_defined_enums; end
    def __class_attr_defined_enums=(new_value); end
  end
end

module Fedipub::ApplicationRecord::GeneratedAssociationMethods; end
module Fedipub::ApplicationRecord::GeneratedAttributeMethods; end

class Fedipub::Block < ::Fedipub::ApplicationRecord
  include ::Fedipub::Block::GeneratedAttributeMethods
  include ::Fedipub::Block::GeneratedAssociationMethods

  def _run_save_callbacks(&block); end
  def autosave_associated_records_for_actor(*args); end
  def autosave_associated_records_for_target_actor(*args); end

  class << self
    private

    def __class_attr___callbacks; end
    def __class_attr___callbacks=(new_value); end
    def __class_attr__reflections; end
    def __class_attr__reflections=(new_value); end
    def __class_attr__validators; end
    def __class_attr__validators=(new_value); end
    def __class_attr_defined_enums; end
    def __class_attr_defined_enums=(new_value); end
  end
end

module Fedipub::Block::GeneratedAssociationMethods
  def actor; end
  def actor=(value); end
  def actor_changed?; end
  def actor_previously_changed?; end
  def build_actor(*args, &block); end
  def build_target_actor(*args, &block); end
  def create_actor(*args, &block); end
  def create_actor!(*args, &block); end
  def create_target_actor(*args, &block); end
  def create_target_actor!(*args, &block); end
  def reload_actor; end
  def reload_target_actor; end
  def reset_actor; end
  def reset_target_actor; end
  def target_actor; end
  def target_actor=(value); end
  def target_actor_changed?; end
  def target_actor_previously_changed?; end
end

module Fedipub::Block::GeneratedAttributeMethods; end
module Fedipub::Client; end

class Fedipub::Client::ActivitiesController < ::Fedipub::ClientController
  def feed; end
  def index; end

  private

  def _layout(lookup_context, formats, keys); end
  def authorize_action!; end

  class << self
    private

    def __class_attr___callbacks; end
    def __class_attr___callbacks=(new_value); end
    def __class_attr__wrapper_options; end
    def __class_attr__wrapper_options=(new_value); end
    def __class_attr_config; end
    def __class_attr_config=(new_value); end
    def __class_attr_helpers_path; end
    def __class_attr_helpers_path=(new_value); end
    def __class_attr_middleware_stack; end
    def __class_attr_middleware_stack=(new_value); end
  end
end

class Fedipub::Client::ActivityPolicy < ::Fedipub::FedipubPolicy
  def feed?; end
end

class Fedipub::Client::ActivityResource < ::Fedipub::Client::BaseResource; end

class Fedipub::Client::ActorPolicy < ::Fedipub::FedipubPolicy
  def lookup?; end
end

class Fedipub::Client::ActorPolicy::Scope < ::Fedipub::FedipubPolicy::Scope
  def resolve; end
end

class Fedipub::Client::ActorResource < ::Fedipub::Client::BaseResource; end

class Fedipub::Client::ActorsController < ::Fedipub::ClientController
  def index; end
  def lookup; end
  def show; end

  private

  def _layout(lookup_context, formats, keys); end
  def account_param; end
  def render_show; end
  def set_actor; end

  class << self
    private

    def __class_attr___callbacks; end
    def __class_attr___callbacks=(new_value); end
    def __class_attr__wrapper_options; end
    def __class_attr__wrapper_options=(new_value); end
    def __class_attr_config; end
    def __class_attr_config=(new_value); end
    def __class_attr_helpers_path; end
    def __class_attr_helpers_path=(new_value); end
    def __class_attr_middleware_stack; end
    def __class_attr_middleware_stack=(new_value); end
  end
end

class Fedipub::Client::BaseResource
  include ::Alba::Resource
  include ::Alba::Resource::InstanceMethods
  extend ::Alba::Resource::ClassMethods

  def encode(hash); end

  private

  def _setup; end
end

class Fedipub::Client::FollowingPolicy < ::Fedipub::FedipubPolicy
  def accept?; end
  def destroy?; end
  def follow?; end
  def show?; end

  private

  def in_following?; end
end

class Fedipub::Client::FollowingPolicy::Scope < ::Fedipub::FedipubPolicy::Scope
  def resolve; end
end

class Fedipub::Client::FollowingResource < ::Fedipub::Client::BaseResource; end

class Fedipub::Client::FollowingsController < ::Fedipub::ClientController
  def accept; end
  def create; end
  def destroy; end
  def follow; end
  def new; end

  private

  def _layout(lookup_context, formats, keys); end
  def following_account_params; end
  def following_params; end
  def save_and_render; end
  def set_following; end

  class << self
    private

    def __class_attr___callbacks; end
    def __class_attr___callbacks=(new_value); end
    def __class_attr__wrapper_options; end
    def __class_attr__wrapper_options=(new_value); end
    def __class_attr_config; end
    def __class_attr_config=(new_value); end
    def __class_attr_helpers_path; end
    def __class_attr_helpers_path=(new_value); end
    def __class_attr_middleware_stack; end
    def __class_attr_middleware_stack=(new_value); end
  end
end

class Fedipub::ClientController < ::Fedipub::ApplicationController
  include ::Pundit::Authorization

  private

  def _layout(lookup_context, formats, keys); end
  def _layout_from_proc(controller); end
  def render_serialized(resource_class, object, status: T.unsafe(nil), location: T.unsafe(nil), params: T.unsafe(nil)); end

  class << self
    private

    def __class_attr___callbacks; end
    def __class_attr___callbacks=(new_value); end
    def __class_attr__helper_methods; end
    def __class_attr__helper_methods=(new_value); end
    def __class_attr__layout; end
    def __class_attr__layout=(new_value); end
    def __class_attr__layout_conditions; end
    def __class_attr__layout_conditions=(new_value); end
    def __class_attr__wrapper_options; end
    def __class_attr__wrapper_options=(new_value); end
    def __class_attr_config; end
    def __class_attr_config=(new_value); end
    def __class_attr_helpers_path; end
    def __class_attr_helpers_path=(new_value); end
    def __class_attr_middleware_stack; end
    def __class_attr_middleware_stack=(new_value); end
  end
end

module Fedipub::ClientController::HelperMethods
  include ::Turbo::DriveHelper
  include ::Turbo::FramesHelper
  include ::Turbo::IncludesHelper
  include ::Turbo::StreamsHelper
  include ::ActionView::Helpers::CaptureHelper
  include ::ActionView::Helpers::OutputSafetyHelper
  include ::ActionView::Helpers::TagHelper
  include ::Turbo::Streams::ActionHelper
  include ::ActionText::ContentHelper
  include ::ActionText::TagHelper
  include ::Lexxy::TagHelper
  include ::Importmap::ImportmapTagsHelper
  include ::DeviseI18n::ViewHelpers
  include ::ActionController::Base::HelperMethods
  include ::ApplicationHelper
  include ::DeviseHelper
  include ::LinkHelper
  include ::RssHelper
  include ::ApplicationController::HelperMethods
  include ::Pundit::Helper

  def policy(*, **, &); end
  def pundit_policy_scope(*, **, &); end
  def pundit_user(*, **, &); end
end

# Stores the Fedipub configuration in a _singleton_.
#
# pkg:gem/fedipub#lib/fedipub/configuration.rb:11
module Fedipub::Configuration
  # pkg:gem/fedipub#lib/fedipub/configuration.rb:131
  def actor_types; end

  # pkg:gem/fedipub#lib/fedipub/configuration.rb:57
  def app_layout; end

  # pkg:gem/fedipub#lib/fedipub/configuration.rb:57
  def app_layout=(val); end

  # pkg:gem/fedipub#lib/fedipub/configuration.rb:13
  def app_name; end

  # pkg:gem/fedipub#lib/fedipub/configuration.rb:13
  def app_name=(val); end

  # pkg:gem/fedipub#lib/fedipub/configuration.rb:17
  def app_version; end

  # pkg:gem/fedipub#lib/fedipub/configuration.rb:17
  def app_version=(val); end

  # pkg:gem/fedipub#lib/fedipub/configuration.rb:81
  def base_client_controller; end

  # pkg:gem/fedipub#lib/fedipub/configuration.rb:81
  def base_client_controller=(val); end

  # pkg:gem/fedipub#lib/fedipub/configuration.rb:77
  def client_routes_path; end

  # pkg:gem/fedipub#lib/fedipub/configuration.rb:77
  def client_routes_path=(val); end

  # pkg:gem/fedipub#lib/fedipub/configuration.rb:140
  def data_types; end

  # pkg:gem/fedipub#lib/fedipub/configuration.rb:33
  def enable_discovery; end

  # pkg:gem/fedipub#lib/fedipub/configuration.rb:33
  def enable_discovery=(val); end

  # pkg:gem/fedipub#lib/fedipub/configuration.rb:21
  def force_ssl; end

  # pkg:gem/fedipub#lib/fedipub/configuration.rb:21
  def force_ssl=(val); end

  # pkg:gem/fedipub#lib/fedipub/configuration.rb:127
  def job_queue; end

  # pkg:gem/fedipub#lib/fedipub/configuration.rb:127
  def job_queue=(val); end

  # pkg:gem/fedipub#lib/fedipub/configuration.rb:62
  def logger=(val); end

  # pkg:gem/fedipub#lib/fedipub/configuration.rb:48
  def nodeinfo_metadata=(val); end

  # pkg:gem/fedipub#lib/fedipub/configuration.rb:38
  def open_registrations=(val); end

  # pkg:gem/fedipub#lib/fedipub/configuration.rb:119
  def remote_entities_cache_duration; end

  # pkg:gem/fedipub#lib/fedipub/configuration.rb:119
  def remote_entities_cache_duration=(val); end

  # pkg:gem/fedipub#lib/fedipub/configuration.rb:101
  def remote_follow_url_method; end

  # pkg:gem/fedipub#lib/fedipub/configuration.rb:101
  def remote_follow_url_method=(val); end

  # pkg:gem/fedipub#lib/fedipub/configuration.rb:73
  def server_routes_path; end

  # pkg:gem/fedipub#lib/fedipub/configuration.rb:73
  def server_routes_path=(val); end

  # pkg:gem/fedipub#lib/fedipub/configuration.rb:25
  def site_host; end

  # pkg:gem/fedipub#lib/fedipub/configuration.rb:29
  def site_port; end

  # pkg:gem/fedipub#lib/fedipub/configuration.rb:123
  def verify_signatures; end

  # pkg:gem/fedipub#lib/fedipub/configuration.rb:123
  def verify_signatures=(val); end

  class << self
    # pkg:gem/fedipub#lib/fedipub/configuration.rb:131
    def actor_types; end

    # pkg:gem/fedipub#lib/fedipub/configuration.rb:57
    def app_layout; end

    # pkg:gem/fedipub#lib/fedipub/configuration.rb:57
    def app_layout=(val); end

    # pkg:gem/fedipub#lib/fedipub/configuration.rb:13
    def app_name; end

    # pkg:gem/fedipub#lib/fedipub/configuration.rb:13
    def app_name=(val); end

    # pkg:gem/fedipub#lib/fedipub/configuration.rb:17
    def app_version; end

    # pkg:gem/fedipub#lib/fedipub/configuration.rb:17
    def app_version=(val); end

    # pkg:gem/fedipub#lib/fedipub/configuration.rb:81
    def base_client_controller; end

    # pkg:gem/fedipub#lib/fedipub/configuration.rb:81
    def base_client_controller=(val); end

    # pkg:gem/fedipub#lib/fedipub/configuration.rb:77
    def client_routes_path; end

    # pkg:gem/fedipub#lib/fedipub/configuration.rb:77
    def client_routes_path=(val); end

    # pkg:gem/fedipub#lib/fedipub/configuration.rb:140
    def data_types; end

    # pkg:gem/fedipub#lib/fedipub/configuration.rb:33
    def enable_discovery; end

    # pkg:gem/fedipub#lib/fedipub/configuration.rb:33
    def enable_discovery=(val); end

    # pkg:gem/fedipub#lib/fedipub/configuration.rb:21
    def force_ssl; end

    # pkg:gem/fedipub#lib/fedipub/configuration.rb:21
    def force_ssl=(val); end

    # pkg:gem/fedipub#lib/fedipub/configuration.rb:127
    def job_queue; end

    # pkg:gem/fedipub#lib/fedipub/configuration.rb:127
    def job_queue=(val); end

    # pkg:gem/fedipub#lib/fedipub/configuration.rb:66
    sig { returns(::Logger) }
    def logger; end

    # pkg:gem/fedipub#lib/fedipub/configuration.rb:62
    def logger=(val); end

    # pkg:gem/fedipub#lib/fedipub/configuration.rb:52
    sig { returns(T::Hash[::String, ::Object]) }
    def nodeinfo_metadata; end

    # pkg:gem/fedipub#lib/fedipub/configuration.rb:48
    def nodeinfo_metadata=(val); end

    # pkg:gem/fedipub#lib/fedipub/configuration.rb:42
    sig { returns(T::Boolean) }
    def open_registrations; end

    # pkg:gem/fedipub#lib/fedipub/configuration.rb:38
    def open_registrations=(val); end

    # pkg:gem/fedipub#lib/fedipub/configuration.rb:135
    sig { params(klass: ::Class, config: T::Hash[::Symbol, ::Object]).void }
    def register_actor_class(klass, config = T.unsafe(nil)); end

    # pkg:gem/fedipub#lib/fedipub/configuration.rb:144
    sig { params(klass: ::Class, config: T::Hash[::Symbol, ::Object]).void }
    def register_data_type(klass, config = T.unsafe(nil)); end

    # pkg:gem/fedipub#lib/fedipub/configuration.rb:119
    def remote_entities_cache_duration; end

    # pkg:gem/fedipub#lib/fedipub/configuration.rb:119
    def remote_entities_cache_duration=(val); end

    # pkg:gem/fedipub#lib/fedipub/configuration.rb:101
    def remote_follow_url_method; end

    # pkg:gem/fedipub#lib/fedipub/configuration.rb:101
    def remote_follow_url_method=(val); end

    # pkg:gem/fedipub#lib/fedipub/configuration.rb:73
    def server_routes_path; end

    # pkg:gem/fedipub#lib/fedipub/configuration.rb:73
    def server_routes_path=(val); end

    # pkg:gem/fedipub#lib/fedipub/configuration.rb:25
    def site_host; end

    # pkg:gem/fedipub#lib/fedipub/configuration.rb:105
    sig { params(value: T.nilable(::String)).void }
    def site_host=(value); end

    # pkg:gem/fedipub#lib/fedipub/configuration.rb:29
    def site_port; end

    # pkg:gem/fedipub#lib/fedipub/configuration.rb:111
    sig { params(value: T.nilable(::Integer)).void }
    def site_port=(value); end

    # pkg:gem/fedipub#lib/fedipub/configuration.rb:123
    def verify_signatures; end

    # pkg:gem/fedipub#lib/fedipub/configuration.rb:123
    def verify_signatures=(val); end
  end
end

# pkg:gem/fedipub#lib/fedipub.rb:25
Fedipub::DEFAULT_DATA_FILTER_METHOD = T.let(T.unsafe(nil), Symbol)

module Fedipub::DataEntity
  extend ::ActiveSupport::Concern
  include ::Fedipub::HandlesDeleteRequests
  include ::Fedipub::HandlesSocialActivities
  include ::Fedipub::Likeable
  include ::Fedipub::Announceable

  mixes_in_class_methods ::Fedipub::HandlesDeleteRequests::ClassMethods
  mixes_in_class_methods ::Fedipub::HandlesSocialActivities::ClassMethods
  mixes_in_class_methods ::Fedipub::DataEntity::ClassMethods

  sig { returns(T.nilable(::String)) }
  def federated_url; end

  sig { returns(T::Array[::String]) }
  def federation_reply_recipients; end

  sig { returns(T::Hash[::Symbol, T.untyped]) }
  def fedipub_data_configuration; end

  sig { returns(T::Boolean) }
  def fedipub_sync!; end

  sig { returns(T::Boolean) }
  def fedipub_tombstoned?; end

  sig { returns(T.nilable(::DateTime)) }
  def fedipub_tombstoned_at; end

  sig { returns(T::Boolean) }
  def local_fedipub_entity?; end

  private

  def create_fedipub_activity(action, actor: T.unsafe(nil), to: T.unsafe(nil), cc: T.unsafe(nil)); end

  sig { returns(T::Boolean) }
  def default_should_federate?; end

  sig { void }
  def ensure_fedipub_configuration!; end

  sig { params(action: ::String, actor: T.nilable(::Fedipub::Actor)).returns(T::Boolean) }
  def fedipub_activity_deliverable?(action, actor); end

  sig { returns(T.nilable(::Fedipub::Actor)) }
  def set_fedipub_actor; end
end

module Fedipub::DataEntity::ClassMethods
  def acts_as_fedipub_data(handles:, with: T.unsafe(nil), route_path_segment: T.unsafe(nil), actor_entity_method: T.unsafe(nil), url_param: T.unsafe(nil), filter_method: T.unsafe(nil), should_federate_method: T.unsafe(nil), soft_deleted_method: T.unsafe(nil), soft_delete_date_method: T.unsafe(nil)); end

  sig { params(params: T.untyped).returns(T.untyped) }
  def find_untombstoned_by!(**params); end

  sig { params(activity_hash_or_id: T.any(::String, T::Hash[T.untyped, T.untyped])).returns(T.self_type) }
  def handle_incoming_fediverse_data(activity_hash_or_id); end

  sig { params(activitypub_object: T::Hash[T.untyped, T.untyped]).returns(T.self_type) }
  def new_from_activitypub_object(activitypub_object); end
end

Fedipub::DataEntity::LIFECYCLE_FEDIPUB_ACTIONS = T.let(T.unsafe(nil), Array)
class Fedipub::DataEntity::TombstonedError < ::StandardError; end

# pkg:gem/fedipub#lib/fedipub/data_transformer/note.rb:7
module Fedipub::DataTransformer; end

# pkg:gem/fedipub#lib/fedipub/data_transformer/note.rb:8
module Fedipub::DataTransformer::Note
  class << self
    # Renders a Note. The entity is used to determine actor and generic fields data
    #
    # @param entity [#federail_actor, #federated_url, #created_at, #updated_at] A model instance
    # @param content [String] Note content
    # @param name [String, nil] Optional name/title
    # @param custom [Hash] Optional additional keys (e.g.: attachment, icon, ...). Defaults will override these.
    # @param to [Array<String>, nil] Recipients for the object itself. Defaults to the public collection.
    # @param cc [Array<String>, nil] Copied recipients for the object itself. Defaults to the actor's followers.
    #
    #   Objects must carry their own addressing: some implementations (e.g. Hollo/Fedify)
    #   derive object visibility from the object's to/cc only, and treat an unaddressed
    #   object as a direct message, hiding it from profiles and searches.
    #
    # @return [Hash]
    #
    # @example
    #   Fedipub::DataTransformer::Note.to_federation(comment, content: comment.content, custom: { 'inReplyTo' => comment.parent.federated_url })
    #
    # See:
    #   - https://www.w3.org/TR/activitystreams-vocabulary/#dfn-object
    #   - https://www.w3.org/TR/activitystreams-vocabulary/#dfn-note
    #
    # pkg:gem/fedipub#lib/fedipub/data_transformer/note.rb:30
    def to_federation(entity, content:, name: T.unsafe(nil), custom: T.unsafe(nil), to: T.unsafe(nil), cc: T.unsafe(nil)); end
  end
end

# pkg:gem/fedipub#lib/fedipub/delivery_errors.rb:5
class Fedipub::DeliveryError < ::StandardError
  # pkg:gem/fedipub#lib/fedipub/delivery_errors.rb:8
  def initialize(message, response_code: T.unsafe(nil), inbox_url: T.unsafe(nil)); end

  # pkg:gem/fedipub#lib/fedipub/delivery_errors.rb:6
  def inbox_url; end

  # pkg:gem/fedipub#lib/fedipub/delivery_errors.rb:6
  def response_code; end
end

# pkg:gem/fedipub#lib/fedipub/engine.rb:10
class Fedipub::Engine < ::Rails::Engine; end

class Fedipub::FeaturedItem < ::Fedipub::ApplicationRecord
  include ::Fedipub::FeaturedItem::GeneratedAttributeMethods
  include ::Fedipub::FeaturedItem::GeneratedAssociationMethods

  def _run_save_callbacks(&block); end
  def autosave_associated_records_for_actor(*args); end

  class << self
    private

    def __class_attr___callbacks; end
    def __class_attr___callbacks=(new_value); end
    def __class_attr__reflections; end
    def __class_attr__reflections=(new_value); end
    def __class_attr__validators; end
    def __class_attr__validators=(new_value); end
    def __class_attr_defined_enums; end
    def __class_attr_defined_enums=(new_value); end
  end
end

module Fedipub::FeaturedItem::GeneratedAssociationMethods
  def actor; end
  def actor=(value); end
  def actor_changed?; end
  def actor_previously_changed?; end
  def build_actor(*args, &block); end
  def create_actor(*args, &block); end
  def create_actor!(*args, &block); end
  def reload_actor; end
  def reset_actor; end
end

module Fedipub::FeaturedItem::GeneratedAttributeMethods; end

class Fedipub::FeaturedTag < ::Fedipub::ApplicationRecord
  include ::Fedipub::FeaturedTag::GeneratedAttributeMethods
  include ::Fedipub::FeaturedTag::GeneratedAssociationMethods

  def _run_save_callbacks(&block); end
  def autosave_associated_records_for_actor(*args); end

  class << self
    private

    def __class_attr___callbacks; end
    def __class_attr___callbacks=(new_value); end
    def __class_attr__reflections; end
    def __class_attr__reflections=(new_value); end
    def __class_attr__validators; end
    def __class_attr__validators=(new_value); end
    def __class_attr_defined_enums; end
    def __class_attr_defined_enums=(new_value); end
  end
end

module Fedipub::FeaturedTag::GeneratedAssociationMethods
  def actor; end
  def actor=(value); end
  def actor_changed?; end
  def actor_previously_changed?; end
  def build_actor(*args, &block); end
  def create_actor(*args, &block); end
  def create_actor!(*args, &block); end
  def reload_actor; end
  def reset_actor; end
end

module Fedipub::FeaturedTag::GeneratedAttributeMethods; end

class Fedipub::FedipubPolicy
  def initialize(user, record); end

  def create?; end
  def destroy?; end
  def edit?; end
  def index?; end
  def new?; end
  def record; end
  def show?; end
  def update?; end
  def user; end

  private

  def owner?; end
  def user_with_actor?; end
end

class Fedipub::FedipubPolicy::Scope
  def initialize(user, scope); end

  def resolve; end
  def scope; end
  def user; end
end

class Fedipub::FetchNodeinfoJob < ::Fedipub::ApplicationJob
  def perform(domain); end
end

class Fedipub::Following < ::Fedipub::ApplicationRecord
  include ::Fedipub::Following::GeneratedAttributeMethods
  include ::Fedipub::Following::GeneratedAssociationMethods
  include ::Fedipub::HasUuid
  extend ::Fedipub::HasUuid::ClassMethods

  def _on_fedipub_delete_requested_callbacks; end
  def _run_create_callbacks(&block); end
  def _run_destroy_callbacks(&block); end
  def _run_on_fedipub_delete_requested_callbacks(&block); end
  def _run_on_fedipub_delete_requested_callbacks!(&block); end
  def _run_save_callbacks(&block); end
  def _run_update_callbacks(&block); end

  sig { params(follow_activity: ::Fedipub::Activity).returns(::Fedipub::Activity) }
  def accept!(follow_activity:); end

  def autosave_associated_records_for_activities(*args); end
  def autosave_associated_records_for_actor(*args); end
  def autosave_associated_records_for_target_actor(*args); end

  sig { returns(::String) }
  def federated_url; end

  sig { returns(T.nilable(::Fedipub::Activity)) }
  def follow_activity; end

  def validate_associated_records_for_activities(*args); end

  private

  sig { void }
  def after_follow; end

  sig { void }
  def after_follow_accepted; end

  sig { returns(::Fedipub::Activity) }
  def create_activity; end

  sig { returns(::Fedipub::Activity) }
  def destroy_activity; end

  sig { returns(T::Boolean) }
  def locally_instigated?; end

  class << self
    def _on_fedipub_delete_requested_callbacks; end
    def _on_fedipub_delete_requested_callbacks=(value); end
    def accepted(*args, **); end

    sig { params(account: ::String, actor: ::Fedipub::Actor).returns(::Fedipub::Following) }
    def new_from_account(account, actor:); end

    def not_accepted(*args, **); end
    def not_pending(*args, **); end
    def pending(*args, **); end
    def statuses; end
    def with_actor(*args, **); end

    private

    def __class_attr___callbacks; end
    def __class_attr___callbacks=(new_value); end
    def __class_attr__reflections; end
    def __class_attr__reflections=(new_value); end
    def __class_attr__validators; end
    def __class_attr__validators=(new_value); end
    def __class_attr_defined_enums; end
    def __class_attr_defined_enums=(new_value); end
  end
end

module Fedipub::Following::GeneratedAssociationMethods
  def activities; end
  def activities=(value); end
  def activity_ids; end
  def activity_ids=(ids); end
  def actor; end
  def actor=(value); end
  def actor_changed?; end
  def actor_previously_changed?; end
  def build_actor(*args, &block); end
  def build_target_actor(*args, &block); end
  def create_actor(*args, &block); end
  def create_actor!(*args, &block); end
  def create_target_actor(*args, &block); end
  def create_target_actor!(*args, &block); end
  def reload_actor; end
  def reload_target_actor; end
  def reset_actor; end
  def reset_target_actor; end
  def target_actor; end
  def target_actor=(value); end
  def target_actor_changed?; end
  def target_actor_previously_changed?; end
end

module Fedipub::Following::GeneratedAttributeMethods; end

module Fedipub::HandlesDeleteRequests
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::Fedipub::HandlesDeleteRequests::ClassMethods
end

module Fedipub::HandlesDeleteRequests::ClassMethods
  def on_fedipub_delete_requested(*); end
  def on_fedipub_undelete_requested(*); end
end

module Fedipub::HandlesSocialActivities
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::Fedipub::HandlesSocialActivities::ClassMethods
end

module Fedipub::HandlesSocialActivities::ClassMethods
  def on_fedipub_announce_received(method_name = T.unsafe(nil), **, &); end
  def on_fedipub_like_received(method_name = T.unsafe(nil), **, &); end
  def on_fedipub_undo_announce_received(method_name = T.unsafe(nil), **, &); end
  def on_fedipub_undo_like_received(method_name = T.unsafe(nil), **, &); end

  private

  sig do
    params(
      callback_name: ::Symbol,
      method_name: T.nilable(::Symbol),
      options: T.untyped,
      block: T.nilable(T.proc.params(arg0: T.untyped).void)
    ).returns(T.untyped)
  end
  def register_social_callback(callback_name, method_name = T.unsafe(nil), **options, &block); end
end

module Fedipub::HasUuid
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::Fedipub::HasUuid::ClassMethods

  sig { returns(::String) }
  def to_param; end

  sig { returns(::String) }
  def uuid; end

  private

  sig { void }
  def generate_uuid; end
end

module Fedipub::HasUuid::ClassMethods
  sig { params(param: ::String).returns(T.untyped) }
  def find_param(param); end
end

class Fedipub::Host < ::Fedipub::ApplicationRecord
  include ::Fedipub::Host::GeneratedAttributeMethods
  include ::Fedipub::Host::GeneratedAssociationMethods

  def _run_create_callbacks(&block); end
  def _run_save_callbacks(&block); end
  def _run_update_callbacks(&block); end
  def autosave_associated_records_for_actors(*args); end

  sig { returns(T::Boolean) }
  def same_app?; end

  sig { returns(T::Boolean) }
  def same_app_and_version?; end

  sig { returns(T::Boolean) }
  def sync!; end

  def validate_associated_records_for_actors(*args); end

  class << self
    sig do
      params(
        domain: ::String,
        min_update_interval: T.any(::ActiveSupport::Duration, ::Integer)
      ).returns(T.nilable(::Fedipub::Host))
    end
    def create_or_update(domain, min_update_interval: T.unsafe(nil)); end

    def same_app(*args, **); end
    def same_app_and_version(*args, **); end

    private

    def __class_attr___callbacks; end
    def __class_attr___callbacks=(new_value); end
    def __class_attr__reflections; end
    def __class_attr__reflections=(new_value); end
    def __class_attr__validators; end
    def __class_attr__validators=(new_value); end
    def __class_attr_defined_enums; end
    def __class_attr_defined_enums=(new_value); end

    sig { params(domain: ::String, error: ::StandardError).returns(::NilClass) }
    def log_sync_failure(domain, error); end

    sig { params(domain: ::String, new_record: T::Boolean).returns(::Fedipub::Host) }
    def recover_from_domain_race(domain, new_record); end
  end
end

module Fedipub::Host::GeneratedAssociationMethods
  def actor_ids; end
  def actor_ids=(ids); end
  def actors; end
  def actors=(value); end
end

module Fedipub::Host::GeneratedAttributeMethods; end
Fedipub::Host::SYNC_FAILURES = T.let(T.unsafe(nil), Array)

# pkg:gem/fedipub#lib/fedipub/delivery_errors.rb:16
class Fedipub::InvalidDeliveryPayloadError < ::Fedipub::PermanentDeliveryError; end

module Fedipub::Likeable
  extend ::ActiveSupport::Concern

  def dislike!(actor:); end
  def like!(actor:); end
end

# pkg:gem/fedipub#lib/fedipub/maintenance/actors_updater.rb:5
module Fedipub::Maintenance; end

# pkg:gem/fedipub#lib/fedipub/maintenance/actors_updater.rb:6
class Fedipub::Maintenance::ActorsUpdater
  class << self
    # Fetches all distant actors again and update their local copy
    #
    # A block can be passed with two arguments: the actor being updated and the update status
    #
    # @param actors [Integer, Fedipub::Actor, Array<Fedipub::Actor>, nil] Actor ID, Actor or list of actors to update.
    #   If nothing is passed, all distant actors are processed
    # @example
    #   Update all distant actors
    #     Fedipub::Maintenance::ActorUpdater.run
    #   With an actor id:
    #     Fedipub::Maintenance::ActorUpdater.run 1
    #   With a federated URL:
    #     Fedipub::Maintenance::ActorUpdater.run 'https://example.com/actor'
    #   With a federated URL:
    #     Fedipub::Maintenance::ActorUpdater.run ['https://example.com/actors/1', 'https://example.com/actors/1']
    #   With actors:
    #     Fedipub::Maintenance::ActorUpdater.run Fedipub::Actor.last(10)
    #   Update all distant actors and puts status for each actor
    #     Fedipub::Maintenance::ActorUpdater.run {|actor, status| puts "#{actor.federated_url}: #{status}"}
    #
    # pkg:gem/fedipub#lib/fedipub/maintenance/actors_updater.rb:27
    def run(actors = T.unsafe(nil), &block); end

    private

    # Make a list of actors to update from the passed attribute
    #
    # pkg:gem/fedipub#lib/fedipub/maintenance/actors_updater.rb:38
    def actors_list(param); end

    # pkg:gem/fedipub#lib/fedipub/maintenance/actors_updater.rb:57
    sig { params(actor: ::Fedipub::Actor).returns(::Symbol) }
    def update(actor); end
  end
end

# pkg:gem/fedipub#lib/fedipub/maintenance/hosts_updater.rb:6
class Fedipub::Maintenance::HostsUpdater
  class << self
    # Update information for all known hosts, and complete if some are missing
    #
    # pkg:gem/fedipub#lib/fedipub/maintenance/hosts_updater.rb:9
    def run(cache_interval: T.unsafe(nil)); end
  end
end

class Fedipub::NotifyInboxJob < ::Fedipub::ApplicationJob
  def perform(activity, inbox_url = T.unsafe(nil)); end

  class << self
    private

    def __class_attr_rescue_handlers; end
    def __class_attr_rescue_handlers=(new_value); end
  end
end

# pkg:gem/fedipub#lib/fedipub/delivery_errors.rb:15
class Fedipub::PermanentDeliveryError < ::Fedipub::DeliveryError; end

module Fedipub::SerializerSupport
  private

  def json_ld_context(additional: T.unsafe(nil)); end
  def route_helpers; end

  class << self
    def json_ld_context(additional: T.unsafe(nil)); end
    def route_helpers; end
  end
end

module Fedipub::Server; end

class Fedipub::Server::ActivitiesController < ::Fedipub::ServerController
  include ::Fedipub::Server::RenderCollections
  include ::Fedipub::Server::VerifySignature
  include ::Fedipub::Server::InboxPayload

  def create; end
  def outbox; end
  def show; end

  private

  def _layout(lookup_context, formats, keys); end
  def _layout_from_proc; end
  def activity_params; end
  def log_social_activity_payload(payload); end
  def set_activity; end

  class << self
    private

    def __class_attr___callbacks; end
    def __class_attr___callbacks=(new_value); end
    def __class_attr__wrapper_options; end
    def __class_attr__wrapper_options=(new_value); end
    def __class_attr_config; end
    def __class_attr_config=(new_value); end
    def __class_attr_helpers_path; end
    def __class_attr_helpers_path=(new_value); end
    def __class_attr_middleware_stack; end
    def __class_attr_middleware_stack=(new_value); end
  end
end

class Fedipub::Server::ActivityPolicy < ::Fedipub::FedipubPolicy
  def outbox?; end
end

class Fedipub::Server::ActivityResource < ::Fedipub::Server::BaseResource
  def include_addressing?; end
  def include_context?; end
  def serialize_object(entity, action: T.unsafe(nil)); end
end

Fedipub::Server::ActivityResource::URI_ONLY_OBJECT_ACTIONS = T.let(T.unsafe(nil), Array)

class Fedipub::Server::ActorPolicy < ::Fedipub::FedipubPolicy
  def featured?; end
  def featured_tags?; end
  def followers?; end
  def following?; end
  def liked?; end
  def show?; end
end

class Fedipub::Server::ActorPolicy::Scope < ::Fedipub::FedipubPolicy::Scope
  def resolve; end
end

class Fedipub::Server::ActorResource < ::Fedipub::Server::BaseResource
  def actor_data(actor); end
  def serializable_hash; end
end

Fedipub::Server::ActorResource::DISCOVERY_IMPLEMENTS = T.let(T.unsafe(nil), Array)
Fedipub::Server::ActorResource::FEP_844E_CONTEXT = T.let(T.unsafe(nil), String)
Fedipub::Server::ActorResource::IMPLEMENTS = T.let(T.unsafe(nil), Array)
class Fedipub::Server::ActorTombstoneResource < ::Fedipub::Server::BaseResource; end

class Fedipub::Server::ActorsController < ::Fedipub::ServerController
  include ::Fedipub::Server::RenderCollections

  def featured; end
  def featured_tags; end
  def followers; end
  def following; end
  def liked; end
  def show; end

  private

  def _layout(lookup_context, formats, keys); end
  def _layout_from_proc; end
  def application_actor_show?; end
  def set_actor; end

  class << self
    private

    def __class_attr___callbacks; end
    def __class_attr___callbacks=(new_value); end
    def __class_attr__wrapper_options; end
    def __class_attr__wrapper_options=(new_value); end
    def __class_attr_config; end
    def __class_attr_config=(new_value); end
    def __class_attr_helpers_path; end
    def __class_attr_helpers_path=(new_value); end
    def __class_attr_middleware_stack; end
    def __class_attr_middleware_stack=(new_value); end
  end
end

class Fedipub::Server::BaseResource
  include ::Alba::Resource
  include ::Alba::Resource::InstanceMethods
  extend ::Alba::Resource::ClassMethods

  def encode(hash); end
  def select(_key, value); end

  private

  def _setup; end
  def normalize_activitypub_hash(data); end
end

class Fedipub::Server::FollowingPolicy < ::Fedipub::FedipubPolicy; end
class Fedipub::Server::FollowingResource < ::Fedipub::Server::BaseResource; end

class Fedipub::Server::FollowingsController < ::Fedipub::ServerController
  def show; end

  private

  def _layout(lookup_context, formats, keys); end
  def _layout_from_proc; end
  def set_following; end

  class << self
    private

    def __class_attr___callbacks; end
    def __class_attr___callbacks=(new_value); end
    def __class_attr__wrapper_options; end
    def __class_attr__wrapper_options=(new_value); end
    def __class_attr_config; end
    def __class_attr_config=(new_value); end
    def __class_attr_helpers_path; end
    def __class_attr_helpers_path=(new_value); end
    def __class_attr_middleware_stack; end
    def __class_attr_middleware_stack=(new_value); end
  end
end

module Fedipub::Server::InboxPayload
  extend ::ActiveSupport::Concern

  private

  def compact_payload(payload); end
  def payload_from_params; end
  def supported_inbox_content_type?; end
  def validate_payload(hash); end
end

class Fedipub::Server::NodeinfoController < ::Fedipub::ServerController
  def index; end
  def show; end

  private

  def _layout(lookup_context, formats, keys); end
  def _layout_from_proc; end

  class << self
    private

    def __class_attr__wrapper_options; end
    def __class_attr__wrapper_options=(new_value); end
    def __class_attr_config; end
    def __class_attr_config=(new_value); end
    def __class_attr_helpers_path; end
    def __class_attr_helpers_path=(new_value); end
    def __class_attr_middleware_stack; end
    def __class_attr_middleware_stack=(new_value); end
  end
end

class Fedipub::Server::NodeinfoIndexPayload < ::Struct
  def application_actor_href; end
  def application_actor_href=(_); end
  def href; end
  def href=(_); end

  class << self
    def [](*_arg0); end
    def inspect; end
    def keyword_init?; end
    def members; end
    def new(*_arg0); end
  end
end

class Fedipub::Server::NodeinfoIndexResource < ::Fedipub::Server::BaseResource; end

class Fedipub::Server::NodeinfoPayload < ::Struct
  def active_halfyear; end
  def active_halfyear=(_); end
  def active_month; end
  def active_month=(_); end
  def has_user_counts; end
  def has_user_counts=(_); end
  def metadata; end
  def metadata=(_); end
  def open_registrations; end
  def open_registrations=(_); end
  def software_name; end
  def software_name=(_); end
  def software_version; end
  def software_version=(_); end
  def total; end
  def total=(_); end

  class << self
    def [](*_arg0); end
    def inspect; end
    def keyword_init?; end
    def members; end
    def new(*_arg0); end
  end
end

class Fedipub::Server::NodeinfoResource < ::Fedipub::Server::BaseResource; end

class Fedipub::Server::OrderedCollectionPayload
  def initialize(attributes); end

  def context; end
  def first; end
  def id; end
  def last; end
  def next; end
  def orderedItems; end
  def partOf; end
  def prev; end
  def totalItems; end
  def type; end
end

class Fedipub::Server::OrderedCollectionResource < ::Fedipub::Server::BaseResource; end

class Fedipub::Server::PublishablePolicy < ::Fedipub::FedipubPolicy
  def show?; end
end

class Fedipub::Server::PublishablePolicy::Scope < ::Fedipub::FedipubPolicy::Scope
  def resolve; end
end

class Fedipub::Server::PublishableResource < ::Fedipub::Server::BaseResource
  def publishable_data(publishable); end
  def serializable_hash; end
end

class Fedipub::Server::PublishableTombstoneResource < ::Fedipub::Server::BaseResource; end

class Fedipub::Server::PublishedController < ::Fedipub::ServerController
  def show; end

  private

  def _layout(lookup_context, formats, keys); end
  def _layout_from_proc; end
  def publishable_config; end
  def type_scope; end
  def url_param; end

  class << self
    private

    def __class_attr__wrapper_options; end
    def __class_attr__wrapper_options=(new_value); end
    def __class_attr_config; end
    def __class_attr_config=(new_value); end
    def __class_attr_helpers_path; end
    def __class_attr_helpers_path=(new_value); end
    def __class_attr_middleware_stack; end
    def __class_attr_middleware_stack=(new_value); end
  end
end

module Fedipub::Server::RenderCollections
  extend ::ActiveSupport::Concern

  private

  def collection_page_payload(actor:, pagy:, paged:, url_helper:); end
  def collection_summary_payload(actor:, pagy:, url_helper:); end
  def render_collection(actor:, collection:, url_helper:, &items_block); end
  def url_for_collection(url_helper, actor, **params); end
end

class Fedipub::Server::SharedInboxController < ::Fedipub::ServerController
  include ::Fedipub::Server::VerifySignature
  include ::Fedipub::Server::InboxPayload

  def create; end

  private

  def _layout(lookup_context, formats, keys); end
  def _layout_from_proc; end
  def validate_content_type!; end

  class << self
    private

    def __class_attr___callbacks; end
    def __class_attr___callbacks=(new_value); end
    def __class_attr__wrapper_options; end
    def __class_attr__wrapper_options=(new_value); end
    def __class_attr_config; end
    def __class_attr_config=(new_value); end
    def __class_attr_helpers_path; end
    def __class_attr_helpers_path=(new_value); end
    def __class_attr_middleware_stack; end
    def __class_attr_middleware_stack=(new_value); end
  end
end

module Fedipub::Server::VerifySignature
  extend ::ActiveSupport::Concern

  private

  def actor_match?(payload); end
  def body_digest(digest_name); end
  def content_digest_match?(header); end
  def digest_match?(header); end
  def extract_payload_actor; end
  def log_signature_failure(error); end
  def verify_body_digest!; end
  def verify_http_signature!; end
end

Fedipub::Server::VerifySignature::CONTENT_DIGEST_ALGORITHMS = T.let(T.unsafe(nil), Hash)
Fedipub::Server::VerifySignature::DIGEST_CHECKS = T.let(T.unsafe(nil), Hash)

class Fedipub::Server::WebFingerController < ::Fedipub::ServerController
  def find; end
  def host_meta; end

  private

  def _layout(lookup_context, formats, keys); end
  def _layout_from_proc; end
  def username; end

  class << self
    private

    def __class_attr__wrapper_options; end
    def __class_attr__wrapper_options=(new_value); end
    def __class_attr_config; end
    def __class_attr_config=(new_value); end
    def __class_attr_helpers_path; end
    def __class_attr_helpers_path=(new_value); end
    def __class_attr_middleware_stack; end
    def __class_attr_middleware_stack=(new_value); end
  end
end

class Fedipub::Server::WebFingerPayload < ::Struct
  def profile_href; end
  def profile_href=(_); end
  def remote_follow_url; end
  def remote_follow_url=(_); end
  def self_href; end
  def self_href=(_); end
  def service_href; end
  def service_href=(_); end
  def subject; end
  def subject=(_); end

  class << self
    def [](*_arg0); end
    def inspect; end
    def keyword_init?; end
    def members; end
    def new(*_arg0); end
  end
end

class Fedipub::Server::WebFingerResource < ::Fedipub::Server::BaseResource
  private

  def service_link(href); end
end

class Fedipub::ServerController < ::ActionController::Base
  include ::Pagy::Method
  include ::Pundit::Authorization
  include ::Fedipub::ServerHelper

  private

  def _layout(lookup_context, formats, keys); end
  def _layout_from_proc; end
  def error_fallback(exception, fallback_message, status); end
  def error_gone(exception = T.unsafe(nil)); end
  def error_not_found(exception = T.unsafe(nil)); end
  def log_signature_failure(error, **details); end
  def render_serialized(resource_class, object, content_type:, status: T.unsafe(nil), location: T.unsafe(nil), params: T.unsafe(nil)); end
  def verify_request_signature!; end

  class << self
    def _routes; end
    def require_signature?; end

    private

    def __class_attr___callbacks; end
    def __class_attr___callbacks=(new_value); end
    def __class_attr__helper_methods; end
    def __class_attr__helper_methods=(new_value); end
    def __class_attr__wrapper_options; end
    def __class_attr__wrapper_options=(new_value); end
    def __class_attr_config; end
    def __class_attr_config=(new_value); end
    def __class_attr_helpers_path; end
    def __class_attr_helpers_path=(new_value); end
    def __class_attr_middleware_stack; end
    def __class_attr_middleware_stack=(new_value); end
    def __class_attr_rescue_handlers; end
    def __class_attr_rescue_handlers=(new_value); end
  end
end

module Fedipub::ServerController::HelperMethods
  include ::Turbo::DriveHelper
  include ::Turbo::FramesHelper
  include ::Turbo::IncludesHelper
  include ::Turbo::StreamsHelper
  include ::ActionView::Helpers::CaptureHelper
  include ::ActionView::Helpers::OutputSafetyHelper
  include ::ActionView::Helpers::TagHelper
  include ::Turbo::Streams::ActionHelper
  include ::ActionText::ContentHelper
  include ::ActionText::TagHelper
  include ::Lexxy::TagHelper
  include ::Importmap::ImportmapTagsHelper
  include ::DeviseI18n::ViewHelpers
  include ::ActionController::Base::HelperMethods
  include ::Fedipub::ServerHelper
  include ::Pundit::Helper

  def policy(*, **, &); end
  def pundit_policy_scope(*, **, &); end
  def pundit_user(*, **, &); end
end

module Fedipub::ServerHelper
  def remote_follow_url; end
  def set_json_ld_context(json, additional: T.unsafe(nil)); end
end

# pkg:gem/fedipub#lib/fedipub/delivery_errors.rb:18
class Fedipub::TemporaryDeliveryError < ::Fedipub::DeliveryError
  # pkg:gem/fedipub#lib/fedipub/delivery_errors.rb:21
  def initialize(message, response_code: T.unsafe(nil), inbox_url: T.unsafe(nil), retry_after: T.unsafe(nil)); end

  # pkg:gem/fedipub#lib/fedipub/delivery_errors.rb:19
  def retry_after; end
end

# pkg:gem/fedipub#lib/fedipub/utils/object.rb:5
module Fedipub::Utils; end

# pkg:gem/fedipub#lib/fedipub/utils/actor.rb:6
class Fedipub::Utils::Actor
  class << self
    # @param actor [Fedipub::Actor]
    # @return [Fedipub::Actor]
    #
    # pkg:gem/fedipub#lib/fedipub/utils/actor.rb:23
    def tombstone!(actor); end

    # pkg:gem/fedipub#lib/fedipub/utils/actor.rb:34
    sig { params(actor: ::Fedipub::Actor).void }
    def untombstone!(actor); end

    private

    # pkg:gem/fedipub#lib/fedipub/utils/actor.rb:80
    sig { params(actor: ::Fedipub::Actor).void }
    def tombstone_distant_actor(actor); end

    # pkg:gem/fedipub#lib/fedipub/utils/actor.rb:45
    sig { params(actor: ::Fedipub::Actor).void }
    def tombstone_local_actor(actor); end

    # pkg:gem/fedipub#lib/fedipub/utils/actor.rb:85
    sig { params(actor: ::Fedipub::Actor).void }
    def untombstone_distant_actor(actor); end

    # pkg:gem/fedipub#lib/fedipub/utils/actor.rb:61
    sig { params(actor: ::Fedipub::Actor).void }
    def untombstone_local_actor(actor); end
  end
end

# List of the attributes computed for local actors
#
# pkg:gem/fedipub#lib/fedipub/utils/actor.rb:8
Fedipub::Utils::Actor::COMPUTED_ATTRIBUTES = T.let(T.unsafe(nil), Array)

# pkg:gem/fedipub#lib/fedipub/utils/context.rb:6
module Fedipub::Utils::Context
  class << self
    # pkg:gem/fedipub#lib/fedipub/utils/context.rb:9
    sig do
      params(
        additional: T.nilable(T.any(::String, T::Array[::String]))
      ).returns(T.any(::String, T::Array[::String]))
    end
    def generate(additional: T.unsafe(nil)); end
  end
end

# pkg:gem/fedipub#lib/fedipub/utils/host.rb:6
class Fedipub::Utils::Host
  class << self
    # Gets the route on the current instance, or nil
    #
    # @param url [String] URL to check
    #
    # @return [ActionDispatch::Routing::RouteSet, nil] nil when URL do not match a route
    #
    # pkg:gem/fedipub#lib/fedipub/utils/host.rb:35
    def local_route(url); end

    # Checks if the given URL points somewhere on current instance
    #
    # @param url [String] URL to check
    #
    # @return [true, false]
    #
    # pkg:gem/fedipub#lib/fedipub/utils/host.rb:23
    def local_url?(url); end

    # @return [String] Host and port of the current instance
    #
    # pkg:gem/fedipub#lib/fedipub/utils/host.rb:12
    def localhost; end

    private

    # pkg:gem/fedipub#lib/fedipub/utils/host.rb:47
    sig { params(host: T.nilable(::String), port: T.nilable(::Integer)).returns(::String) }
    def host_and_port(host, port); end
  end
end

# Wrapper around HTTP calls which ensures signatures etc are applied.
#
# pkg:gem/fedipub#lib/fedipub/utils/json_request.rb:10
class Fedipub::Utils::JsonRequest
  include ::Singleton::SingletonInstanceMethods
  include ::Singleton
  extend ::Singleton::SingletonClassMethods

  # Makes a GET request signed by +from+ (the application actor by default), following redirects
  #
  # pkg:gem/fedipub#lib/fedipub/utils/json_request.rb:45
  def get(url:, params: T.unsafe(nil), headers: T.unsafe(nil), from: T.unsafe(nil)); end

  # Makes a GET request and returns a +Hash+ from the parsed body
  #
  # @param url [String] Target URL
  # @param params [Hash] Querystring parameters
  # @param headers [Hash] Additional headers
  # @param expected_status [Integer, nil] Expected response status. Will raise a +UnhandledResponseStatus+ when status is different; +nil+ disables the check
  # @param from [Fedipub::Actor, nil] Actor signing the request; defaults to the application actor
  #
  # @return [Hash, Array] The parsed JSON object
  #
  # @raise [UnhandledResponseStatus] when response status is not the expected_status
  #
  # pkg:gem/fedipub#lib/fedipub/utils/json_request.rb:37
  def get_json(url, params: T.unsafe(nil), headers: T.unsafe(nil), expected_status: T.unsafe(nil), from: T.unsafe(nil)); end

  # Makes a POST request, signed by +from+ when given. Redirects are not followed.
  #
  # pkg:gem/fedipub#lib/fedipub/utils/json_request.rb:50
  def post(url:, message:, headers: T.unsafe(nil), from: T.unsafe(nil)); end

  private

  # pkg:gem/fedipub#lib/fedipub/utils/json_request.rb:84
  def build_request(method:, url:, params: T.unsafe(nil), headers: T.unsafe(nil), message: T.unsafe(nil)); end

  # pkg:gem/fedipub#lib/fedipub/utils/json_request.rb:100
  def connection; end

  # Follows redirects for GETs only, signing the request again for each new target: signatures cover the target URI.
  # POSTs are not redirected, so an activity is never replayed to a target we did not choose.
  #
  # pkg:gem/fedipub#lib/fedipub/utils/json_request.rb:58
  def execute_request(method:, url:, params: T.unsafe(nil), headers: T.unsafe(nil), message: T.unsafe(nil), from: T.unsafe(nil)); end

  # Sends with an RFC9421 signature, then retries once with a draft-cavage-12 signature (double-knocking)
  # on a freshly built request if we signed and got a 400 or 401.
  #
  # pkg:gem/fedipub#lib/fedipub/utils/json_request.rb:75
  def send_request(method:, url:, params:, headers:, message:, from:); end

  class << self
    # Makes a GET request signed by +from+ (the application actor by default), following redirects
    #
    # pkg:gem/fedipub#lib/fedipub/utils/json_request.rb:21
    def get(*, **, &); end

    # Makes a GET request and returns a +Hash+ from the parsed body
    #
    # @param url [String] Target URL
    # @param params [Hash] Querystring parameters
    # @param headers [Hash] Additional headers
    # @param expected_status [Integer, nil] Expected response status. Will raise a +UnhandledResponseStatus+ when status is different; +nil+ disables the check
    # @param from [Fedipub::Actor, nil] Actor signing the request; defaults to the application actor
    #
    # @return [Hash, Array] The parsed JSON object
    #
    # @raise [UnhandledResponseStatus] when response status is not the expected_status
    #
    # pkg:gem/fedipub#lib/fedipub/utils/json_request.rb:21
    def get_json(*, **, &); end

    # Makes a POST request, signed by +from+ when given. Redirects are not followed.
    #
    # pkg:gem/fedipub#lib/fedipub/utils/json_request.rb:21
    def post(*, **, &); end

    private

    # pkg:gem/fedipub#lib/fedipub/utils/json_request.rb:11
    def allocate; end

    # pkg:gem/fedipub#lib/fedipub/utils/json_request.rb:11
    def new(*_arg0); end
  end
end

# @rbs @connection: Faraday::Connection
#
# pkg:gem/fedipub#lib/fedipub/utils/json_request.rb:15
Fedipub::Utils::JsonRequest::MAX_REDIRECTS = T.let(T.unsafe(nil), Integer)

# pkg:gem/fedipub#lib/fedipub/utils/json_request.rb:16
Fedipub::Utils::JsonRequest::REDIRECT_STATUSES = T.let(T.unsafe(nil), Array)

# pkg:gem/fedipub#lib/fedipub/utils/json_request.rb:24
class Fedipub::Utils::JsonRequest::UnhandledResponseStatus < ::StandardError; end

# Methods to manipulate incoming objects
#
# pkg:gem/fedipub#lib/fedipub/utils/object.rb:7
class Fedipub::Utils::Object
  class << self
    # Search for a distant object in actors and configured data entities.
    #
    # This is useful to find something when the type is unknown, as an object from a Delete activity.
    #
    # @param federated_url [String] Object identifier
    # @return [Fedipub::Actor, Fedipub::DataEntity, Fedipub::Following, nil]
    #
    # pkg:gem/fedipub#lib/fedipub/utils/object.rb:56
    def find_distant_object_in_all(federated_url); end

    # Finds an already stored entity from an object or its ID, without dereferencing distant objects.
    #
    # Unlike .find_or_initialize, this never fetches remote data nor returns unsaved instances.
    # Hash objects matching a configured data type are looked up in that type first; every lookup
    # also searches actors, followings and all data entities, so an entity stored under another
    # class than the current type handler is still found.
    #
    # @param object_or_id [String, Hash] String identifier or incoming object
    #
    # @return [ActiveRecord::Base, nil] Stored data entity, Fedipub::Actor or Fedipub::Following; nil when not
    #   found locally
    #
    # pkg:gem/fedipub#lib/fedipub/utils/object.rb:37
    def find_existing(object_or_id); end

    # Finds or create an entity from an ActivityPub object or id
    #
    # Note that the data transformer MUST return timestamps from the ActivityPub object if used on the model,
    # as they won't be set automatically.
    #
    # @see .find_or_initialize!
    #
    # @param object_or_id [String, Hash] String identifier or incoming object
    #
    # @return [ApplicationRecord, nil] Entity or nil when invalid/not found
    #
    # pkg:gem/fedipub#lib/fedipub/utils/object.rb:100
    def find_or_create!(object_or_id); end

    # Finds data from an object or its ID.
    #
    # When data exists locally, the entity is returned.
    # For distant data, a new instance is returned unless the target does not exist.
    #
    # @param object_or_id [String, Hash] String identifier or incoming object
    #
    # @return [ApplicationRecord, nil] Entity or nil when invalid/not found
    #
    # pkg:gem/fedipub#lib/fedipub/utils/object.rb:17
    def find_or_initialize(object_or_id); end

    # Finds or initializes an entity from an ActivityPub object or id
    #
    # @see .find_or_initialize
    #
    # @param object_or_id [String, Hash] String identifier or incoming object
    #
    # @return [ApplicationRecord, nil] Entity or nil when invalid/not found
    #
    # pkg:gem/fedipub#lib/fedipub/utils/object.rb:83
    def find_or_initialize!(object_or_id); end

    # Returns the timestamps to use from an ActivityPub object
    #
    # @param hash [Hash] ActivityPub object
    #
    # @return [Hash] Hash with timestamps
    #
    # pkg:gem/fedipub#lib/fedipub/utils/object.rb:121
    def timestamp_attributes(hash); end

    private

    # `attributedTo` may be a String, a linked object with an `id`, or an
    # Array of either — all valid per ActivityStreams. find_by_federation_url
    # expects a String, so normalize to the first URL. Passing the raw Array
    # would raise `NoMethodError: undefined method 'match?' for an Array`.
    #
    # pkg:gem/fedipub#lib/fedipub/utils/object.rb:182
    sig { params(attributed_to: ::Fedipub::Utils::Object).returns(T.nilable(::String)) }
    def attributed_to_url(attributed_to); end

    # pkg:gem/fedipub#lib/fedipub/utils/object.rb:149
    def fallback_local_config(route_path_segment); end

    # pkg:gem/fedipub#lib/fedipub/utils/object.rb:159
    sig do
      params(
        federated_url: T.any(::String, T::Hash[::String, T.untyped])
      ).returns(T.nilable(::ActiveRecord::Base))
    end
    def from_distant_server(federated_url); end

    # pkg:gem/fedipub#lib/fedipub/utils/object.rb:140
    sig { params(route: T::Hash[::Symbol, ::String]).returns(T.nilable(::ActiveRecord::Base)) }
    def from_local_route(route); end

    # pkg:gem/fedipub#lib/fedipub/utils/object.rb:131
    sig { params(url: ::String).returns(T.nilable(T::Hash[::Symbol, ::String])) }
    def local_route(url); end
  end
end

# pkg:gem/fedipub#lib/fedipub/utils/response_codes.rb:6
module Fedipub::Utils::ResponseCodes; end

# pkg:gem/fedipub#lib/fedipub/utils/response_codes.rb:7
Fedipub::Utils::ResponseCodes::UNPROCESSABLE_CONTENT = T.let(T.unsafe(nil), Symbol)

# pkg:gem/fedipub#lib/fedipub/version.rb:5
Fedipub::VERSION = T.let(T.unsafe(nil), String)

# This module includes classes and helpers to interact with the Fediverse.
# rbs_inline: enabled
#
# pkg:gem/fedipub#lib/fediverse/signature.rb:1
module Fediverse; end

# pkg:gem/fedipub#lib/fediverse/collection.rb:5
class Fediverse::Collection < ::Array
  # pkg:gem/fedipub#lib/fediverse/collection.rb:24
  sig { params(url: ::String, max_pages: ::Integer).returns(T.self_type) }
  def fetch(url, max_pages: T.unsafe(nil)); end

  # pkg:gem/fedipub#lib/fediverse/collection.rb:13
  sig { returns(T.nilable(::String)) }
  def id; end

  # pkg:gem/fedipub#lib/fediverse/collection.rb:10
  sig { returns(T.nilable(::Integer)) }
  def total_items; end

  # pkg:gem/fedipub#lib/fediverse/collection.rb:16
  sig { returns(T.nilable(::String)) }
  def type; end

  class << self
    # pkg:gem/fedipub#lib/fediverse/collection.rb:19
    sig { params(url: ::String, max_pages: ::Integer).returns(::Fediverse::Collection) }
    def fetch(url, max_pages: T.unsafe(nil)); end
  end
end

# pkg:gem/fedipub#lib/fediverse/collection.rb:7
Fediverse::Collection::DEFAULT_MAX_PAGES = T.let(T.unsafe(nil), Integer)

# pkg:gem/fedipub#lib/fediverse/collection.rb:6
Fediverse::Collection::PUBLIC = T.let(T.unsafe(nil), String)

# pkg:gem/fedipub#lib/fediverse/collection.rb:47
module Fediverse::Errors; end

# pkg:gem/fedipub#lib/fediverse/collection.rb:48
class Fediverse::Errors::NotACollection < ::StandardError; end

# pkg:gem/fedipub#lib/fediverse/inbox/like_handler.rb:7
class Fediverse::Inbox
  class << self
    # Dispatches an incoming ActivityPub activity to the appropriate handler.
    #
    # Performs de-duplication (AP Section 5.2), origin verification for Update
    # activities (AP Section 7.3), and records processed activity IDs for
    # future de-duplication.
    #
    # @param payload [Hash] Raw activity JSON from the inbox POST
    # @return [true] when the activity was successfully handled
    # @return [:duplicate] when the activity has already been processed
    # @return [false] when no handler matched or verification failed
    #
    # pkg:gem/fedipub#lib/fediverse/inbox.rb:40
    def dispatch_request(payload); end

    # Checks whether an incoming activity should be forwarded to local followers.
    # AP Section 7.1.2: forward when all conditions are met:
    # 1. Activity has not been seen before (handled by dispatch_request de-duplication)
    # 2. to/cc/audience addresses a collection owned by this server
    # 3. inReplyTo/object/target/tag references an object owned by this server
    #
    # @param payload [Hash] The activity payload that was just dispatched
    #
    # pkg:gem/fedipub#lib/fediverse/inbox.rb:86
    def maybe_forward(payload); end

    # Registers a handler for incoming data
    #
    # Unless a specific type is not implemented in Fedipub, you should leave the 'Delete' activity to Fedipub:
    # it will dispatch a `on_fedipub_delete_requested` event on the right objects.
    #
    # @param activity_type [String] Target activity type ('Create', 'Follow', 'Like', ...)
    #   See https://www.w3.org/TR/activitystreams-vocabulary/#activity-types for a list of common ones
    # @param object_type [String] Type of the related object ('Article', 'Note', ...)
    #   See https://www.w3.org/TR/activitystreams-vocabulary/#object-types for a list of common object types
    # @param klass [String] Class handling the incoming object
    # @param method [Symbol] Method in the class that will handle the object
    #
    # pkg:gem/fedipub#lib/fediverse/inbox.rb:24
    def register_handler(activity_type, object_type, klass, method); end

    private

    # Extracts local collection URLs from to/cc/audience addressing fields.
    #
    # pkg:gem/fedipub#lib/fediverse/inbox.rb:179
    sig { params(payload: T::Hash[::String, T.untyped]).returns(T::Array[::String]) }
    def addressed_local_collections(payload); end

    # Resolves the entity (polymorphic object) for a processed activity record.
    # Only already stored entities are used: the record is a processing log and must not
    # fetch or persist distant objects (e.g. a boosted distant Note). Falls back to actor otherwise.
    #
    # pkg:gem/fedipub#lib/fediverse/inbox.rb:208
    sig do
      params(
        payload: T::Hash[::String, T.untyped],
        actor: ::Fedipub::Actor
      ).returns(T.nilable(::ActiveRecord::Base))
    end
    def entity_for_processed_activity(payload, actor); end

    # Returns merged handlers matching the given activity and object types,
    # including wildcard ('*') registrations.
    #
    # pkg:gem/fedipub#lib/fediverse/inbox.rb:137
    def get_handlers(activity_type, object_type); end

    # Checks if a URL resolves to a local followers collection via route recognition.
    # AP Section 7.1.2: forwarding targets followers collections only, not following.
    #
    # pkg:gem/fedipub#lib/fediverse/inbox.rb:186
    sig { params(url: ::String).returns(T::Boolean) }
    def local_collection_url?(url); end

    # Checks if a URL resolves to any local Fedipub resource via route recognition.
    #
    # pkg:gem/fedipub#lib/fediverse/inbox.rb:195
    sig { params(url: ::String).returns(T::Boolean) }
    def local_object_reference?(url); end

    # Best-effort recording of processed activity for de-duplication.
    # Uses actor as fallback entity when the object is not already stored locally.
    # Failures here must not propagate since the activity was already handled successfully.
    #
    # pkg:gem/fedipub#lib/fediverse/inbox.rb:101
    sig { params(payload: T::Hash[::String, T.untyped], dispatched_at: ::ActiveSupport::TimeWithZone).void }
    def record_processed_activity(payload, dispatched_at); end

    # Returns true if to/cc/audience addresses a collection owned by this server.
    #
    # pkg:gem/fedipub#lib/fediverse/inbox.rb:158
    sig { params(payload: T::Hash[::String, T.untyped]).returns(T::Boolean) }
    def references_local_collection?(payload); end

    # Returns true if inReplyTo, object, target, or tag references an object owned by this server.
    #
    # pkg:gem/fedipub#lib/fediverse/inbox.rb:164
    sig { params(payload: T::Hash[::String, T.untyped]).returns(T::Boolean) }
    def references_local_object?(payload); end

    # Compares host and port of two URLs for same-origin verification (AP Section 7.3).
    #
    # pkg:gem/fedipub#lib/fediverse/inbox.rb:146
    sig { params(actor_url: T.nilable(::String), object_url: T.nilable(::String)).returns(T::Boolean) }
    def same_origin?(actor_url, object_url); end

    # pkg:gem/fedipub#lib/fediverse/inbox.rb:222
    sig { params(activity: ::Fedipub::Activity, payload: T::Hash[::String, T.untyped]).void }
    def update_processed_activity!(activity, payload); end
  end
end

# pkg:gem/fedipub#lib/fediverse/inbox/announce_handler.rb:8
module Fediverse::Inbox::AnnounceHandler
  class << self
    # pkg:gem/fedipub#lib/fediverse/inbox/announce_handler.rb:10
    def handle_announce(activity); end

    # pkg:gem/fedipub#lib/fediverse/inbox/announce_handler.rb:17
    def handle_undo_announce(activity); end

    private

    # pkg:gem/fedipub#lib/fediverse/inbox/announce_handler.rb:29
    def dispatch_callback(entity, callback_name, actor); end

    # pkg:gem/fedipub#lib/fediverse/inbox/announce_handler.rb:37
    def resolve_target_entity(object); end
  end
end

# pkg:gem/fedipub#lib/fediverse/inbox/block_handler.rb:6
module Fediverse::Inbox::BlockHandler
  class << self
    # pkg:gem/fedipub#lib/fediverse/inbox/block_handler.rb:9
    def handle_block(activity); end

    # pkg:gem/fedipub#lib/fediverse/inbox/block_handler.rb:23
    def handle_undo_block(activity); end
  end
end

# pkg:gem/fedipub#lib/fediverse/inbox/delete_handler.rb:8
module Fediverse::Inbox::DeleteHandler
  class << self
    # Early-dispatch path invoked from Inbox.dispatch_request before dereferencing.
    # Handles the Delete case where the target object may already be gone remotely.
    #
    # pkg:gem/fedipub#lib/fediverse/inbox/delete_handler.rb:13
    sig { params(payload: T::Hash[::String, T.untyped]).returns(T.nilable(::Object)) }
    def dispatch_delete_request(payload); end

    # Triggers on_fedipub_delete_requested callback on the matching local object.
    #
    # pkg:gem/fedipub#lib/fediverse/inbox/delete_handler.rb:23
    sig { params(activity: T::Hash[::String, T.untyped]).void }
    def handle_delete_request(activity); end

    # Triggers on_fedipub_undelete_requested callback when an Undo+Delete is received.
    #
    # pkg:gem/fedipub#lib/fediverse/inbox/delete_handler.rb:32
    sig { params(activity: T::Hash[::String, T.untyped]).void }
    def handle_undelete_request(activity); end
  end
end

# pkg:gem/fedipub#lib/fediverse/inbox/follow_handler.rb:8
module Fediverse::Inbox::FollowHandler
  class << self
    # Marks a pending Following as accepted when the target actor confirms.
    #
    # pkg:gem/fedipub#lib/fediverse/inbox/follow_handler.rb:38
    sig { params(activity: T::Hash[::String, T.untyped]).returns(T.nilable(::Fedipub::Activity)) }
    def handle_accept_follow_request(activity); end

    # Creates a Following record from an incoming Follow activity.
    #
    # pkg:gem/fedipub#lib/fediverse/inbox/follow_handler.rb:13
    sig { params(activity: T::Hash[::String, T.untyped]).returns(::Fedipub::Following) }
    def handle_create_follow_request(activity); end

    # Destroys a pending Following when the target actor rejects the request.
    # AP Section 7.7: MUST NOT add to Following collection on Reject.
    #
    # pkg:gem/fedipub#lib/fediverse/inbox/follow_handler.rb:87
    sig { params(activity: T::Hash[::String, T.untyped]).returns(T.nilable(::Fedipub::Following)) }
    def handle_reject_follow_request(activity); end

    # Destroys a Following record when the follower undoes their Follow.
    #
    # pkg:gem/fedipub#lib/fediverse/inbox/follow_handler.rb:72
    sig { params(activity: T::Hash[::String, T.untyped]).returns(T.nilable(::Fedipub::Following)) }
    def handle_undo_follow_request(activity); end

    private

    # pkg:gem/fedipub#lib/fediverse/inbox/follow_handler.rb:139
    sig do
      params(
        target_actor: ::Fedipub::Actor,
        following: ::Fedipub::Following,
        follow_activity: T.nilable(::Fedipub::Activity)
      ).void
    end
    def dispatch_followed_callback(target_actor, following, follow_activity); end

    # pkg:gem/fedipub#lib/fediverse/inbox/follow_handler.rb:124
    sig do
      params(
        actor: ::Fedipub::Actor,
        target_actor: ::Fedipub::Actor,
        activity: T::Hash[::String, T.untyped]
      ).returns(T.nilable(::Fedipub::Activity))
    end
    def inbound_follow_activity(actor:, target_actor:, activity:); end

    # Re-sends an Accept Activity when a Follow is received for an already-accepted Following
    # under a new activity id. De-duplication in dispatch_request ensures this path is only
    # reached for genuinely new inbound Follow activities.
    #
    # pkg:gem/fedipub#lib/fediverse/inbox/follow_handler.rb:108
    sig { params(following: ::Fedipub::Following, follow_activity: T.nilable(::Fedipub::Activity)).void }
    def resend_accept_for_duplicate_follow(following, follow_activity); end
  end
end

# pkg:gem/fedipub#lib/fediverse/inbox/like_handler.rb:8
module Fediverse::Inbox::LikeHandler
  class << self
    # pkg:gem/fedipub#lib/fediverse/inbox/like_handler.rb:10
    def handle_like(activity); end

    # pkg:gem/fedipub#lib/fediverse/inbox/like_handler.rb:17
    def handle_undo_like(activity); end

    private

    # pkg:gem/fedipub#lib/fediverse/inbox/like_handler.rb:29
    def dispatch_callback(entity, callback_name, actor); end

    # pkg:gem/fedipub#lib/fediverse/inbox/like_handler.rb:37
    def resolve_target_entity(object); end
  end
end

# pkg:gem/fedipub#lib/fediverse/node_info.rb:5
class Fediverse::NodeInfo
  class << self
    # pkg:gem/fedipub#lib/fediverse/node_info.rb:15
    sig { params(domain: ::String).returns(T::Hash[::Symbol, ::Object]) }
    def fetch(domain); end

    private

    # pkg:gem/fedipub#lib/fediverse/node_info.rb:34
    sig { params(domain: ::String).returns(::String) }
    def base_url(domain); end

    # pkg:gem/fedipub#lib/fediverse/node_info.rb:40
    sig { params(domain: ::String).returns(::String) }
    def nodeinfo_url(domain); end
  end
end

# pkg:gem/fedipub#lib/fediverse/node_info.rb:8
Fediverse::NodeInfo::NODEINFO_SCHEMA_RELS = T.let(T.unsafe(nil), Array)

# pkg:gem/fedipub#lib/fediverse/node_info.rb:7
class Fediverse::NodeInfo::NoActivityPubError < ::StandardError; end

# pkg:gem/fedipub#lib/fediverse/node_info.rb:6
class Fediverse::NodeInfo::NotFoundError < ::StandardError; end

# pkg:gem/fedipub#lib/fediverse/notifier.rb:7
class Fediverse::Notifier
  class << self
    # Delivers an activity to a single inbox. Called by NotifyInboxJob.
    #
    # @param activity [Fedipub::Activity]
    # @param inbox_url [String]
    #
    # pkg:gem/fedipub#lib/fediverse/notifier.rb:35
    def deliver_to_inbox(activity, inbox_url); end

    # Enqueues a separate delivery job for each recipient inbox.
    #
    # @param activity [Fedipub::Activity]
    #
    # pkg:gem/fedipub#lib/fediverse/notifier.rb:21
    def enqueue_deliveries(activity); end

    # pkg:gem/fedipub#lib/fediverse/notifier.rb:64
    sig do
      params(
        payload: T::Hash[::String, T.untyped],
        collection_urls: T::Array[::String],
        exclude_actor: T.nilable(::String)
      ).void
    end
    def forward_activity(payload, collection_urls, exclude_actor: T.unsafe(nil)); end

    # Posts an activity to its recipients (legacy synchronous delivery).
    #
    # @param activity [Fedipub::Activity]
    #
    # pkg:gem/fedipub#lib/fediverse/notifier.rb:46
    def post_to_inboxes(activity); end

    private

    # pkg:gem/fedipub#lib/fediverse/notifier.rb:146
    sig { params(actor_url: T.nilable(::String)).returns(T.nilable(::String)) }
    def actor_inbox_for(actor_url); end

    # pkg:gem/fedipub#lib/fediverse/notifier.rb:261
    sig { params(url: ::String).returns(T.nilable(T::Array[::Fedipub::Actor])) }
    def actors_for_local_collection(url); end

    # pkg:gem/fedipub#lib/fediverse/notifier.rb:123
    sig { params(url: ::String, max_depth: ::Integer).returns(T::Array[::Fedipub::Actor]) }
    def collection_to_actors(url, max_depth: T.unsafe(nil)); end

    # pkg:gem/fedipub#lib/fediverse/notifier.rb:209
    sig do
      params(
        inbox_url: ::String,
        status: ::Integer,
        body: T.nilable(::String),
        retry_after: T.nilable(::String),
        permanent: T::Boolean
      ).returns(::String)
    end
    def delivery_error_message(inbox_url:, status:, body:, retry_after:, permanent:); end

    # pkg:gem/fedipub#lib/fediverse/notifier.rb:155
    sig { params(collection_urls: T::Array[::String]).returns(T.nilable(::Fedipub::Actor)) }
    def forwarding_sender_for(collection_urls); end

    # Determines the list of inboxes that the activity should be delivered to
    #
    # @return [Array<String>] inbox URLs (preferring shared inboxes), excluding the sender's own and blocking actors' inboxes
    #
    # pkg:gem/fedipub#lib/fediverse/notifier.rb:88
    def inboxes_for(activity); end

    # pkg:gem/fedipub#lib/fediverse/notifier.rb:239
    sig { params(activity: ::Fedipub::Activity, json: T::Hash[::Symbol, T.untyped]).returns(::String) }
    def invalid_payload_message(activity, json); end

    # pkg:gem/fedipub#lib/fediverse/notifier.rb:167
    sig { params(activity: ::Fedipub::Activity).returns(::String) }
    def payload(activity); end

    # pkg:gem/fedipub#lib/fediverse/notifier.rb:204
    sig { params(status: ::Integer).returns(T::Boolean) }
    def permanent_delivery_status?(status); end

    # Extension point: host apps may override this to filter deliveries (e.g. moderation).
    # Must return a Faraday::Response or raise a Fedipub::*DeliveryError.
    #
    # pkg:gem/fedipub#lib/fediverse/notifier.rb:177
    sig do
      params(
        inbox_url: ::String,
        message: ::String,
        from: T.nilable(::Fedipub::Actor)
      ).returns(::Faraday::Response)
    end
    def post_to_inbox(inbox_url:, message:, from: T.unsafe(nil)); end

    # pkg:gem/fedipub#lib/fediverse/notifier.rb:234
    sig { params(json: T::Hash[::Symbol, T.untyped]).returns(T::Boolean) }
    def update_object_id_missing?(json); end

    # pkg:gem/fedipub#lib/fediverse/notifier.rb:256
    sig { params(activity: ::Fedipub::Activity, message: ::String).void }
    def validate_message!(activity, message); end

    # pkg:gem/fedipub#lib/fediverse/notifier.rb:222
    sig { params(activity: ::Fedipub::Activity, json: T::Hash[::Symbol, T.untyped]).void }
    def validate_payload!(activity, json); end
  end
end

# pkg:gem/fedipub#lib/fediverse/notifier.rb:9
Fediverse::Notifier::ACTIONS_REQUIRING_OBJECT = T.let(T.unsafe(nil), Array)

# pkg:gem/fedipub#lib/fediverse/notifier.rb:8
Fediverse::Notifier::MAX_COLLECTION_DEPTH = T.let(T.unsafe(nil), Integer)

# Redirects are permanent failures too: signed POSTs are never replayed to another target
#
# pkg:gem/fedipub#lib/fediverse/notifier.rb:11
Fediverse::Notifier::PERMANENT_DELIVERY_STATUS_CODES = T.let(T.unsafe(nil), Array)

# Client errors that can clear on their own, as in Mastodon's DeliveryWorker.
# 401: Fedify rejects with "The signer and the actor do not match." whenever it cannot fetch
# the sender's actor document to confirm key ownership, including on a timeout.
#
# pkg:gem/fedipub#lib/fediverse/notifier.rb:15
Fediverse::Notifier::RETRYABLE_CLIENT_ERROR_STATUS_CODES = T.let(T.unsafe(nil), Array)

# pkg:gem/fedipub#lib/fediverse/request.rb:7
class Fediverse::Request
  class << self
    # Dereferences a value
    #
    # @param value [String, Hash]
    #
    # @return [Hash, nil]
    #
    # pkg:gem/fedipub#lib/fediverse/request.rb:14
    def dereference(value); end

    private

    # pkg:gem/fedipub#lib/fediverse/request.rb:33
    sig { params(json: T::Hash[::String, ::Object]).returns(T::Hash[::String, ::Object]) }
    def compact_json_ld(json); end

    # pkg:gem/fedipub#lib/fediverse/request.rb:24
    sig { params(id: ::String).returns(T.nilable(T::Hash[::String, ::Object])) }
    def get(id); end
  end
end

# pkg:gem/fedipub#lib/fediverse/signature.rb:2
module Fediverse::Signature
  class << self
    # Whether the request carries a body that the signature must cover
    #
    # pkg:gem/fedipub#lib/fediverse/signature.rb:80
    def body?(request); end

    # Finds (or fetches) the actor owning a key id
    #
    # @raise [BadSignature] when the actor can't be retrieved or has no public key
    #
    # pkg:gem/fedipub#lib/fediverse/signature.rb:45
    def find_sender(key_id); end

    # Re-fetches a remote sender whose cached data is stale, so a rotated key can be picked up.
    # The sender is touched even when nothing changed, so failing requests can't trigger a fetch every time.
    #
    # @return [Boolean] true if the sender was refreshed and verification is worth retrying
    # @raise [BadSignature] when the refresh fails
    #
    # pkg:gem/fedipub#lib/fediverse/signature.rb:62
    def refresh_stale_sender!(sender); end

    # Errors that can happen while fetching a remote signer; they mean the signature can't be verified.
    # (A method rather than a constant, so this file can be required before Rails is loaded.)
    #
    # pkg:gem/fedipub#lib/fediverse/signature.rb:8
    def sender_fetch_errors; end

    # pkg:gem/fedipub#lib/fediverse/signature.rb:12
    def sign(sender:, request:, legacy_signature: T.unsafe(nil)); end

    # Verifies the request's signature, if it has one.
    #
    # @return [true] when the signature is valid, or when the request is unsigned and signatures are optional
    # @raise [BadSignature] when the signature is invalid, or missing while required
    #
    # pkg:gem/fedipub#lib/fediverse/signature.rb:24
    def verify!(request:, require_signature: T.unsafe(nil)); end

    # Verifies the request's signature (RFC9421 first, then draft-cavage-12) and returns the actor whose
    # key was used to verify it, so callers never have to parse the key id again.
    #
    # @return [Fedipub::Actor, nil] the signer, or nil when the request is unsigned
    # @raise [BadSignature] when the signature is invalid
    #
    # pkg:gem/fedipub#lib/fediverse/signature.rb:36
    def verify_sender!(request:); end
  end
end

# pkg:gem/fedipub#lib/fediverse/signature.rb:3
class Fediverse::Signature::BadSignature < ::StandardError; end

# pkg:gem/fedipub#lib/fediverse/signature/draft_cavage12.rb:5
class Fediverse::Signature::DraftCavage12
  class << self
    # pkg:gem/fedipub#lib/fediverse/signature/draft_cavage12.rb:7
    def sign(sender:, request:); end

    # @return [Fedipub::Actor, false] the signer, or false if the request has no draft-cavage-12 signature
    # @raise [Fediverse::Signature::BadSignature] when the signature is invalid
    #
    # pkg:gem/fedipub#lib/fediverse/signature/draft_cavage12.rb:26
    def verify!(request:); end

    private

    # pkg:gem/fedipub#lib/fediverse/signature/draft_cavage12.rb:52
    def check_covered_headers!(request, headers); end

    # pkg:gem/fedipub#lib/fediverse/signature/draft_cavage12.rb:59
    def check_date!(request); end

    # pkg:gem/fedipub#lib/fediverse/signature/draft_cavage12.rb:92
    def digest(message); end

    # pkg:gem/fedipub#lib/fediverse/signature/draft_cavage12.rb:68
    def do_verification(signature, sender, comparison_string); end

    # Path and query string, as sent on the wire
    #
    # pkg:gem/fedipub#lib/fediverse/signature/draft_cavage12.rb:111
    def request_target_path(request); end

    # pkg:gem/fedipub#lib/fediverse/signature/draft_cavage12.rb:74
    def set_headers(request); end

    # pkg:gem/fedipub#lib/fediverse/signature/draft_cavage12.rb:128
    def signature(sender:, request:); end

    # pkg:gem/fedipub#lib/fediverse/signature/draft_cavage12.rb:81
    def signature_components(request); end

    # pkg:gem/fedipub#lib/fediverse/signature/draft_cavage12.rb:120
    def signature_headers(request); end

    # pkg:gem/fedipub#lib/fediverse/signature/draft_cavage12.rb:98
    def signature_payload(request:, headers: T.unsafe(nil)); end
  end
end

# pkg:gem/fedipub#lib/fediverse/signature/rfc9421.rb:9
class Fediverse::Signature::Rfc9421
  class << self
    # pkg:gem/fedipub#lib/fediverse/signature/rfc9421.rb:11
    def sign(sender:, request:); end

    # Verifies each signature label in turn and returns the sender of the first valid one.
    #
    # @return [Fedipub::Actor, false] the signer, or false if the request has no RFC9421 signature
    # @raise [Fediverse::Signature::BadSignature] when no signature label is valid
    #
    # pkg:gem/fedipub#lib/fediverse/signature/rfc9421.rb:32
    def verify!(request:); end

    private

    # Linzer only verifies what the signer chose to cover
    #
    # pkg:gem/fedipub#lib/fediverse/signature/rfc9421.rb:74
    def check_covered_components!(request, signature); end

    # pkg:gem/fedipub#lib/fediverse/signature/rfc9421.rb:81
    def check_created!(signature); end

    # pkg:gem/fedipub#lib/fediverse/signature/rfc9421.rb:104
    def components(request); end

    # pkg:gem/fedipub#lib/fediverse/signature/rfc9421.rb:112
    def digest(message); end

    # Converts key to right structure for Linzer to use
    #
    # pkg:gem/fedipub#lib/fediverse/signature/rfc9421.rb:92
    def linzer_private_key(sender); end

    # pkg:gem/fedipub#lib/fediverse/signature/rfc9421.rb:97
    def linzer_public_key(sender); end

    # pkg:gem/fedipub#lib/fediverse/signature/rfc9421.rb:50
    def signature_labels(headers); end

    # pkg:gem/fedipub#lib/fediverse/signature/rfc9421.rb:54
    def verify_label!(request, message, headers, label); end

    # pkg:gem/fedipub#lib/fediverse/signature/rfc9421.rb:64
    def verify_with_key_refresh!(sender, message, signature); end
  end
end

# Methods related to Webfinger: find accounts, fetch actors,...
#
# pkg:gem/fedipub#lib/fediverse/webfinger.rb:9
class Fediverse::Webfinger
  class << self
    # Fetches a distant actor
    #
    # @param username [String]
    # @param domain [String]
    #
    # @return [Fedipub::Actor]
    # @raise [ActiveRecord::RecordNotFound] when the actor cannot be resolved
    #
    # pkg:gem/fedipub#lib/fediverse/webfinger.rb:39
    def fetch_actor(username, domain); end

    # Fetches an actor given its URL
    #
    # @param url [String] Actor's federation URL
    #
    # @return [Fedipub::Actor]
    # @raise [ActiveRecord::RecordNotFound] when the actor cannot be resolved
    #
    # pkg:gem/fedipub#lib/fediverse/webfinger.rb:49
    def fetch_actor_url(url); end

    # Determines if a given account string should be a local account (same host as configured one)
    #
    # @param hash [Hash, MatchData] Object with +:username+ and +:domain+ keys
    #
    # @return [Boolean]
    #
    # pkg:gem/fedipub#lib/fediverse/webfinger.rb:28
    def local_user?(hash); end

    # Returns remote follow link template, or complete link if actor_url is provided
    #
    # @param username [String]
    # @param domain [String]
    # @param actor_url [String] Optional Federation URL to provide when known
    #
    # @return [String] The URL to use as follow URL
    #
    # pkg:gem/fedipub#lib/fediverse/webfinger.rb:78
    def remote_follow_url(username, domain, actor_url: T.unsafe(nil)); end

    # Extracts username and domain from an account string.
    # Accepts forms "user@domain", "@user@domain" and "acct:user@domain"
    #
    # @param account [String] Account string
    #
    # @return [MatchData, nil] Matches with +:username+ and +:domain+ or +nil+
    #
    # pkg:gem/fedipub#lib/fediverse/webfinger.rb:19
    def split_account(account); end

    # Gets the real actor's federation URL from its username and domain
    #
    # @param username [String]
    # @param domain [String]
    #
    # @return [String, nil] Federation URL if found
    #
    # pkg:gem/fedipub#lib/fediverse/webfinger.rb:59
    def webfinger(username, domain); end

    private

    # Makes a GET request (signed as the application actor) and returns a +Hash+ from the parsed body
    # @return [Hash]
    # @raise [ActiveRecord::RecordNotFound] when the response is invalid
    #
    # pkg:gem/fedipub#lib/fediverse/webfinger.rb:147
    def get_json(url, params = T.unsafe(nil)); end

    # Extracts the server and port from a string, omitting common ports
    # @return [String] Server and port
    #
    # pkg:gem/fedipub#lib/fediverse/webfinger.rb:106
    def server_and_port(string); end

    # Makes a webfinger request for a given username/domain
    # @return [Hash] Webfinger response's content
    #
    # pkg:gem/fedipub#lib/fediverse/webfinger.rb:99
    def webfinger_response(username, domain); end

    # Builds an unsaved remote +Fedipub::Actor+ from an ActivityPub actor document
    # @param data [Hash] ActivityPub actor document
    # @return [Fedipub::Actor]
    # @raise [ActiveRecord::RecordNotFound] when the payload is not a valid actor document
    #
    # pkg:gem/fedipub#lib/fediverse/webfinger.rb:119
    def webfinger_to_actor(data); end
  end
end
