# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `packwerk-extensions` gem.
# Please instead update this file by running `bin/tapioca gem packwerk-extensions`.


# pkg:gem/packwerk-extensions#lib/packwerk/privacy/package.rb:4
module Packwerk; end

# pkg:gem/packwerk-extensions#lib/packwerk-extensions.rb:12
module Packwerk::Extensions; end

# pkg:gem/packwerk-extensions#lib/packwerk/folder_privacy/package.rb:5
module Packwerk::FolderPrivacy; end

# pkg:gem/packwerk-extensions#lib/packwerk/folder_privacy/checker.rb:9
class Packwerk::FolderPrivacy::Checker
  include ::Packwerk::Checker

  # @override
  #
  # pkg:gem/packwerk-extensions#lib/packwerk/folder_privacy/checker.rb:22
  sig { override.params(reference: ::Packwerk::Reference).returns(T::Boolean) }
  def invalid_reference?(reference); end

  # @override
  #
  # pkg:gem/packwerk-extensions#lib/packwerk/folder_privacy/checker.rb:50
  sig { override.params(reference: ::Packwerk::Reference).returns(::String) }
  def message(reference); end

  # @override
  #
  # pkg:gem/packwerk-extensions#lib/packwerk/folder_privacy/checker.rb:43
  sig { override.params(listed_offense: ::Packwerk::ReferenceOffense).returns(T::Boolean) }
  def strict_mode_violation?(listed_offense); end

  # @override
  #
  # pkg:gem/packwerk-extensions#lib/packwerk/folder_privacy/checker.rb:16
  sig { override.returns(::String) }
  def violation_type; end

  private

  # pkg:gem/packwerk-extensions#lib/packwerk/folder_privacy/checker.rb:66
  sig { params(visibility_option: T.nilable(T.any(::String, T::Boolean))).returns(T::Boolean) }
  def enforcement_disabled?(visibility_option); end

  # pkg:gem/packwerk-extensions#lib/packwerk/folder_privacy/checker.rb:71
  sig { params(reference: ::Packwerk::Reference).returns(::String) }
  def standard_help_message(reference); end
end

# pkg:gem/packwerk-extensions#lib/packwerk/folder_privacy/checker.rb:12
Packwerk::FolderPrivacy::Checker::VIOLATION_TYPE = T.let(T.unsafe(nil), String)

# pkg:gem/packwerk-extensions#lib/packwerk/folder_privacy/package.rb:6
class Packwerk::FolderPrivacy::Package
  # pkg:gem/packwerk-extensions#lib/packwerk/folder_privacy/package.rb:11
  sig { params(enforce_folder_privacy: T.nilable(T.any(::String, T::Boolean))).void }
  def initialize(enforce_folder_privacy:); end

  # pkg:gem/packwerk-extensions#lib/packwerk/folder_privacy/package.rb:8
  sig { returns(T.nilable(T.any(::String, T::Boolean))) }
  def enforce_folder_privacy; end

  class << self
    # pkg:gem/packwerk-extensions#lib/packwerk/folder_privacy/package.rb:17
    sig { params(package: ::Packwerk::Package).returns(::Packwerk::FolderPrivacy::Package) }
    def from(package); end
  end
end

# pkg:gem/packwerk-extensions#lib/packwerk/folder_privacy/validator.rb:6
class Packwerk::FolderPrivacy::Validator
  include ::Packwerk::Validator

  # @override
  #
  # pkg:gem/packwerk-extensions#lib/packwerk/folder_privacy/validator.rb:13
  sig do
    override
      .params(
        package_set: Packwerk::PackageSet,
        configuration: ::Packwerk::Configuration
      ).returns(::Packwerk::Validator::Result)
  end
  def call(package_set, configuration); end

  # @override
  #
  # pkg:gem/packwerk-extensions#lib/packwerk/folder_privacy/validator.rb:32
  sig { override.returns(T::Array[::String]) }
  def permitted_keys; end
end

# pkg:gem/packwerk-extensions#lib/packwerk/folder_privacy/validator.rb:9
Packwerk::FolderPrivacy::Validator::Result = Packwerk::Validator::Result

# pkg:gem/packwerk-extensions#lib/packwerk/layer/config.rb:5
module Packwerk::Layer; end

# This enforces "layered architecture," which allows each class to be designated as one of N layers
# configured by the client in `packwerk.yml`, for example:
#
# layers:
#   - orchestrator
#   - business_domain
#   - platform
#   - utility
#   - specification
#
# Then a package can configure:
# enforce_layers: true | false | strict
# layer: utility
#
# This is intended to provide:
# A) Direction for which dependency violations to tackle
# B) What dependencies should or should not exist
# C) A potential sequencing for modularizing a system (starting with lower layers first).
#
# pkg:gem/packwerk-extensions#lib/packwerk/layer/checker.rb:30
class Packwerk::Layer::Checker
  include ::Packwerk::Checker

  # @override
  #
  # pkg:gem/packwerk-extensions#lib/packwerk/layer/checker.rb:41
  sig { override.params(reference: ::Packwerk::Reference).returns(T::Boolean) }
  def invalid_reference?(reference); end

  # pkg:gem/packwerk-extensions#lib/packwerk/layer/checker.rb:89
  sig { returns(::Packwerk::Layer::Config) }
  def layer_config; end

  # pkg:gem/packwerk-extensions#lib/packwerk/layer/checker.rb:84
  sig { returns(::Packwerk::Layer::Layers) }
  def layers; end

  # @override
  #
  # pkg:gem/packwerk-extensions#lib/packwerk/layer/checker.rb:56
  sig { override.params(reference: ::Packwerk::Reference).returns(::String) }
  def message(reference); end

  # TODO: Extract this out into a common helper, can call it StandardViolationHelpMessage.new(...) and implements .to_s
  #
  # pkg:gem/packwerk-extensions#lib/packwerk/layer/checker.rb:74
  sig { params(reference: ::Packwerk::Reference).returns(::String) }
  def standard_help_message(reference); end

  # @override
  #
  # pkg:gem/packwerk-extensions#lib/packwerk/layer/checker.rb:49
  sig { override.params(listed_offense: ::Packwerk::ReferenceOffense).returns(T::Boolean) }
  def strict_mode_violation?(listed_offense); end

  # @override
  #
  # pkg:gem/packwerk-extensions#lib/packwerk/layer/checker.rb:35
  sig { override.returns(::String) }
  def violation_type; end
end

# pkg:gem/packwerk-extensions#lib/packwerk/layer/config.rb:6
class Packwerk::Layer::Config
  # pkg:gem/packwerk-extensions#lib/packwerk/layer/config.rb:33
  sig { returns(::String) }
  def enforce_key; end

  # pkg:gem/packwerk-extensions#lib/packwerk/layer/config.rb:23
  sig { returns(::String) }
  def layers_key; end

  # pkg:gem/packwerk-extensions#lib/packwerk/layer/config.rb:18
  sig { returns(T::Boolean) }
  def layers_key_configured?; end

  # pkg:gem/packwerk-extensions#lib/packwerk/layer/config.rb:13
  sig { returns(T::Array[::String]) }
  def layers_list; end

  # pkg:gem/packwerk-extensions#lib/packwerk/layer/config.rb:28
  sig { returns(::String) }
  def violation_key; end
end

# pkg:gem/packwerk-extensions#lib/packwerk/layer/config.rb:8
Packwerk::Layer::Config::ARCHITECTURE_ENFORCE = T.let(T.unsafe(nil), String)

# pkg:gem/packwerk-extensions#lib/packwerk/layer/config.rb:7
Packwerk::Layer::Config::ARCHITECTURE_VIOLATION_TYPE = T.let(T.unsafe(nil), String)

# pkg:gem/packwerk-extensions#lib/packwerk/layer/config.rb:10
Packwerk::Layer::Config::LAYER_ENFORCE = T.let(T.unsafe(nil), String)

# pkg:gem/packwerk-extensions#lib/packwerk/layer/config.rb:9
Packwerk::Layer::Config::LAYER_VIOLATION_TYPE = T.let(T.unsafe(nil), String)

# pkg:gem/packwerk-extensions#lib/packwerk/layer/layers.rb:6
class Packwerk::Layer::Layers
  # pkg:gem/packwerk-extensions#lib/packwerk/layer/layers.rb:8
  sig { params(layer: ::String).returns(::Integer) }
  def index_of(layer); end

  # pkg:gem/packwerk-extensions#lib/packwerk/layer/layers.rb:18
  sig { returns(T::Set[::String]) }
  def names; end

  # pkg:gem/packwerk-extensions#lib/packwerk/layer/layers.rb:23
  sig { returns(T::Array[::String]) }
  def names_list; end
end

# pkg:gem/packwerk-extensions#lib/packwerk/layer/package.rb:6
class Packwerk::Layer::Package
  # pkg:gem/packwerk-extensions#lib/packwerk/layer/package.rb:17
  sig do
    params(
      layer: T.nilable(::String),
      enforcement_setting: T.nilable(T.any(::String, T::Array[::String], T::Boolean)),
      config: T::Hash[T.untyped, T.untyped]
    ).void
  end
  def initialize(layer:, enforcement_setting:, config:); end

  # pkg:gem/packwerk-extensions#lib/packwerk/layer/package.rb:29
  sig { params(other_package: ::Packwerk::Layer::Package, layers: ::Packwerk::Layer::Layers).returns(T::Boolean) }
  def can_depend_on?(other_package, layers:); end

  # pkg:gem/packwerk-extensions#lib/packwerk/layer/package.rb:14
  sig { returns(T::Hash[T.untyped, T.untyped]) }
  def config; end

  # pkg:gem/packwerk-extensions#lib/packwerk/layer/package.rb:11
  sig { returns(T.nilable(T.any(::String, T::Array[::String], T::Boolean))) }
  def enforcement_setting; end

  # pkg:gem/packwerk-extensions#lib/packwerk/layer/package.rb:24
  sig { returns(T::Boolean) }
  def enforces?; end

  # pkg:gem/packwerk-extensions#lib/packwerk/layer/package.rb:8
  sig { returns(T.nilable(::String)) }
  def layer; end

  class << self
    # pkg:gem/packwerk-extensions#lib/packwerk/layer/package.rb:42
    sig { params(package: ::Packwerk::Package, layers: ::Packwerk::Layer::Layers).returns(::Packwerk::Layer::Package) }
    def from(package, layers); end
  end
end

# pkg:gem/packwerk-extensions#lib/packwerk/layer/validator.rb:6
class Packwerk::Layer::Validator
  include ::Packwerk::Validator

  # @override
  #
  # pkg:gem/packwerk-extensions#lib/packwerk/layer/validator.rb:13
  sig do
    override
      .params(
        package_set: Packwerk::PackageSet,
        configuration: ::Packwerk::Configuration
      ).returns(::Packwerk::Validator::Result)
  end
  def call(package_set, configuration); end

  # pkg:gem/packwerk-extensions#lib/packwerk/layer/validator.rb:56
  sig do
    params(
      package: ::Packwerk::Layer::Package,
      config_file_path: ::String,
      config: T::Hash[T.untyped, T.untyped]
    ).returns(::Packwerk::Validator::Result)
  end
  def check_enforce_key(package, config_file_path, config); end

  # pkg:gem/packwerk-extensions#lib/packwerk/layer/validator.rb:96
  sig { params(config_file_path: ::String, setting: T.untyped).returns(::Packwerk::Validator::Result) }
  def check_enforce_layers_setting(config_file_path, setting); end

  # pkg:gem/packwerk-extensions#lib/packwerk/layer/validator.rb:76
  sig do
    params(
      package: ::Packwerk::Layer::Package,
      config_file_path: ::String
    ).returns(::Packwerk::Validator::Result)
  end
  def check_layer_setting(package, config_file_path); end

  # pkg:gem/packwerk-extensions#lib/packwerk/layer/validator.rb:45
  sig { returns(::Packwerk::Layer::Config) }
  def layer_config; end

  # pkg:gem/packwerk-extensions#lib/packwerk/layer/validator.rb:40
  sig { returns(::Packwerk::Layer::Layers) }
  def layers; end

  # @override
  #
  # pkg:gem/packwerk-extensions#lib/packwerk/layer/validator.rb:51
  sig { override.returns(T::Array[::String]) }
  def permitted_keys; end
end

# pkg:gem/packwerk-extensions#lib/packwerk/layer/validator.rb:9
Packwerk::Layer::Validator::Result = Packwerk::Validator::Result

# pkg:gem/packwerk-extensions#lib/packwerk/privacy/package.rb:5
module Packwerk::Privacy; end

# Checks whether a given reference references a private constant of another package.
#
# pkg:gem/packwerk-extensions#lib/packwerk/privacy/checker.rb:10
class Packwerk::Privacy::Checker
  include ::Packwerk::Checker

  # @override
  #
  # pkg:gem/packwerk-extensions#lib/packwerk/privacy/checker.rb:57
  sig { override.params(reference: ::Packwerk::Reference).returns(T::Boolean) }
  def invalid_reference?(reference); end

  # @override
  #
  # pkg:gem/packwerk-extensions#lib/packwerk/privacy/checker.rb:88
  sig { override.params(reference: ::Packwerk::Reference).returns(::String) }
  def message(reference); end

  # @override
  #
  # pkg:gem/packwerk-extensions#lib/packwerk/privacy/checker.rb:74
  sig { override.params(listed_offense: ::Packwerk::ReferenceOffense).returns(T::Boolean) }
  def strict_mode_violation?(listed_offense); end

  # @override
  #
  # pkg:gem/packwerk-extensions#lib/packwerk/privacy/checker.rb:51
  sig { override.returns(::String) }
  def violation_type; end

  private

  # pkg:gem/packwerk-extensions#lib/packwerk/privacy/checker.rb:113
  sig { params(privacy_option: T.nilable(T.any(::String, T::Array[::String], T::Boolean))).returns(T::Boolean) }
  def enforcement_disabled?(privacy_option); end

  # pkg:gem/packwerk-extensions#lib/packwerk/privacy/checker.rb:128
  sig { params(globs: T::Array[::String], path: ::Pathname).returns(T::Boolean) }
  def exclude_from_strict?(globs, path); end

  # pkg:gem/packwerk-extensions#lib/packwerk/privacy/checker.rb:104
  sig do
    params(
      constant: ::Packwerk::ConstantContext,
      explicitly_private_constants: T::Array[::String]
    ).returns(T::Boolean)
  end
  def explicitly_private_constant?(constant, explicitly_private_constants:); end

  # pkg:gem/packwerk-extensions#lib/packwerk/privacy/checker.rb:118
  sig { params(reference: ::Packwerk::Reference).returns(::String) }
  def standard_help_message(reference); end

  class << self
    # pkg:gem/packwerk-extensions#lib/packwerk/privacy/checker.rb:32
    sig { params(location: ::String).returns(T::Boolean) }
    def check_for_publicized_sigil(location); end

    # pkg:gem/packwerk-extensions#lib/packwerk/privacy/checker.rb:37
    sig { params(lines: T::Array[::String]).returns(T::Boolean) }
    def content_contains_sigil?(lines); end

    # pkg:gem/packwerk-extensions#lib/packwerk/privacy/checker.rb:23
    sig { params(location: ::String).returns(T::Boolean) }
    def publicized_location?(location); end

    # pkg:gem/packwerk-extensions#lib/packwerk/privacy/checker.rb:20
    sig { returns(T::Hash[::String, T::Boolean]) }
    def publicized_locations; end
  end
end

# pkg:gem/packwerk-extensions#lib/packwerk/privacy/checker.rb:14
Packwerk::Privacy::Checker::PUBLICIZED_SIGIL = T.let(T.unsafe(nil), String)

# pkg:gem/packwerk-extensions#lib/packwerk/privacy/checker.rb:15
Packwerk::Privacy::Checker::PUBLICIZED_SIGIL_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/packwerk-extensions#lib/packwerk/privacy/checker.rb:13
Packwerk::Privacy::Checker::VIOLATION_TYPE = T.let(T.unsafe(nil), String)

# pkg:gem/packwerk-extensions#lib/packwerk/privacy/package.rb:6
class Packwerk::Privacy::Package
  # pkg:gem/packwerk-extensions#lib/packwerk/privacy/package.rb:26
  sig do
    params(
      public_path: ::String,
      user_defined_public_path: T.nilable(::String),
      enforce_privacy: T.nilable(T.any(::String, T::Boolean)),
      private_constants: T::Array[::String],
      ignored_private_constants: T::Array[::String],
      strict_privacy_ignored_patterns: T::Array[::String]
    ).void
  end
  def initialize(public_path:, user_defined_public_path:, enforce_privacy:, private_constants:, ignored_private_constants:, strict_privacy_ignored_patterns:); end

  # pkg:gem/packwerk-extensions#lib/packwerk/privacy/package.rb:14
  sig { returns(T.nilable(T.any(::String, T::Boolean))) }
  def enforce_privacy; end

  # pkg:gem/packwerk-extensions#lib/packwerk/privacy/package.rb:20
  sig { returns(T::Array[::String]) }
  def ignored_private_constants; end

  # pkg:gem/packwerk-extensions#lib/packwerk/privacy/package.rb:17
  sig { returns(T::Array[::String]) }
  def private_constants; end

  # pkg:gem/packwerk-extensions#lib/packwerk/privacy/package.rb:8
  sig { returns(::String) }
  def public_path; end

  # pkg:gem/packwerk-extensions#lib/packwerk/privacy/package.rb:43
  sig { params(path: ::String).returns(T::Boolean) }
  def public_path?(path); end

  # pkg:gem/packwerk-extensions#lib/packwerk/privacy/package.rb:23
  sig { returns(T::Array[::String]) }
  def strict_privacy_ignored_patterns; end

  # pkg:gem/packwerk-extensions#lib/packwerk/privacy/package.rb:11
  sig { returns(T.nilable(::String)) }
  def user_defined_public_path; end

  class << self
    # pkg:gem/packwerk-extensions#lib/packwerk/privacy/package.rb:49
    sig { params(package: ::Packwerk::Package).returns(::Packwerk::Privacy::Package) }
    def from(package); end

    # pkg:gem/packwerk-extensions#lib/packwerk/privacy/package.rb:69
    sig { params(package: ::Packwerk::Package).returns(::String) }
    def public_path_for(package); end

    # pkg:gem/packwerk-extensions#lib/packwerk/privacy/package.rb:61
    sig { params(package: ::Packwerk::Package).returns(T.nilable(::String)) }
    def user_defined_public_path(package); end
  end
end

# pkg:gem/packwerk-extensions#lib/packwerk/privacy/validator.rb:6
class Packwerk::Privacy::Validator
  include ::Packwerk::Validator

  # @override
  #
  # pkg:gem/packwerk-extensions#lib/packwerk/privacy/validator.rb:13
  sig do
    override
      .params(
        package_set: Packwerk::PackageSet,
        configuration: ::Packwerk::Configuration
      ).returns(::Packwerk::Validator::Result)
  end
  def call(package_set, configuration); end

  # @override
  #
  # pkg:gem/packwerk-extensions#lib/packwerk/privacy/validator.rb:32
  sig { override.returns(T::Array[::String]) }
  def permitted_keys; end

  private

  # pkg:gem/packwerk-extensions#lib/packwerk/privacy/validator.rb:134
  sig { params(constants: T.untyped, config_file_path: ::String).returns(T::Array[::Packwerk::Validator::Result]) }
  def assert_constants_can_be_loaded(constants, config_file_path); end

  # pkg:gem/packwerk-extensions#lib/packwerk/privacy/validator.rb:90
  sig { params(config_file_path: ::String, setting: T.untyped).returns(::Packwerk::Validator::Result) }
  def check_enforce_privacy_setting(config_file_path, setting); end

  # pkg:gem/packwerk-extensions#lib/packwerk/privacy/validator.rb:117
  sig do
    params(
      location: ::String,
      constant_package: ::Packwerk::Package,
      name: T.untyped
    ).returns(::Packwerk::Validator::Result)
  end
  def check_for_publicized_constant(location, constant_package, name); end

  # pkg:gem/packwerk-extensions#lib/packwerk/privacy/validator.rb:102
  sig do
    params(
      configuration: ::Packwerk::Configuration,
      package_set: Packwerk::PackageSet,
      name: T.untyped,
      location: T.untyped,
      config_file_path: T.untyped
    ).returns(::Packwerk::Validator::Result)
  end
  def check_private_constant_location(configuration, package_set, name, location, config_file_path); end

  # pkg:gem/packwerk-extensions#lib/packwerk/privacy/validator.rb:78
  sig { params(config_file_path: ::String, setting: T.untyped).returns(::Packwerk::Validator::Result) }
  def check_public_path(config_file_path, setting); end

  # pkg:gem/packwerk-extensions#lib/packwerk/privacy/validator.rb:151
  sig { params(name: T.untyped, config_file_path: T.untyped).returns(::Packwerk::Validator::Result) }
  def private_constant_unresolvable(name, config_file_path); end

  # pkg:gem/packwerk-extensions#lib/packwerk/privacy/validator.rb:39
  sig do
    params(
      package_set: Packwerk::PackageSet,
      configuration: ::Packwerk::Configuration
    ).returns(T::Array[::Packwerk::Validator::Result])
  end
  def verify_private_constants_setting(package_set, configuration); end
end

# pkg:gem/packwerk-extensions#lib/packwerk/privacy/validator.rb:9
Packwerk::Privacy::Validator::Result = Packwerk::Validator::Result

# pkg:gem/packwerk-extensions#lib/packwerk/privacy/validator.rb:9
class Packwerk::Validator::Result; end

# pkg:gem/packwerk-extensions#lib/packwerk/visibility/package.rb:5
module Packwerk::Visibility; end

# Checks whether a given reference references a constant from a package that does not permit visibility
#
# pkg:gem/packwerk-extensions#lib/packwerk/visibility/checker.rb:10
class Packwerk::Visibility::Checker
  include ::Packwerk::Checker

  # @override
  #
  # pkg:gem/packwerk-extensions#lib/packwerk/visibility/checker.rb:23
  sig { override.params(reference: ::Packwerk::Reference).returns(T::Boolean) }
  def invalid_reference?(reference); end

  # @override
  #
  # pkg:gem/packwerk-extensions#lib/packwerk/visibility/checker.rb:41
  sig { override.params(reference: ::Packwerk::Reference).returns(::String) }
  def message(reference); end

  # @override
  #
  # pkg:gem/packwerk-extensions#lib/packwerk/visibility/checker.rb:34
  sig { override.params(listed_offense: ::Packwerk::ReferenceOffense).returns(T::Boolean) }
  def strict_mode_violation?(listed_offense); end

  # @override
  #
  # pkg:gem/packwerk-extensions#lib/packwerk/visibility/checker.rb:17
  sig { override.returns(::String) }
  def violation_type; end

  private

  # pkg:gem/packwerk-extensions#lib/packwerk/visibility/checker.rb:57
  sig { params(visibility_option: T.nilable(T.any(::String, T::Boolean))).returns(T::Boolean) }
  def enforcement_disabled?(visibility_option); end

  # pkg:gem/packwerk-extensions#lib/packwerk/visibility/checker.rb:62
  sig { params(reference: ::Packwerk::Reference).returns(::String) }
  def standard_help_message(reference); end
end

# pkg:gem/packwerk-extensions#lib/packwerk/visibility/checker.rb:13
Packwerk::Visibility::Checker::VIOLATION_TYPE = T.let(T.unsafe(nil), String)

# pkg:gem/packwerk-extensions#lib/packwerk/visibility/package.rb:6
class Packwerk::Visibility::Package
  # pkg:gem/packwerk-extensions#lib/packwerk/visibility/package.rb:14
  sig { params(visible_to: T::Array[::String], enforce_visibility: T.nilable(T.any(::String, T::Boolean))).void }
  def initialize(visible_to:, enforce_visibility:); end

  # pkg:gem/packwerk-extensions#lib/packwerk/visibility/package.rb:11
  sig { returns(T.nilable(T.any(::String, T::Boolean))) }
  def enforce_visibility; end

  # pkg:gem/packwerk-extensions#lib/packwerk/visibility/package.rb:8
  sig { returns(T::Array[::String]) }
  def visible_to; end

  class << self
    # pkg:gem/packwerk-extensions#lib/packwerk/visibility/package.rb:21
    sig { params(package: ::Packwerk::Package).returns(::Packwerk::Visibility::Package) }
    def from(package); end
  end
end

# pkg:gem/packwerk-extensions#lib/packwerk/visibility/validator.rb:6
class Packwerk::Visibility::Validator
  include ::Packwerk::Validator

  # @override
  #
  # pkg:gem/packwerk-extensions#lib/packwerk/visibility/validator.rb:13
  sig do
    override
      .params(
        package_set: Packwerk::PackageSet,
        configuration: ::Packwerk::Configuration
      ).returns(::Packwerk::Validator::Result)
  end
  def call(package_set, configuration); end

  # @override
  #
  # pkg:gem/packwerk-extensions#lib/packwerk/visibility/validator.rb:55
  sig { override.returns(T::Array[::String]) }
  def permitted_keys; end
end

# pkg:gem/packwerk-extensions#lib/packwerk/visibility/validator.rb:9
Packwerk::Visibility::Validator::Result = Packwerk::Validator::Result
