# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `pg_search` gem.
# Please instead update this file by running `bin/tapioca gem pg_search`.


# pkg:gem/pg_search#lib/pg_search/configuration/association.rb:5
module PgSearch
  include ::PgSearch::Model

  mixes_in_class_methods ::PgSearch::Model::ClassMethods

  # pkg:gem/pg_search#lib/pg_search.rb:30
  def multisearch_options; end

  # pkg:gem/pg_search#lib/pg_search.rb:30
  def multisearch_options=(val); end

  # pkg:gem/pg_search#lib/pg_search.rb:33
  def unaccent_function; end

  # pkg:gem/pg_search#lib/pg_search.rb:33
  def unaccent_function=(val); end

  class << self
    # pkg:gem/pg_search#lib/pg_search.rb:41
    def disable_multisearch; end

    # pkg:gem/pg_search#lib/pg_search.rb:20
    def included(base); end

    # pkg:gem/pg_search#lib/pg_search.rb:37
    def multisearch(*_arg0, **_arg1, &_arg2); end

    # pkg:gem/pg_search#lib/pg_search.rb:48
    def multisearch_enabled?; end

    # pkg:gem/pg_search#lib/pg_search.rb:30
    def multisearch_options; end

    # pkg:gem/pg_search#lib/pg_search.rb:30
    def multisearch_options=(val); end

    # pkg:gem/pg_search#lib/pg_search.rb:33
    def unaccent_function; end

    # pkg:gem/pg_search#lib/pg_search.rb:33
    def unaccent_function=(val); end
  end
end

# pkg:gem/pg_search#lib/pg_search/configuration/association.rb:6
class PgSearch::Configuration
  # pkg:gem/pg_search#lib/pg_search/configuration.rb:11
  def initialize(options, model); end

  # pkg:gem/pg_search#lib/pg_search/configuration.rb:44
  def associated_columns; end

  # pkg:gem/pg_search#lib/pg_search/configuration.rb:36
  def associations; end

  # pkg:gem/pg_search#lib/pg_search/configuration.rb:26
  def columns; end

  # pkg:gem/pg_search#lib/pg_search/configuration.rb:54
  def feature_options; end

  # pkg:gem/pg_search#lib/pg_search/configuration.rb:52
  def features; end

  # pkg:gem/pg_search#lib/pg_search/configuration.rb:48
  def ignore; end

  # pkg:gem/pg_search#lib/pg_search/configuration.rb:9
  def model; end

  # pkg:gem/pg_search#lib/pg_search/configuration.rb:58
  def order_within_rank; end

  # pkg:gem/pg_search#lib/pg_search/configuration.rb:46
  def query; end

  # pkg:gem/pg_search#lib/pg_search/configuration.rb:50
  def ranking_sql; end

  # pkg:gem/pg_search#lib/pg_search/configuration.rb:28
  def regular_columns; end

  private

  # standard:enable Lint/UselessConstantScoping
  #
  # pkg:gem/pg_search#lib/pg_search/configuration.rb:78
  def assert_valid_options(options); end

  # pkg:gem/pg_search#lib/pg_search/configuration.rb:64
  def default_options; end

  # pkg:gem/pg_search#lib/pg_search/configuration.rb:62
  def options; end

  # pkg:gem/pg_search#lib/pg_search/configuration.rb:95
  def using_tsvector_column?(options); end

  class << self
    # pkg:gem/pg_search#lib/pg_search/configuration.rb:19
    def alias(*strings); end
  end
end

# pkg:gem/pg_search#lib/pg_search/configuration/association.rb:7
class PgSearch::Configuration::Association
  # pkg:gem/pg_search#lib/pg_search/configuration/association.rb:10
  def initialize(model, name, column_names); end

  # pkg:gem/pg_search#lib/pg_search/configuration/association.rb:22
  def arel_table; end

  # pkg:gem/pg_search#lib/pg_search/configuration/association.rb:8
  def columns; end

  # pkg:gem/pg_search#lib/pg_search/configuration/association.rb:39
  def subselect_alias; end

  # pkg:gem/pg_search#lib/pg_search/configuration/association.rb:18
  def table_name; end

  # Builds an outer join retaining association-scope binds.
  #
  # Arguments
  #
  # +primary_key+:: An Arel expression or trusted SQL String identifying the
  #                 model's primary-key column, not a record's key value.
  #
  # Returns a composable outer join to the search subquery.
  #
  # pkg:gem/pg_search#lib/pg_search/configuration/association.rb:32
  def to_arel(primary_key); end

  private

  # pkg:gem/pg_search#lib/pg_search/configuration/association.rb:45
  def relation(primary_key); end

  # pkg:gem/pg_search#lib/pg_search/configuration/association.rb:54
  def selects; end

  # pkg:gem/pg_search#lib/pg_search/configuration/association.rb:72
  def singular_association?; end
end

# pkg:gem/pg_search#lib/pg_search/configuration/column.rb:7
class PgSearch::Configuration::Column
  # pkg:gem/pg_search#lib/pg_search/configuration/column.rb:10
  def initialize(column_name, weight, model); end

  # pkg:gem/pg_search#lib/pg_search/configuration/column.rb:8
  def name; end

  # Physical source-column attribute, or the supplied trusted SQL literal.
  # Foreign columns refer to the association table, not the search alias.
  #
  # pkg:gem/pg_search#lib/pg_search/configuration/column.rb:19
  def source_attribute; end

  # Composable search expression cast to text, with NULL mapped to "".
  # Foreign columns use their derived search alias rather than the source.
  #
  # pkg:gem/pg_search#lib/pg_search/configuration/column.rb:27
  def to_arel; end

  # pkg:gem/pg_search#lib/pg_search/configuration/column.rb:8
  def weight; end

  private

  # pkg:gem/pg_search#lib/pg_search/configuration/column.rb:31
  def attribute; end

  # pkg:gem/pg_search#lib/pg_search/configuration/column.rb:37
  def cast_to_text(node); end

  # pkg:gem/pg_search#lib/pg_search/configuration/column.rb:41
  def coalesce_to_blank_string(node); end

  # pkg:gem/pg_search#lib/pg_search/configuration/column.rb:45
  def source_table; end
end

# pkg:gem/pg_search#lib/pg_search/configuration/foreign_column.rb:7
class PgSearch::Configuration::ForeignColumn < ::PgSearch::Configuration::Column
  # pkg:gem/pg_search#lib/pg_search/configuration/foreign_column.rb:10
  def initialize(column_name, weight, model, association); end

  # pkg:gem/pg_search#lib/pg_search/configuration/foreign_column.rb:15
  def alias; end

  # pkg:gem/pg_search#lib/pg_search/configuration/foreign_column.rb:8
  def weight; end

  private

  # pkg:gem/pg_search#lib/pg_search/configuration/foreign_column.rb:21
  def attribute; end

  # pkg:gem/pg_search#lib/pg_search/configuration/foreign_column.rb:25
  def source_table; end
end

# standard:disable Lint/UselessConstantScoping
#
# pkg:gem/pg_search#lib/pg_search/configuration.rb:69
PgSearch::Configuration::VALID_KEYS = T.let(T.unsafe(nil), Array)

# pkg:gem/pg_search#lib/pg_search/configuration.rb:73
PgSearch::Configuration::VALID_VALUES = T.let(T.unsafe(nil), Hash)

# pkg:gem/pg_search#lib/pg_search/document.rb:6
class PgSearch::Document < ::ActiveRecord::Base
  include ::PgSearch::Document::GeneratedAttributeMethods
  include ::PgSearch::Document::GeneratedAssociationMethods
  include ::PgSearch::Model
  extend ::PgSearch::Model::ClassMethods

  # pkg:gem/pg_search#lib/pg_search/document.rb:10
  def _run_save_callbacks(&block); end

  # pkg:gem/pg_search#lib/pg_search/document.rb:10
  def autosave_associated_records_for_searchable(*args); end

  class << self
    # The logger might not have loaded yet.
    # https://github.com/Casecommons/pg_search/issues/26
    #
    # pkg:gem/pg_search#lib/pg_search/document.rb:14
    def logger; end

    # pkg:gem/pg_search#lib/pg_search/document.rb:18
    def search(*args); end

    private

    # pkg:gem/pg_search#lib/pg_search/document.rb:10
    def __class_attr___callbacks; end

    # pkg:gem/pg_search#lib/pg_search/document.rb:10
    def __class_attr___callbacks=(new_value); end

    # pkg:gem/pg_search#lib/pg_search/document.rb:10
    def __class_attr__reflections; end

    # pkg:gem/pg_search#lib/pg_search/document.rb:10
    def __class_attr__reflections=(new_value); end

    # pkg:gem/pg_search#lib/pg_search/document.rb:6
    def __class_attr__validators; end

    # pkg:gem/pg_search#lib/pg_search/document.rb:6
    def __class_attr__validators=(new_value); end

    # pkg:gem/pg_search#lib/pg_search/document.rb:6
    def __class_attr_defined_enums; end

    # pkg:gem/pg_search#lib/pg_search/document.rb:6
    def __class_attr_defined_enums=(new_value); end
  end
end

# pkg:gem/pg_search#lib/pg_search/document.rb:6
module PgSearch::Document::GeneratedAssociationMethods
  # pkg:gem/pg_search#lib/pg_search/document.rb:10
  def reload_searchable; end

  # pkg:gem/pg_search#lib/pg_search/document.rb:10
  def reset_searchable; end

  # pkg:gem/pg_search#lib/pg_search/document.rb:10
  def searchable; end

  # pkg:gem/pg_search#lib/pg_search/document.rb:10
  def searchable=(value); end

  # pkg:gem/pg_search#lib/pg_search/document.rb:10
  def searchable_changed?; end

  # pkg:gem/pg_search#lib/pg_search/document.rb:10
  def searchable_previously_changed?; end
end

# pkg:gem/pg_search#lib/pg_search/document.rb:6
module PgSearch::Document::GeneratedAttributeMethods; end

# Search features provide conditions and rank as composable Arel expressions,
# not SQL Strings. TSearch also provides a highlight expression for selection.
#
# pkg:gem/pg_search#lib/pg_search/features/feature.rb:6
module PgSearch::Features; end

# pkg:gem/pg_search#lib/pg_search/features/dmetaphone.rb:7
class PgSearch::Features::DMetaphone
  # pkg:gem/pg_search#lib/pg_search/features/dmetaphone.rb:8
  def initialize(query, options, columns, model, normalizer); end

  # pkg:gem/pg_search#lib/pg_search/features/dmetaphone.rb:14
  def conditions(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/pg_search#lib/pg_search/features/dmetaphone.rb:16
  def rank(*_arg0, **_arg1, &_arg2); end

  private

  # pkg:gem/pg_search#lib/pg_search/features/dmetaphone.rb:20
  def tsearch; end
end

# Decorates a normalizer with dmetaphone processing.
#
# pkg:gem/pg_search#lib/pg_search/features/dmetaphone.rb:23
class PgSearch::Features::DMetaphone::Normalizer
  # pkg:gem/pg_search#lib/pg_search/features/dmetaphone.rb:24
  def initialize(normalizer_to_wrap); end

  # pkg:gem/pg_search#lib/pg_search/features/dmetaphone.rb:28
  def add_normalization(expression); end

  private

  # pkg:gem/pg_search#lib/pg_search/features/dmetaphone.rb:37
  def normalizer_to_wrap; end
end

# pkg:gem/pg_search#lib/pg_search/features/feature.rb:7
class PgSearch::Features::Feature
  # pkg:gem/pg_search#lib/pg_search/features/feature.rb:12
  def initialize(query, options, all_columns, model, normalizer); end

  private

  # pkg:gem/pg_search#lib/pg_search/features/feature.rb:22
  def all_columns; end

  # pkg:gem/pg_search#lib/pg_search/features/feature.rb:35
  def columns; end

  # pkg:gem/pg_search#lib/pg_search/features/feature.rb:24
  def document; end

  # pkg:gem/pg_search#lib/pg_search/features/feature.rb:22
  def model; end

  # pkg:gem/pg_search#lib/pg_search/features/feature.rb:45
  def normalize(expression); end

  # pkg:gem/pg_search#lib/pg_search/features/feature.rb:22
  def normalizer; end

  # pkg:gem/pg_search#lib/pg_search/features/feature.rb:22
  def options; end

  # pkg:gem/pg_search#lib/pg_search/features/feature.rb:22
  def query; end

  class << self
    # pkg:gem/pg_search#lib/pg_search/features/feature.rb:8
    def valid_options; end
  end
end

# pkg:gem/pg_search#lib/pg_search/features/tsearch.rb:8
class PgSearch::Features::TSearch < ::PgSearch::Features::Feature
  # pkg:gem/pg_search#lib/pg_search/features/tsearch.rb:13
  def conditions; end

  # pkg:gem/pg_search#lib/pg_search/features/tsearch.rb:23
  def highlight; end

  # pkg:gem/pg_search#lib/pg_search/features/tsearch.rb:19
  def rank; end

  private

  # pkg:gem/pg_search#lib/pg_search/features/tsearch.rb:179
  def column_to_tsvector(search_column); end

  # pkg:gem/pg_search#lib/pg_search/features/tsearch.rb:171
  def columns_to_use; end

  # pkg:gem/pg_search#lib/pg_search/features/tsearch.rb:57
  def deprecated_headline_options; end

  # pkg:gem/pg_search#lib/pg_search/features/tsearch.rb:167
  def dictionary; end

  # pkg:gem/pg_search#lib/pg_search/features/tsearch.rb:47
  def headline_options; end

  # From http://www.postgresql.org/docs/8.3/static/textsearch-controls.html
  #   0 (the default) ignores the document length
  #   1 divides the rank by 1 + the logarithm of the document length
  #   2 divides the rank by the document length
  #   4 divides the rank by the mean harmonic distance between extents (this is implemented only by ts_rank_cd)
  #   8 divides the rank by the number of unique words in document
  #   16 divides the rank by 1 + the logarithm of the number of unique words in document
  #   32 divides the rank by itself + 1
  # The integer option controls several behaviors, so it is a bit mask: you can specify one or more behaviors
  #
  # pkg:gem/pg_search#lib/pg_search/features/tsearch.rb:155
  def normalization; end

  # pkg:gem/pg_search#lib/pg_search/features/tsearch.rb:29
  def ts_headline; end

  # pkg:gem/pg_search#lib/pg_search/features/tsearch.rb:79
  def ts_headline_option_value(value); end

  # pkg:gem/pg_search#lib/pg_search/features/tsearch.rb:38
  def ts_headline_options; end

  # pkg:gem/pg_search#lib/pg_search/features/tsearch.rb:131
  def tsdocument; end

  # pkg:gem/pg_search#lib/pg_search/features/tsearch.rb:159
  def tsearch_rank; end

  # pkg:gem/pg_search#lib/pg_search/features/tsearch.rb:123
  def tsquery; end

  # After this, the SQL expression evaluates to a string containing the term surrounded by single-quotes.
  # If :prefix is true, then the term will have :* appended to the end.
  # If :negated is true, then the term will have ! prepended to the front.
  #
  # pkg:gem/pg_search#lib/pg_search/features/tsearch.rb:109
  def tsquery_expression(term_node, negated:, prefix:); end

  # standard:disable Lint/UselessConstantScoping
  #
  # pkg:gem/pg_search#lib/pg_search/features/tsearch.rb:93
  def tsquery_for_term(unsanitized_term); end

  class << self
    # pkg:gem/pg_search#lib/pg_search/features/tsearch.rb:9
    def valid_options; end
  end
end

# pkg:gem/pg_search#lib/pg_search/features/tsearch.rb:92
PgSearch::Features::TSearch::DISALLOWED_TSQUERY_CHARACTERS = T.let(T.unsafe(nil), Regexp)

# pkg:gem/pg_search#lib/pg_search/features/trigram.rb:5
class PgSearch::Features::Trigram < ::PgSearch::Features::Feature
  # pkg:gem/pg_search#lib/pg_search/features/trigram.rb:10
  def conditions; end

  # pkg:gem/pg_search#lib/pg_search/features/trigram.rb:26
  def rank; end

  private

  # pkg:gem/pg_search#lib/pg_search/features/trigram.rb:38
  def infix_operator; end

  # pkg:gem/pg_search#lib/pg_search/features/trigram.rb:49
  def normalized_document; end

  # pkg:gem/pg_search#lib/pg_search/features/trigram.rb:53
  def normalized_query; end

  # pkg:gem/pg_search#lib/pg_search/features/trigram.rb:42
  def similarity; end

  # pkg:gem/pg_search#lib/pg_search/features/trigram.rb:34
  def similarity_function; end

  # pkg:gem/pg_search#lib/pg_search/features/trigram.rb:32
  def word_similarity?; end

  class << self
    # pkg:gem/pg_search#lib/pg_search/features/trigram.rb:6
    def valid_options; end
  end
end

# pkg:gem/pg_search#lib/pg_search/model.rb:4
module PgSearch::Model
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::PgSearch::Model::ClassMethods

  # pkg:gem/pg_search#lib/pg_search/model.rb:32
  def method_missing(method, *_arg1, **_arg2); end

  private

  # pkg:gem/pg_search#lib/pg_search/model.rb:47
  def respond_to_missing?(method, *_arg1, **_arg2); end
end

# pkg:gem/pg_search#lib/pg_search/model.rb:7
module PgSearch::Model::ClassMethods
  # pkg:gem/pg_search#lib/pg_search/model.rb:24
  def multisearchable(options = T.unsafe(nil)); end

  # pkg:gem/pg_search#lib/pg_search/model.rb:8
  def pg_search_scope(name, options); end
end

# pkg:gem/pg_search#lib/pg_search/multisearch/rebuilder.rb:4
module PgSearch::Multisearch
  class << self
    # pkg:gem/pg_search#lib/pg_search/multisearch.rb:8
    def rebuild(model, deprecated_clean_up = T.unsafe(nil), clean_up: T.unsafe(nil), transactional: T.unsafe(nil)); end

    private

    # pkg:gem/pg_search#lib/pg_search/multisearch.rb:28
    def execute(model, clean_up); end
  end
end

# pkg:gem/pg_search#lib/pg_search/multisearch.rb:34
class PgSearch::Multisearch::ModelNotMultisearchable < ::StandardError
  # pkg:gem/pg_search#lib/pg_search/multisearch.rb:35
  def initialize(model_class); end

  # pkg:gem/pg_search#lib/pg_search/multisearch.rb:40
  def message; end
end

# pkg:gem/pg_search#lib/pg_search/multisearch/rebuilder.rb:5
class PgSearch::Multisearch::Rebuilder
  # Arguments
  #
  # +model+:: Active Record model configured for multisearch.
  # +time_source+:: Clock returning a timestamp for bulk inserts. Defaults to
  #                 +Time.method(:now)+ and is called once per bulk rebuild so
  #                 +created_at+ and +updated_at+ share a timestamp.
  #
  # Raises
  #
  # ModelNotMultisearchable:: If +model+ is not configured for multisearch.
  #
  # pkg:gem/pg_search#lib/pg_search/multisearch/rebuilder.rb:16
  def initialize(model, time_source = T.unsafe(nil)); end

  # Populates search documents without first clearing existing documents.
  # Uses the model's rebuild_pg_search_documents override when available;
  # otherwise updates records individually for conditions, dynamic content,
  # or additional attributes, and bulk-inserts for plain column content.
  #
  # pkg:gem/pg_search#lib/pg_search/multisearch/rebuilder.rb:27
  def rebuild; end

  private

  # pkg:gem/pg_search#lib/pg_search/multisearch/rebuilder.rb:51
  def additional_attributes?; end

  # pkg:gem/pg_search#lib/pg_search/multisearch/rebuilder.rb:102
  def apply_sti_condition(select_manager, src_table); end

  # pkg:gem/pg_search#lib/pg_search/multisearch/rebuilder.rb:100
  def columns; end

  # pkg:gem/pg_search#lib/pg_search/multisearch/rebuilder.rb:41
  def conditional?; end

  # pkg:gem/pg_search#lib/pg_search/multisearch/rebuilder.rb:55
  def connection; end

  # pkg:gem/pg_search#lib/pg_search/multisearch/rebuilder.rb:89
  def content_expression; end

  # pkg:gem/pg_search#lib/pg_search/multisearch/rebuilder.rb:46
  def dynamic?; end

  # pkg:gem/pg_search#lib/pg_search/multisearch/rebuilder.rb:59
  def insert_manager; end

  # pkg:gem/pg_search#lib/pg_search/multisearch/rebuilder.rb:39
  def model; end

  # pkg:gem/pg_search#lib/pg_search/multisearch/rebuilder.rb:57
  def rebuild_sql; end
end

# pkg:gem/pg_search#lib/pg_search/multisearchable.rb:6
module PgSearch::Multisearchable
  # pkg:gem/pg_search#lib/pg_search/multisearchable.rb:57
  def create_or_update_pg_search_document; end

  # pkg:gem/pg_search#lib/pg_search/multisearchable.rb:25
  def pg_search_document_attrs; end

  # pkg:gem/pg_search#lib/pg_search/multisearchable.rb:19
  def searchable_text; end

  # pkg:gem/pg_search#lib/pg_search/multisearchable.rb:35
  def should_update_pg_search_document?; end

  # pkg:gem/pg_search#lib/pg_search/multisearchable.rb:42
  def update_pg_search_document; end

  class << self
    # pkg:gem/pg_search#lib/pg_search/multisearchable.rb:7
    def included(mod); end
  end
end

# pkg:gem/pg_search#lib/pg_search/normalizer.rb:4
class PgSearch::Normalizer
  # Arguments
  #
  # +config+:: Search configuration whose ignore list controls accent
  #            normalization.
  #
  # pkg:gem/pg_search#lib/pg_search/normalizer.rb:9
  def initialize(config); end

  # Applies configured accent normalization, preserving the input expression
  # without an unaccent wrapper when accents are not ignored.
  #
  # Arguments
  #
  # +expression+:: An Arel node, attribute, or trusted SQL String. A String is
  #                an SQL expression, not a value to quote.
  #
  # Returns a composable Arel expression.
  #
  # Raises
  #
  # TypeError:: If +expression+ is not an Arel node, attribute, or String.
  #
  # pkg:gem/pg_search#lib/pg_search/normalizer.rb:28
  def add_normalization(expression); end

  private

  # pkg:gem/pg_search#lib/pg_search/normalizer.rb:45
  def config; end

  # pkg:gem/pg_search#lib/pg_search/normalizer.rb:47
  def to_node(expression); end
end

# pkg:gem/pg_search#lib/pg_search/normalizer.rb:13
PgSearch::Normalizer::DISALLOWED_CHARACTERS = T.let(T.unsafe(nil), String)

# pkg:gem/pg_search#lib/pg_search.rb:64
class PgSearch::PgSearchHighlightNotSelected < ::StandardError
  # pkg:gem/pg_search#lib/pg_search.rb:65
  def message; end
end

# pkg:gem/pg_search#lib/pg_search.rb:57
class PgSearch::PgSearchRankNotSelected < ::StandardError
  # pkg:gem/pg_search#lib/pg_search.rb:58
  def message; end
end

# pkg:gem/pg_search#lib/pg_search/railtie.rb:4
class PgSearch::Railtie < ::Rails::Railtie; end

# pkg:gem/pg_search#lib/pg_search/scope_options.rb:4
class PgSearch::ScopeOptions
  # pkg:gem/pg_search#lib/pg_search/scope_options.rb:7
  def initialize(config); end

  # pkg:gem/pg_search#lib/pg_search/scope_options.rb:13
  def apply(scope); end

  # pkg:gem/pg_search#lib/pg_search/scope_options.rb:5
  def config; end

  # pkg:gem/pg_search#lib/pg_search/scope_options.rb:5
  def feature_options; end

  # pkg:gem/pg_search#lib/pg_search/scope_options.rb:5
  def model; end

  private

  # pkg:gem/pg_search#lib/pg_search/scope_options.rb:89
  def conditions; end

  # pkg:gem/pg_search#lib/pg_search/scope_options.rb:120
  def feature_for(feature_name); end

  # pkg:gem/pg_search#lib/pg_search/scope_options.rb:152
  def include_table_aliasing_for_rank(scope); end

  # pkg:gem/pg_search#lib/pg_search/scope_options.rb:98
  def order_within_rank; end

  # pkg:gem/pg_search#lib/pg_search/scope_options.rb:106
  def primary_key; end

  # pkg:gem/pg_search#lib/pg_search/scope_options.rb:137
  def rank; end

  # pkg:gem/pg_search#lib/pg_search/scope_options.rb:145
  def rank_join(rank_subquery); end

  # pkg:gem/pg_search#lib/pg_search/scope_options.rb:78
  def subquery; end

  # pkg:gem/pg_search#lib/pg_search/scope_options.rb:110
  def subquery_join; end
end

# pkg:gem/pg_search#lib/pg_search/scope_options.rb:114
PgSearch::ScopeOptions::FEATURE_CLASSES = T.let(T.unsafe(nil), Hash)

# pkg:gem/pg_search#lib/pg_search/scope_options.rb:56
module PgSearch::ScopeOptions::PgSearchRankTableAliasing
  # pkg:gem/pg_search#lib/pg_search/scope_options.rb:57
  def pg_search_rank_table_alias(include_counter: T.unsafe(nil)); end

  private

  # pkg:gem/pg_search#lib/pg_search/scope_options.rb:69
  def increment_counter; end
end

# pkg:gem/pg_search#lib/pg_search/scope_options.rb:26
module PgSearch::ScopeOptions::WithPgSearchHighlight
  # pkg:gem/pg_search#lib/pg_search/scope_options.rb:35
  def tsearch; end

  # pkg:gem/pg_search#lib/pg_search/scope_options.rb:39
  def with_pg_search_highlight; end

  class << self
    # pkg:gem/pg_search#lib/pg_search/scope_options.rb:27
    def [](tsearch); end
  end
end

# pkg:gem/pg_search#lib/pg_search/scope_options.rb:46
module PgSearch::ScopeOptions::WithPgSearchRank
  # pkg:gem/pg_search#lib/pg_search/scope_options.rb:47
  def with_pg_search_rank; end
end

# pkg:gem/pg_search#lib/pg_search/version.rb:4
PgSearch::VERSION = T.let(T.unsafe(nil), String)
