# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rails_semantic_logger` gem.
# Please instead update this file by running `bin/tapioca gem rails_semantic_logger`.


# pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/extensions/action_controller/live.rb:4
module ActionController; end

# pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/extensions/action_controller/live.rb:5
module ActionController::Live
  include GeneratedInstanceMethods

  mixes_in_class_methods GeneratedClassMethods
  mixes_in_class_methods ::ActionController::Live::ClassMethods

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/extensions/action_controller/live.rb:7
  def log_error(exception); end

  module GeneratedClassMethods
    def live_streaming_excluded_keys; end
    def live_streaming_excluded_keys=(value); end
    def live_streaming_excluded_keys?; end
  end

  module GeneratedInstanceMethods; end
end

# pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/extensions/action_dispatch/debug_exceptions.rb:4
module ActionDispatch; end

# pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/extensions/action_dispatch/debug_exceptions.rb:5
class ActionDispatch::DebugExceptions
  private

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/extensions/action_dispatch/debug_exceptions.rb:9
  def log_error(request, wrapper); end
end

# pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/extensions/action_view/streaming_template_renderer.rb:4
module ActionView; end

# pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/extensions/action_view/streaming_template_renderer.rb:5
class ActionView::StreamingTemplateRenderer < ::ActionView::TemplateRenderer; end

# pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/extensions/action_view/streaming_template_renderer.rb:6
class ActionView::StreamingTemplateRenderer::Body
  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/extensions/action_view/streaming_template_renderer.rb:10
  def log_error(exception); end
end

# pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/extensions/active_job/logging.rb:4
module ActiveJob
  extend ::ActiveJob::EnqueueAfterTransactionCommit::ActiveJobMethods
end

# pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/extensions/active_job/logging.rb:5
module ActiveJob::Logging
  include ::SemanticLogger::Loggable
  extend ::SemanticLogger::Loggable::ClassMethods
  include GeneratedInstanceMethods

  mixes_in_class_methods GeneratedClassMethods
  mixes_in_class_methods ::SemanticLogger::Loggable::ClassMethods

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/extensions/active_job/logging.rb:6
  def logger; end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/extensions/active_job/logging.rb:6
  def logger=(logger); end

  private

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/extensions/active_job/logging.rb:11
  def tag_logger(*tags, &_arg1); end

  class << self
    # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/extensions/active_job/logging.rb:6
    def logger; end

    # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/extensions/active_job/logging.rb:6
    def logger=(logger); end
  end

  module GeneratedClassMethods
    def log_arguments; end
    def log_arguments=(value); end
    def log_arguments?; end
  end

  module GeneratedInstanceMethods; end
end

# pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/extensions/active_support/logger.rb:3
module ActiveSupport; end

# More hacks to try and stop Rails from being its own worst enemy.
#
# pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/extensions/active_support/logger.rb:5
class ActiveSupport::Logger < ::Logger
  class << self
    # Keep a handle on the genuine constructor so that callers which supply a
    # real log destination still get a real logger (see #new below).
    #
    # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/extensions/active_support/logger.rb:9
    def _semantic_logger_original_new(*_arg0); end

    # Prevent Rails from trying to merge/broadcast loggers (e.g. ActiveRecord's
    # `console` hook and `rails server`'s log_to_stdout). SemanticLogger already
    # multiplexes through its own appenders, and SemanticLogger::Logger does not
    # implement #broadcast_to, so the merge path would otherwise raise.
    #
    # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/extensions/active_support/logger.rb:17
    def logger_outputs_to?(*_args); end

    # Historically every `ActiveSupport::Logger.new(...)` call was redirected to
    # SemanticLogger, silently discarding the requested destination. That broke
    # third-party callers such as Webpacker's `ActiveSupport::Logger.new(STDOUT)`,
    # whose output never reached STDOUT (issue #141). Only redirect to
    # SemanticLogger when no destination is supplied; otherwise honor the caller
    # and build a genuine logger pointed at the requested destination.
    #
    # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/extensions/active_support/logger.rb:27
    def new(*args, **kwargs); end
  end
end

# This subscriber is a reimplementation of Rails' own ActionController::LogSubscriber that emits
# structured (message + payload) log entries instead of formatted text. When Rails changes its
# subscriber, those changes must be brought across here. Compare against the upstream source for
# each supported Rails version:
#
#   Rails 8.1: https://github.com/rails/rails/blob/8-1-stable/actionpack/lib/action_controller/log_subscriber.rb
#   Rails 8.0: https://github.com/rails/rails/blob/8-0-stable/actionpack/lib/action_controller/log_subscriber.rb
#   Rails 7.2: https://github.com/rails/rails/blob/7-2-stable/actionpack/lib/action_controller/log_subscriber.rb
#
# This subscriber is a reimplementation of Rails' own ActionMailer::LogSubscriber that emits
# structured (message + payload) log entries instead of formatted text. When Rails changes its
# subscriber, those changes must be brought across here. Compare against the upstream source for
# each supported Rails version:
#
#   Rails 8.1: https://github.com/rails/rails/blob/8-1-stable/actionmailer/lib/action_mailer/log_subscriber.rb
#   Rails 8.0: https://github.com/rails/rails/blob/8-0-stable/actionmailer/lib/action_mailer/log_subscriber.rb
#   Rails 7.2: https://github.com/rails/rails/blob/7-2-stable/actionmailer/lib/action_mailer/log_subscriber.rb
#
# This subscriber is a reimplementation of Rails' own ActionView::LogSubscriber that emits
# structured (message + payload) log entries instead of formatted text. When Rails changes its
# subscriber, those changes must be brought across here. Compare against the upstream source for
# each supported Rails version:
#
#   Rails 8.1: https://github.com/rails/rails/blob/8-1-stable/actionview/lib/action_view/log_subscriber.rb
#   Rails 8.0: https://github.com/rails/rails/blob/8-0-stable/actionview/lib/action_view/log_subscriber.rb
#   Rails 7.2: https://github.com/rails/rails/blob/7-2-stable/actionview/lib/action_view/log_subscriber.rb
#
# As of these versions the upstream subscriber is identical across 7.2, 8.0, and 8.1, so no
# version-specific behavior is required here.
#
# This subscriber is a reimplementation of Rails' own ActiveJob::LogSubscriber that emits
# structured (message + payload) log entries instead of formatted text. When Rails changes its
# subscriber, those changes must be brought across here. Compare against the upstream source for
# each supported Rails version:
#
#   Rails 8.1: https://github.com/rails/rails/blob/8-1-stable/activejob/lib/active_job/log_subscriber.rb
#   Rails 8.0: https://github.com/rails/rails/blob/8-0-stable/activejob/lib/active_job/log_subscriber.rb
#   Rails 7.2: https://github.com/rails/rails/blob/7-2-stable/activejob/lib/active_job/log_subscriber.rb
#
# Event coverage by Rails version:
#   7.2 / 8.0: enqueue, enqueue_at, enqueue_all, perform_start, perform,
#              enqueue_retry, retry_stopped, discard
#   8.1 adds (ActiveJob Continuations): interrupt, resume, step_skipped, step_started, step
#
# The Continuation handlers are defined unconditionally. On Rails < 8.1 those notifications are
# never emitted, so the extra methods are simply never invoked.
#
# This subscriber is a reimplementation of Rails' own ActiveRecord::LogSubscriber that emits
# structured (message + payload) log entries instead of formatted text. When Rails changes its
# subscriber, those changes must be brought across here. Compare against the upstream source for
# each supported Rails version:
#
#   Rails 8.1: https://github.com/rails/rails/blob/8-1-stable/activerecord/lib/active_record/log_subscriber.rb
#   Rails 8.0: https://github.com/rails/rails/blob/8-0-stable/activerecord/lib/active_record/log_subscriber.rb
#   Rails 7.2: https://github.com/rails/rails/blob/7-2-stable/activerecord/lib/active_record/log_subscriber.rb
#
# The upstream subscriber is functionally identical across Rails 7.2, 8.0, and 8.1 for everything
# that affects structured output. The only differences between those versions are in the internal
# `query_source_location` helper (used by `verbose_query_logs` to print the "↳ source" line) and a
# behavior is required here.
#
# As of Rails 8.1 there is also a parallel ActiveRecord::StructuredEventSubscriber (it emits
# structured events to Rails.event rather than text to Rails.logger). It is the authoritative,
# Rails-maintained reference for field names and payload shape; the fields below (e.g. :lock_wait
# and the strict_loading_violation payload) follow it. We do not use it (see CLAUDE.md), but diff
# against it when adding fields:
#
#   Rails 8.1: https://github.com/rails/rails/blob/8-1-stable/activerecord/lib/active_record/structured_event_subscriber.rb
# Upstream source (identical across supported versions, only the namespace differs):
#   https://github.com/rails/rails/blob/v7.2.2/actioncable/lib/action_cable/connection/tagged_logger_proxy.rb
#   https://github.com/rails/rails/blob/v8.0.2/actioncable/lib/action_cable/connection/tagged_logger_proxy.rb
#   https://github.com/rails/rails/blob/v8.1.3/actioncable/lib/action_cable/connection/tagged_logger_proxy.rb
#   https://github.com/rails/rails/blob/main/actioncable/lib/action_cable/server/tagged_logger_proxy.rb
#
# pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/options.rb:1
module RailsSemanticLogger
  class << self
    # Create each appender declared via `config.rails_semantic_logger.appenders`.
    # The first file appender (if any) becomes the internal logger, so that any
    # failures writing to other appenders are still recorded somewhere durable.
    #
    # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger.rb:108
    def add_appenders(appenders); end

    # Console (REPL) counterpart of .add_server_appenders, used by the `rails console`
    # hook. When the application declared its own appenders, its `add_console`
    # declarations apply; otherwise the deprecated `console_logger` toggle decides
    # whether the default stderr console appender is added.
    #
    # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger.rb:93
    def add_console_appenders; end

    # Create the appenders declared via `config.rails_semantic_logger.appenders` with
    # `add_server` (or the default console appender when the application declared no
    # appenders of its own).
    #
    # Called automatically for the server contexts that have a first-party hook
    # (`rails server`, Sidekiq in server mode). App servers without such a hook (bare
    # puma, rackup, Passenger, Unicorn) cannot be detected reliably, so call this from
    # the server's own definitive boot hook instead of relying on a guess. Example,
    # in `config/puma.rb`:
    #
    #   on_booted { RailsSemanticLogger.add_server_appenders }
    #
    # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger.rb:77
    def add_server_appenders; end

    # Deprecator used for options that are being phased out in favor of declaring
    # appenders directly (see RailsSemanticLogger::Appenders).
    #
    # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger.rb:45
    def deprecator; end

    # Swap an existing subscriber with a new one
    #
    # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger.rb:118
    def swap_subscriber(old_class, new_class, notifier); end

    # Warn that a setting was changed too late to take effect, so the change has no
    # effect. When `config_initializers_too_late` is true (the default), the setting
    # is consumed while the logger is built, *before* `config/initializers/*` is
    # loaded, so that location is called out as too late. When false, the setting is
    # consumed at the end of initialization (`config/initializers/*` still works) and
    # only a change after the application has booted is too late.
    #
    # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger.rb:55
    def warn_initialized_too_late(setting, config_initializers_too_late: T.unsafe(nil)); end

    private

    # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger.rb:141
    def listeners_for(notifier, pattern); end

    # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger.rb:137
    def subscriber_patterns(subscriber); end

    # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger.rb:125
    def unattach(subscriber); end
  end
end

# pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/extensions/action_cable/tagged_logger_proxy.rb:7
module RailsSemanticLogger::ActionCable; end

# Rails 8.2 moved the proxy from ActionCable::Connection to ActionCable::Server, as part of
# the ActionCable::Server::Socket refactor, without leaving a back-compat alias behind.
# Resolve whichever constant this version of ActionCable ships rather than hard-coding a
# namespace, so that a `require` of the old path cannot fail the app's boot. See #326.
#
# pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/extensions/action_cable/tagged_logger_proxy.rb:12
RailsSemanticLogger::ActionCable::TaggedLoggerProxy = ActionCable::Connection::TaggedLoggerProxy

# pkg:gem/rails_semantic_logger#lib/rails_semantic_logger.rb:6
module RailsSemanticLogger::ActionController; end

# pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_controller/log_subscriber.rb:12
class RailsSemanticLogger::ActionController::LogSubscriber < ::ActiveSupport::LogSubscriber
  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_controller/log_subscriber.rb:15
  def backtrace_cleaner; end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_controller/log_subscriber.rb:15
  def backtrace_cleaner=(_arg0); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_controller/log_subscriber.rb:15
  def backtrace_cleaner?; end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_controller/log_subscriber.rb:167
  def exist_fragment?(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_controller/log_subscriber.rb:167
  def expire_fragment(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_controller/log_subscriber.rb:167
  def expire_page(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_controller/log_subscriber.rb:94
  def halted_callback(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_controller/log_subscriber.rb:29
  def process_action(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_controller/log_subscriber.rb:167
  def read_fragment(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_controller/log_subscriber.rb:130
  def redirect_to(event); end

  # Rails 8.1+ emits this event when an exception is handled by a `rescue_from` callback.
  # On earlier Rails versions the event is never instrumented, so this handler is dormant.
  #
  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_controller/log_subscriber.rb:105
  def rescue_from_callback(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_controller/log_subscriber.rb:144
  def send_data(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_controller/log_subscriber.rb:123
  def send_file(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_controller/log_subscriber.rb:25
  def start_processing(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_controller/log_subscriber.rb:151
  def unpermitted_parameters(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_controller/log_subscriber.rb:167
  def write_fragment(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_controller/log_subscriber.rb:167
  def write_page(event); end

  private

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_controller/log_subscriber.rb:201
  def action_message(message, payload); end

  # Returns the logger for the supplied event.
  # Returns ActionController::Base.logger if no controller is present
  #
  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_controller/log_subscriber.rb:182
  def controller_logger(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_controller/log_subscriber.rb:191
  def extract_path(path); end

  # Rails 8.1+ BacktraceCleaner exposes #first_clean_frame for verbose redirect logging.
  #
  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_controller/log_subscriber.rb:197
  def redirect_source_location; end

  class << self
    # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_controller/log_subscriber.rb:18
    def action_message_format; end

    # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_controller/log_subscriber.rb:18
    def action_message_format=(_arg0); end

    # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_controller/log_subscriber.rb:15
    def backtrace_cleaner; end

    # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_controller/log_subscriber.rb:15
    def backtrace_cleaner=(value); end

    # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_controller/log_subscriber.rb:15
    def backtrace_cleaner?; end

    # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_controller/log_subscriber.rb:18
    def processing_log_level; end

    # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_controller/log_subscriber.rb:18
    def processing_log_level=(_arg0); end

    private

    # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_controller/log_subscriber.rb:15
    def __class_attr_backtrace_cleaner; end

    # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_controller/log_subscriber.rb:15
    def __class_attr_backtrace_cleaner=(new_value); end
  end
end

# pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_controller/log_subscriber.rb:13
RailsSemanticLogger::ActionController::LogSubscriber::INTERNAL_PARAMS = T.let(T.unsafe(nil), Array)

# pkg:gem/rails_semantic_logger#lib/rails_semantic_logger.rb:10
module RailsSemanticLogger::ActionMailer; end

# pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_mailer/log_subscriber.rb:15
class RailsSemanticLogger::ActionMailer::LogSubscriber < ::ActiveSupport::LogSubscriber
  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_mailer/log_subscriber.rb:16
  def deliver(event); end

  # An email was generated.
  #
  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_mailer/log_subscriber.rb:46
  def process(event); end

  private

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_mailer/log_subscriber.rb:133
  def log_with_formatter(level: T.unsafe(nil), **kw_args); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_mailer/log_subscriber.rb:142
  def logger; end
end

# pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_mailer/log_subscriber.rb:61
class RailsSemanticLogger::ActionMailer::LogSubscriber::EventFormatter
  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_mailer/log_subscriber.rb:62
  def initialize(event:, log_duration: T.unsafe(nil)); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_mailer/log_subscriber.rb:89
  def date; end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_mailer/log_subscriber.rb:67
  def payload; end

  private

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_mailer/log_subscriber.rb:101
  def action; end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_mailer/log_subscriber.rb:95
  def event; end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_mailer/log_subscriber.rb:111
  def format(arg); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_mailer/log_subscriber.rb:105
  def formatted_args; end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_mailer/log_subscriber.rb:128
  def log_duration?; end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_mailer/log_subscriber.rb:97
  def mailer; end
end

# pkg:gem/rails_semantic_logger#lib/rails_semantic_logger.rb:14
module RailsSemanticLogger::ActionView; end

# Output Semantic logs from Action View.
#
# pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_view/log_subscriber.rb:18
class RailsSemanticLogger::ActionView::LogSubscriber < ::ActiveSupport::LogSubscriber
  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_view/log_subscriber.rb:26
  def initialize; end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_view/log_subscriber.rb:88
  def render_collection(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_view/log_subscriber.rb:70
  def render_layout(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_view/log_subscriber.rb:50
  def render_partial(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_view/log_subscriber.rb:31
  def render_template(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_view/log_subscriber.rb:110
  def start(name, id, payload); end

  private

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_view/log_subscriber.rb:175
  def from_rails_root(string); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_view/log_subscriber.rb:185
  def logger; end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_view/log_subscriber.rb:181
  def rails_root; end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_view/log_subscriber.rb:171
  def should_log?; end

  class << self
    # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_view/log_subscriber.rb:153
    def attach_to(*_arg0); end

    # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_view/log_subscriber.rb:22
    def logger; end

    # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_view/log_subscriber.rb:23
    def rendered_log_level; end

    # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_view/log_subscriber.rb:23
    def rendered_log_level=(_arg0); end
  end
end

# pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_view/log_subscriber.rb:164
RailsSemanticLogger::ActionView::LogSubscriber::EMPTY = T.let(T.unsafe(nil), String)

# pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_view/log_subscriber.rb:122
class RailsSemanticLogger::ActionView::LogSubscriber::Start
  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_view/log_subscriber.rb:133
  def finish(name, id, payload); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_view/log_subscriber.rb:123
  def start(name, _id, payload); end

  private

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_view/log_subscriber.rb:138
  def from_rails_root(string); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_view/log_subscriber.rb:148
  def logger; end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_view/log_subscriber.rb:144
  def rails_root; end
end

# pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/action_view/log_subscriber.rb:19
RailsSemanticLogger::ActionView::LogSubscriber::VIEWS_PATTERN = T.let(T.unsafe(nil), Regexp)

# pkg:gem/rails_semantic_logger#lib/rails_semantic_logger.rb:18
module RailsSemanticLogger::ActiveJob; end

# pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/active_job/log_subscriber.rb:22
class RailsSemanticLogger::ActiveJob::LogSubscriber < ::ActiveSupport::LogSubscriber
  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/active_job/log_subscriber.rb:121
  def discard(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/active_job/log_subscriber.rb:23
  def enqueue(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/active_job/log_subscriber.rb:217
  def enqueue_all(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/active_job/log_subscriber.rb:44
  def enqueue_at(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/active_job/log_subscriber.rb:92
  def enqueue_retry(event); end

  # ActiveJob Continuations (Rails 8.1+)
  #
  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/active_job/log_subscriber.rb:134
  def interrupt(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/active_job/log_subscriber.rb:71
  def perform(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/active_job/log_subscriber.rb:65
  def perform_start(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/active_job/log_subscriber.rb:146
  def resume(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/active_job/log_subscriber.rb:108
  def retry_stopped(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/active_job/log_subscriber.rb:186
  def step(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/active_job/log_subscriber.rb:157
  def step_skipped(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/active_job/log_subscriber.rb:168
  def step_started(event); end

  private

  # Upstream records an enqueue failure either via the event's exception_object or via
  # ActiveJob's job.enqueue_error. Prefer the former, fall back to the latter.
  #
  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/active_job/log_subscriber.rb:251
  def enqueue_error(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/active_job/log_subscriber.rb:256
  def enqueued_jobs_message(adapter_name, enqueued_jobs); end

  # Builds the structured log entry for an event. The block is given an EventFormatter and
  # returns a hash with :message, an optional :exception, and an optional :payload of extra
  # fields. Those extra fields are merged on top of the formatter's standard payload, so
  # handlers can add event-specific keys (executions, wait, step_name, ...) without each
  # having to rebuild the common job payload.
  #
  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/active_job/log_subscriber.rb:352
  def log_with_formatter(level: T.unsafe(nil), **kw_args); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/active_job/log_subscriber.rb:362
  def logger; end
end

# pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/active_job/log_subscriber.rb:263
class RailsSemanticLogger::ActiveJob::LogSubscriber::EventFormatter
  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/active_job/log_subscriber.rb:264
  def initialize(event:, log_duration: T.unsafe(nil)); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/active_job/log_subscriber.rb:299
  def executions; end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/active_job/log_subscriber.rb:269
  def job_info; end

  # Standard payload shared by every event. enqueued_at, scheduled_at, and duration are
  # only present when applicable (the job was scheduled, has been enqueued, or the event
  # carries a duration), so that handlers that do not have them never emit blank keys.
  #
  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/active_job/log_subscriber.rb:276
  def payload; end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/active_job/log_subscriber.rb:291
  def queue_name; end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/active_job/log_subscriber.rb:295
  def scheduled_at; end

  private

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/active_job/log_subscriber.rb:311
  def adapter_name; end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/active_job/log_subscriber.rb:305
  def event; end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/active_job/log_subscriber.rb:323
  def format(arg); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/active_job/log_subscriber.rb:315
  def formatted_args; end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/active_job/log_subscriber.rb:307
  def job; end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/active_job/log_subscriber.rb:342
  def log_duration?; end
end

# pkg:gem/rails_semantic_logger#lib/rails_semantic_logger.rb:22
module RailsSemanticLogger::ActiveRecord; end

# pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/active_record/log_subscriber.rb:25
class RailsSemanticLogger::ActiveRecord::LogSubscriber < ::ActiveSupport::LogSubscriber
  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/active_record/log_subscriber.rb:44
  def sql(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/active_record/log_subscriber.rb:28
  def strict_loading_violation(event); end

  private

  # When multiple values are received for a single bound field, it is converted into an array
  #
  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/active_record/log_subscriber.rb:77
  def add_bind_value(binds, key, value); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/active_record/log_subscriber.rb:99
  def attribute_name(attr, index); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/active_record/log_subscriber.rb:88
  def bind_values(payload); end

  # Filter sensitive bind values using the same parameter filter Rails uses for ActiveRecord,
  # which is derived from ActiveRecord::Base.filter_attributes (config.filter_parameters).
  #
  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/active_record/log_subscriber.rb:122
  def filter(name, value); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/active_record/log_subscriber.rb:84
  def logger; end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/active_record/log_subscriber.rb:107
  def render_bind(attr, value); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/active_record/log_subscriber.rb:131
  def type_casted_binds(casted_binds); end
end

# pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/active_record/log_subscriber.rb:26
RailsSemanticLogger::ActiveRecord::LogSubscriber::IGNORE_PAYLOAD_NAMES = T.let(T.unsafe(nil), Array)

# Collects the appenders declared by the application via:
#
#   config.rails_semantic_logger.appenders do |appenders|
#     appenders.add(file_name: "log/#{Rails.env}.log", formatter: :json)
#     appenders.add_server(io: $stdout, formatter: :color)
#     appenders.add_console(io: $stderr, formatter: :color)
#   end
#
# When at least one appender is declared this way, Rails Semantic Logger stops
# building its own default file appender (`format`, `ap_options`, `filter`, and
# `add_file_appender` no longer apply) and instead creates exactly the appenders
# declared here.
#
# The methods name the *context* in which the appender is created; the
# destination and formatting are ordinary `SemanticLogger.add_appender` arguments:
#
#   #add         - always created, during Rails initialization.
#   #add_server  - created only when serving requests (`rails server`, Sidekiq
#                  in server mode). Defaults to `$stdout`.
#   #add_console - created only inside a `rails console` session. Defaults to
#                  `$stderr` so log output does not tangle with command results.
#
# Because each call appends to its context, any appender works in any context,
# and a context can have several (e.g. a server-only stdout *and* file appender).
#
# pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/appenders.rb:26
class RailsSemanticLogger::Appenders
  include ::Enumerable

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/appenders.rb:33
  def initialize; end

  # Declare an appender. Accepts the same arguments (and optional block) as
  # SemanticLogger.add_appender. Returns self so calls can be chained.
  #
  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/appenders.rb:41
  def add(**args, &block); end

  # Declare an appender that is only created when running inside a `rails console`
  # session. Identical to #add_server except it defaults to `$stderr`.
  #
  # Accepts the same arguments (and optional block) as SemanticLogger.add_appender.
  #
  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/appenders.rb:64
  def add_console(**args, &block); end

  # Declare an appender that is only created when the application is serving
  # requests: `rails server`, Sidekiq in server mode, or when the app calls
  # RailsSemanticLogger.add_server_appenders from its own server's boot hook.
  # It is never created during a non-serving boot (rake tasks, runners,
  # generators), so it only appears where it is useful.
  #
  # Accepts the same arguments (and optional block) as SemanticLogger.add_appender.
  # When no destination is given it defaults to `$stdout`; the formatter defaults
  # to `:color`.
  #
  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/appenders.rb:55
  def add_server(**args, &block); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/appenders.rb:78
  def any?; end

  # The appenders declared via #add_server / #add_console, each as
  # [Hash args, Proc|nil block].
  #
  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/appenders.rb:71
  def console; end

  # Yields each #add declaration as [Hash args, Proc|nil block].
  #
  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/appenders.rb:74
  def each(&_arg0); end

  # The appenders declared via #add_server / #add_console, each as
  # [Hash args, Proc|nil block].
  #
  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/appenders.rb:71
  def server; end

  private

  # Apply the context default stream and formatter, without overriding a
  # destination (io/file_name/...) the caller already supplied.
  #
  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/appenders.rb:86
  def defaults(args, io:); end
end

# Destination keys understood by SemanticLogger.add_appender. When none is
# supplied to #add_server / #add_console, the context's default stream is used.
#
# pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/appenders.rb:31
RailsSemanticLogger::Appenders::DESTINATIONS = T.let(T.unsafe(nil), Array)

# pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/engine.rb:5
class RailsSemanticLogger::Engine < ::Rails::Engine; end

# Options for controlling Rails Semantic Logger behavior
#
# * Convert Action Controller and Active Record text messages to semantic data
#
#     Rails -- Started -- { :ip => "127.0.0.1", :method => "GET", :path => "/dashboards/inquiry_recent_activity" }
#     UserController -- Completed #index -- { :action => "index", :db_runtime => 54.64, :format => "HTML", :method => "GET", :mongo_runtime => 0.0, :path => "/users", :status => 200, :status_message => "OK", :view_runtime => 709.88 }
#
#     config.rails_semantic_logger.semantic = true
#
# * Change Rack started message to debug so that it does not appear in production
#
#     config.rails_semantic_logger.started = false
#
# * Change Processing message to debug so that it does not appear in production
#
#     config.rails_semantic_logger.processing = false
#
# * Change Action View render log messages to debug so that they do not appear in production
#
#     ActionView::Base --   Rendered data/search/_user.html.haml (46.7ms)
#
#     config.rails_semantic_logger.rendered = false
#
# * Override the Amazing Print options for logging Hash data as text:
#
#     Any valid Amazing Print option for rendering data.
#     The defaults can changed be creating a `~/.aprc` file.
#     See: https://github.com/amazing-print/amazing_print
#
#     Note: The option :multiline is set to false if not supplied.
#     Note: Has no effect if Amazing Print is not installed.
#
#        config.rails_semantic_logger.ap_options = {multiline: false}
#
# * Whether to automatically add an environment specific log file appender.
#     For Example: 'log/development.log'
#
#     Note:
#       When Semantic Logger fails to log to an appender it logs the error to an
#       internal logger, which by default writes to STDERR.
#       Example, change the default internal logger to log to stdout:
#         SemanticLogger::Processor.logger = SemanticLogger::Appender::IO.new($stdout, level: :warn)
#
#       config.rails_semantic_logger.add_file_appender = true
#
#   DEPRECATED: declare appenders via #appenders instead. Declaring any appender there already
#   replaces the default file appender, so this flag is no longer needed:
#     config.rails_semantic_logger.appenders { |appenders| appenders.add(file_name: ...) }
#
# * Silence asset logging
#
#     config.rails_semantic_logger.quiet_assets = false
#
# * Disable automatic logging to stderr when running a Rails console.
#
#     config.rails_semantic_logger.console_logger = false
#
#   DEPRECATED: declare a console appender explicitly via #appenders instead, or
#   declare none to disable it:
#     config.rails_semantic_logger.appenders { |appenders| appenders.add_console(...) }
#
# * Override the output format for the primary Rails log file.
#
#     Valid options:
#     * :default
#         Plain text output with no color.
#     * :color
#         Plain text output with color.
#     * :json
#         JSON output format.
#     * class
#
#     * Proc
#         A block that will be called to format the output.
#         It is supplied with the `log` entry and should return the formatted data.
#
#     Note:
#     * `:default` is automatically changed to `:color` if `config.colorize_logging` is `true`.
#
#     JSON Example, in `application.rb`:
#        config.rails_semantic_logger.format = :json
#
#     Custom Example, create `app/lib/my_formatter.rb`:
#
#       # My Custom colorized formatter
#       class MyFormatter < SemanticLogger::Formatters::Color
#         # Return the complete log level name in uppercase
#         def level
#           "#{color}log.level.upcase#{color_map.clear}"
#         end
#       end
#
#      # In application.rb:
#      config.rails_semantic_logger.format = MyFormatter.new
#
#
#      config.rails_semantic_logger.format = :default
#
# * Add a filter to the file logger [Regexp|Proc]
#   RegExp: Only include log messages where the class name matches the supplied
#           regular expression. All other messages will be ignored.
#   Proc: Only include log messages where the supplied Proc returns true.
#         The Proc must return true or false.
#
#     config.rails_semantic_logger.filter = nil
#
# * Change the message format of Action Controller action.
#   A block that will be called to format the message.
#   It is supplied with the `message` and `payload` and should return the formatted data.
#
#     config.rails_semantic_logger.action_message_format = -> (message, payload) do
#       "#{message} - #{payload[:controller]}##{payload[:action]}"
#     end
#
# * Do not replace the Sidekiq logger with a Semantic Logger logger.
#
#     config.rails_semantic_logger.replace_sidekiq_logger = false
#
# * Do not replace the SolidQueue logger / log subscriber.
#
#     config.rails_semantic_logger.replace_solid_queue_logger = false
#
# pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/options.rb:125
class RailsSemanticLogger::Options
  # Setup default values
  #
  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/options.rb:156
  def initialize; end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/options.rb:136
  def action_message_format; end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/options.rb:149
  def action_message_format=(value); end

  # DEPRECATED: configure these on the appender instead, via #appenders.
  #
  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/options.rb:139
  def add_file_appender; end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/options.rb:253
  def add_file_appender=(value); end

  # DEPRECATED: configure these on the appender instead, via #appenders.
  #
  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/options.rb:139
  def ap_options; end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/options.rb:230
  def ap_options=(value); end

  # Declare the appenders for Rails Semantic Logger to create, replacing the
  # default file appender:
  #
  #   config.rails_semantic_logger.appenders do |appenders|
  #     appenders.add(file_name: "log/#{Rails.env}.log", formatter: :json)
  #     appenders.add_server(io: $stdout, formatter: :color)
  #     appenders.add_console(io: $stderr, formatter: :color)
  #   end
  #
  # The method names the context in which the appender is created; the destination
  # is an ordinary `SemanticLogger.add_appender` argument. Use `add` for an
  # appender that is always created, `add_server` for one created only when serving
  # requests (`rails server`, Sidekiq in server mode; defaults to
  # `$stdout`), and `add_console` for one created only inside a `rails console`
  # session (defaults to `$stderr`). Any appender works in any context, so a
  # context may declare several (e.g. a server-only stdout and file appender).
  #
  # `add_server` appenders are created automatically under `rails server` and
  # Sidekiq in server mode. App servers without a first-party hook (bare puma,
  # rackup, Passenger, Unicorn) are not detected; create them from the server's
  # own boot hook instead, e.g. in `config/puma.rb`:
  #
  #   on_booted { RailsSemanticLogger.add_server_appenders }
  #
  # Returns the underlying RailsSemanticLogger::Appenders collection. When at
  # least one appender has been declared, the default file appender (and the
  # `format`, `ap_options`, `filter`, and `add_file_appender` options) is no
  # longer used.
  #
  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/options.rb:200
  def appenders; end

  # Whether the application declared its own appenders via #appenders.
  #
  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/options.rb:210
  def appenders?; end

  # DEPRECATED: configure these on the appender instead, via #appenders.
  #
  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/options.rb:139
  def console_logger; end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/options.rb:248
  def console_logger=(value); end

  # DEPRECATED: configure these on the appender instead, via #appenders.
  #
  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/options.rb:139
  def filter; end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/options.rb:242
  def filter=(value); end

  # Emit the deprecation warnings recorded by the deprecated appender option
  # setters, and warn immediately from any later call. Called by the engine once
  # Rails has applied the application's deprecation configuration.
  #
  # The deprecated options are documented to be set in `config/application.rb` or
  # `config/environments/*.rb`, which Rails reads in `load_environment_config`,
  # long before `active_support.deprecation_behavior` applies
  # `config.active_support.report_deprecations`, `config.active_support.deprecation`,
  # and any per-deprecator settings. Warning from the setter itself would therefore
  # land in a window where nothing the application configures can reach it. The
  # setters record instead, and this flushes once the settings are in place.
  #
  # Each option is reported once, attributed to the first place it was set, so an
  # application setting several deprecated options gets one warning per option
  # rather than one per assignment.
  #
  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/options.rb:274
  def flush_deprecations!; end

  # DEPRECATED: configure these on the appender instead, via #appenders.
  #
  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/options.rb:139
  def format; end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/options.rb:236
  def format=(value); end

  # Marks that Rails has finished initializing the application (the engine's
  # `config.after_initialize` has run). Called by the engine. After this point,
  # the POST_INIT_SETTINGS have already been consumed, so changing them warns.
  #
  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/options.rb:226
  def fully_initialized!; end

  # Marks that Rails Semantic Logger has already built its logger and the
  # init-time appenders. Called by the engine at the end of the
  # `:initialize_logger` initializer. After this point, settings that are only
  # read while building those appenders no longer have any effect, so changing
  # them emits a warning (see #warn_if_logger_initialized).
  #
  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/options.rb:219
  def logger_initialized!; end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/options.rb:136
  def processing; end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/options.rb:149
  def processing=(value); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/options.rb:136
  def quiet_assets; end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/options.rb:149
  def quiet_assets=(value); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/options.rb:136
  def rendered; end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/options.rb:149
  def rendered=(value); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/options.rb:136
  def replace_sidekiq_logger; end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/options.rb:142
  def replace_sidekiq_logger=(value); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/options.rb:136
  def replace_solid_queue_logger; end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/options.rb:142
  def replace_solid_queue_logger=(value); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/options.rb:136
  def semantic; end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/options.rb:142
  def semantic=(value); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/options.rb:136
  def started; end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/options.rb:149
  def started=(value); end

  private

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/options.rb:284
  def deprecate_appender_option(option, via: T.unsafe(nil)); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/options.rb:307
  def deprecations_flushed?; end

  # Deprecations recorded before Rails applied its deprecation configuration,
  # keyed by option so that each is reported only once. See #flush_deprecations!.
  #
  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/options.rb:303
  def pending_deprecations; end

  # Warn when a setting consumed at the end of Rails initialization is changed
  # after the application has already booted. Unlike #warn_if_logger_initialized,
  # `config/initializers/*` is *not* too late for these, so it is not suggested.
  #
  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/options.rb:324
  def warn_if_fully_initialized(setting); end

  # Warn when an init-time setting is changed after the logger and its
  # appenders have already been built. This is the classic footgun of putting
  # logger configuration in `config/initializers/*`, which Rails loads *after*
  # the logger is initialized, so the change silently has no effect.
  #
  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/options.rb:315
  def warn_if_logger_initialized(setting); end
end

# Settings consumed while the logger itself is built, during Rails'
# `:initialize_logger` initializer. Changing them after that (e.g. from
# `config/initializers/*`, which Rails loads later) has no effect.
#
# pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/options.rb:129
RailsSemanticLogger::Options::LOGGER_INIT_SETTINGS = T.let(T.unsafe(nil), Array)

# Settings consumed as Rails finishes initializing (`config.after_initialize`),
# which runs *after* `config/initializers/*`. They may still be set there, but
# changing them after the application has booted has no effect.
#
# pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/options.rb:134
RailsSemanticLogger::Options::POST_INIT_SETTINGS = T.let(T.unsafe(nil), Array)

# pkg:gem/rails_semantic_logger#lib/rails_semantic_logger.rb:26
module RailsSemanticLogger::Rack; end

# pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/rack/logger.rb:9
class RailsSemanticLogger::Rack::Logger < ::ActiveSupport::LogSubscriber
  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/rack/logger.rb:15
  def initialize(app, taggers = T.unsafe(nil)); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/rack/logger.rb:20
  def call(env); end

  private

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/rack/logger.rb:37
  def call_app(request, env); end

  # Leave out any named tags with a nil value
  #
  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/rack/logger.rb:79
  def compute_named_tags(request); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/rack/logger.rb:65
  def compute_tags(request); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/rack/logger.rb:96
  def logger; end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/rack/logger.rb:54
  def started_request_message(request); end

  class << self
    # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/rack/logger.rb:11
    def logger; end

    # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/rack/logger.rb:12
    def started_request_log_level; end

    # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/rack/logger.rb:12
    def started_request_log_level=(_arg0); end
  end
end

# pkg:gem/rails_semantic_logger#lib/rails_semantic_logger.rb:30
module RailsSemanticLogger::Sidekiq; end

# pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/sidekiq/defaults.rb:3
module RailsSemanticLogger::Sidekiq::Defaults
  class << self
    # Returns the default error handler after removing it from the supplied list.
    # Returns [nil] when the default handler was not present.
    #
    # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/sidekiq/defaults.rb:20
    def delete_default_error_handler(error_handlers); end
  end
end

# Prevent exception logging during standard error handling since the Job Logger below already logs the exception.
# Logs the remaining Sidekiq context at :info (matching upstream Sidekiq's default handler) rather than :warn,
# since the exception itself is already logged at :error by the Job Logger.
# Sidekiq 7.1.6+ calls error handlers with a third config argument; earlier 7.x versions pass only two.
#
# pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/sidekiq/defaults.rb:8
RailsSemanticLogger::Sidekiq::Defaults::ERROR_HANDLER = T.let(T.unsafe(nil), Proc)

# pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/sidekiq/job_logger.rb:3
class RailsSemanticLogger::Sidekiq::JobLogger
  # Sidekiq 7 passes its logger, whereas Sidekiq 8 passes its config.
  #
  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/sidekiq/job_logger.rb:17
  def initialize(arg = T.unsafe(nil)); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/sidekiq/job_logger.rb:21
  def call(item, queue, &block); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/sidekiq/job_logger.rb:50
  def prepare(job_hash, &block); end

  private

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/sidekiq/job_logger.rb:69
  def job_hash_context(job_hash); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/sidekiq/job_logger.rb:82
  def job_latency_ms(job); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/sidekiq/job_logger.rb:78
  def logged_job_attributes; end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/sidekiq/job_logger.rb:63
  def perform_messages_enabled?; end

  class << self
    # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/sidekiq/job_logger.rb:11
    def perform_messages; end

    # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/sidekiq/job_logger.rb:9
    def perform_messages=(_arg0); end
  end
end

# Job attributes copied into the logging context, matching Sidekiq's own defaults.
# Sidekiq 8 makes this configurable via `config[:logged_job_attributes]`.
#
# pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/sidekiq/job_logger.rb:6
RailsSemanticLogger::Sidekiq::JobLogger::DEFAULT_LOGGED_JOB_ATTRIBUTES = T.let(T.unsafe(nil), Array)

# pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/sidekiq/loggable.rb:3
module RailsSemanticLogger::Sidekiq::Loggable
  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/sidekiq/loggable.rb:4
  def included(base); end
end

# pkg:gem/rails_semantic_logger#lib/rails_semantic_logger.rb:36
module RailsSemanticLogger::SolidQueue; end

# pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/solid_queue/log_subscriber.rb:3
class RailsSemanticLogger::SolidQueue::LogSubscriber < ::ActiveSupport::LogSubscriber
  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/solid_queue/log_subscriber.rb:8
  def claim(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/solid_queue/log_subscriber.rb:91
  def deregister_process(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/solid_queue/log_subscriber.rb:36
  def discard(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/solid_queue/log_subscriber.rb:32
  def discard_all(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/solid_queue/log_subscriber.rb:4
  def dispatch_scheduled(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/solid_queue/log_subscriber.rb:48
  def enqueue_recurring_task(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/solid_queue/log_subscriber.rb:16
  def fail_many_claimed(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/solid_queue/log_subscriber.rb:118
  def graceful_termination(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/solid_queue/log_subscriber.rb:128
  def immediate_termination(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/solid_queue/log_subscriber.rb:110
  def prune_processes(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/solid_queue/log_subscriber.rb:80
  def register_process(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/solid_queue/log_subscriber.rb:44
  def release_blocked(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/solid_queue/log_subscriber.rb:20
  def release_claimed(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/solid_queue/log_subscriber.rb:40
  def release_many_blocked(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/solid_queue/log_subscriber.rb:12
  def release_many_claimed(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/solid_queue/log_subscriber.rb:137
  def replace_fork(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/solid_queue/log_subscriber.rb:28
  def retry(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/solid_queue/log_subscriber.rb:24
  def retry_all(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/solid_queue/log_subscriber.rb:73
  def shutdown_process(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/solid_queue/log_subscriber.rb:66
  def start_process(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/solid_queue/log_subscriber.rb:114
  def thread_error(event); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/solid_queue/log_subscriber.rb:133
  def unhandled_signal_error(event); end

  private

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/solid_queue/log_subscriber.rb:167
  def log_event(event, level, action, exception: T.unsafe(nil), **attributes); end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/solid_queue/log_subscriber.rb:178
  def logger; end

  # pkg:gem/rails_semantic_logger#lib/rails_semantic_logger/solid_queue/log_subscriber.rb:158
  def process_attributes(process); end
end
