# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `resend` gem.
# Please instead update this file by running `bin/tapioca gem resend`.


module ActionMailbox; end
module ActionMailbox::Ingresses; end
module ActionMailbox::Ingresses::Resend; end

class ActionMailbox::Ingresses::Resend::InboundEmailsController < ::ActionMailbox::BaseController
  def create; end

  private

  def _layout(lookup_context, formats, keys); end
  def _layout_from_proc; end
  def authenticate; end
  def authenticated?; end
  def email_id; end
  def email_received_event?; end
  def event; end
  def raw_email; end
  def signing_secret; end
  def verified_signature?; end

  class << self
    private

    def __class_attr___callbacks; end
    def __class_attr___callbacks=(new_value); end
    def __class_attr__wrapper_options; end
    def __class_attr__wrapper_options=(new_value); end
    def __class_attr_config; end
    def __class_attr_config=(new_value); end
    def __class_attr_helpers_path; end
    def __class_attr_helpers_path=(new_value); end
    def __class_attr_middleware_stack; end
    def __class_attr_middleware_stack=(new_value); end
  end
end

# Main Resend module
#
# pkg:gem/resend#lib/resend/version.rb:3
module Resend
  class << self
    # pkg:gem/resend#lib/resend.rb:52
    def api_key; end

    # pkg:gem/resend#lib/resend.rb:52
    def api_key=(_arg0); end

    # pkg:gem/resend#lib/resend.rb:58
    def config; end

    # pkg:gem/resend#lib/resend.rb:54
    def configure; end
  end
end

# pkg:gem/resend#lib/resend/action_mailbox/message_builder.rb:6
module Resend::ActionMailbox; end

# Rails engine that routes Resend's +email.received+ webhooks to the
# Action Mailbox ingress controller.
#
# pkg:gem/resend#lib/resend/action_mailbox/engine.rb:9
class Resend::ActionMailbox::Engine < ::Rails::Engine; end

# Rebuilds the full RFC 822 source of a received email so it can be ingested
# by Action Mailbox.
#
# Resend's +email.received+ webhook only carries metadata, so the message is
# fetched from the Received Emails API. When the API exposes a raw message
# download it is used as-is; otherwise the message is reconstructed as a
# Mail::Message from its parts, downloading each attachment through the
# attachments API.
#
# pkg:gem/resend#lib/resend/action_mailbox/message_builder.rb:15
class Resend::ActionMailbox::MessageBuilder
  # @param email_id [String] The ID of the received email
  #
  # pkg:gem/resend#lib/resend/action_mailbox/message_builder.rb:25
  def initialize(email_id); end

  # @return [String] the full RFC 822 source of the received email
  #
  # pkg:gem/resend#lib/resend/action_mailbox/message_builder.rb:30
  def raw_email; end

  private

  # pkg:gem/resend#lib/resend/action_mailbox/message_builder.rb:110
  def add_attachment(mail, meta); end

  # pkg:gem/resend#lib/resend/action_mailbox/message_builder.rb:106
  def add_attachments(mail); end

  # pkg:gem/resend#lib/resend/action_mailbox/message_builder.rb:89
  def add_bodies(mail); end

  # pkg:gem/resend#lib/resend/action_mailbox/message_builder.rb:157
  def blank?(value); end

  # pkg:gem/resend#lib/resend/action_mailbox/message_builder.rb:102
  def build_part(mime_type, content); end

  # pkg:gem/resend#lib/resend/action_mailbox/message_builder.rb:62
  def copy_envelope(mail); end

  # pkg:gem/resend#lib/resend/action_mailbox/message_builder.rb:54
  def copy_headers(mail); end

  # Preserve the addresses this email was received for (e.g. through a
  # forwarding rule) so Action Mailbox can route on them.
  #
  # pkg:gem/resend#lib/resend/action_mailbox/message_builder.rb:85
  def copy_received_for(mail); end

  # pkg:gem/resend#lib/resend/action_mailbox/message_builder.rb:122
  def decorate_attachment(part, meta); end

  # pkg:gem/resend#lib/resend/action_mailbox/message_builder.rb:135
  def download(url); end

  # pkg:gem/resend#lib/resend/action_mailbox/message_builder.rb:36
  def email; end

  # Mail omits Bcc when serializing a message by default, but Action Mailbox
  # needs it to route the email.
  #
  # pkg:gem/resend#lib/resend/action_mailbox/message_builder.rb:78
  def expose_bcc(mail); end

  # Nested objects come back from the API with string keys, but hand-built
  # hashes (tests, console usage) often use symbols. Accept both.
  #
  # pkg:gem/resend#lib/resend/action_mailbox/message_builder.rb:149
  def fetch(hash, key); end

  # pkg:gem/resend#lib/resend/action_mailbox/message_builder.rb:131
  def normalize_content_id(content_id); end

  # pkg:gem/resend#lib/resend/action_mailbox/message_builder.rb:153
  def presence(value); end

  # pkg:gem/resend#lib/resend/action_mailbox/message_builder.rb:40
  def raw_download; end

  # pkg:gem/resend#lib/resend/action_mailbox/message_builder.rb:45
  def rebuild_message; end
end

# Envelope fields that are set from the API response when the original
# header of the same name is not available.
#
# pkg:gem/resend#lib/resend/action_mailbox/message_builder.rb:22
Resend::ActionMailbox::MessageBuilder::ENVELOPE_FIELDS = T.let(T.unsafe(nil), Array)

# Headers that describe the reconstructed MIME structure and therefore
# cannot be copied verbatim from the original message.
#
# pkg:gem/resend#lib/resend/action_mailbox/message_builder.rb:18
Resend::ActionMailbox::MessageBuilder::STRUCTURAL_HEADERS = T.let(T.unsafe(nil), Array)

# api keys api wrapper
#
# pkg:gem/resend#lib/resend/api_keys.rb:5
module Resend::ApiKeys
  class << self
    # https://resend.com/docs/api-reference/api-keys/create-api-key
    #
    # pkg:gem/resend#lib/resend/api_keys.rb:8
    def create(params); end

    # https://resend.com/docs/api-reference/api-keys/list-api-keys
    #
    # pkg:gem/resend#lib/resend/api_keys.rb:14
    def list(params = T.unsafe(nil)); end

    # https://resend.com/docs/api-reference/api-keys/delete-api-key
    #
    # pkg:gem/resend#lib/resend/api_keys.rb:20
    def remove(api_key_id = T.unsafe(nil)); end

    # https://resend.com/docs/api-reference/api-keys/update-api-key
    #
    # pkg:gem/resend#lib/resend/api_keys.rb:26
    def update(params); end
  end
end

# @deprecated Use Segments instead
#
# pkg:gem/resend#lib/resend.rb:62
Resend::Audiences = Resend::Segments

# automations api wrapper
#
# pkg:gem/resend#lib/resend/automations.rb:5
module Resend::Automations
  class << self
    # https://resend.com/docs/api-reference/automations/create-automation
    #
    # pkg:gem/resend#lib/resend/automations.rb:8
    def create(params = T.unsafe(nil)); end

    # https://resend.com/docs/api-reference/automations/duplicate-automation
    #
    # pkg:gem/resend#lib/resend/automations.rb:30
    def duplicate(automation_id = T.unsafe(nil)); end

    # https://resend.com/docs/api-reference/automations/get-automation
    #
    # pkg:gem/resend#lib/resend/automations.rb:13
    def get(automation_id = T.unsafe(nil)); end

    # https://resend.com/docs/api-reference/automations/list-automations
    #
    # pkg:gem/resend#lib/resend/automations.rb:40
    def list(params = T.unsafe(nil)); end

    # https://resend.com/docs/api-reference/automations/delete-automation
    #
    # pkg:gem/resend#lib/resend/automations.rb:25
    def remove(automation_id = T.unsafe(nil)); end

    # https://resend.com/docs/api-reference/automations/stop-automation
    #
    # pkg:gem/resend#lib/resend/automations.rb:35
    def stop(automation_id = T.unsafe(nil)); end

    # https://resend.com/docs/api-reference/automations/update-automation
    #
    # pkg:gem/resend#lib/resend/automations.rb:18
    def update(params = T.unsafe(nil)); end
  end
end

# Automation Runs api wrapper
#
# pkg:gem/resend#lib/resend/automations/runs.rb:6
module Resend::Automations::Runs
  class << self
    # https://resend.com/docs/api-reference/automations/get-automation-run
    #
    # pkg:gem/resend#lib/resend/automations/runs.rb:16
    def get(automation_id, run_id); end

    # https://resend.com/docs/api-reference/automations/list-automation-runs
    #
    # pkg:gem/resend#lib/resend/automations/runs.rb:9
    def list(automation_id, params = T.unsafe(nil)); end
  end
end

# Module responsible for wrapping Batch email sending API
#
# pkg:gem/resend#lib/resend/batch.rb:5
module Resend::Batch
  class << self
    # Send a batch of emails
    #
    # @param params [Array<Hash>] Array of email parameters (max 100 emails)
    # @param options [Hash] Additional options for the request
    # @option options [String] :idempotency_key Optional idempotency key
    # @option options [String] :batch_validation Batch validation mode: "strict" (default) or "permissive"
    #   - "strict": Entire batch fails if any email is invalid
    #   - "permissive": Sends valid emails and returns errors for invalid ones
    #
    # @return [Hash] Response with :data array and optional :errors array (in permissive mode)
    #
    # @example Send batch with strict validation (default)
    #   Resend::Batch.send([
    #     { from: "sender@example.com", to: ["recipient@example.com"], subject: "Hello", html: "<p>Hi</p>" }
    #   ])
    #
    # @example Send batch with permissive validation
    #   response = Resend::Batch.send(emails, options: { batch_validation: "permissive" })
    #   # response[:data] contains successful email IDs
    #   # response[:errors] contains validation errors with index and message
    #
    # https://resend.com/docs/api-reference/emails/send-batch-emails
    #
    # pkg:gem/resend#lib/resend/batch.rb:29
    def send(params = T.unsafe(nil), options: T.unsafe(nil)); end
  end
end

# broadcasts api wrapper
#
# pkg:gem/resend#lib/resend/broadcasts.rb:5
module Resend::Broadcasts
  class << self
    # pkg:gem/resend#lib/resend/broadcasts.rb:50
    def cancel(broadcast_id = T.unsafe(nil)); end

    # https://resend.com/docs/api-reference/broadcasts/list-broadcast-clicked-links
    #
    # pkg:gem/resend#lib/resend/broadcasts.rb:45
    def clicked_links(broadcast_id = T.unsafe(nil), params = T.unsafe(nil)); end

    # https://resend.com/docs/api-reference/broadcasts/create-broadcast
    # @note Supports both segment_id and audience_id. At least one is required.
    #   audience_id is deprecated - use segment_id instead.
    # @note When send: true is passed, the broadcast is sent immediately instead of
    #   creating a draft. When using send: true, you can also include scheduled_at
    #   to schedule the broadcast. Passing scheduled_at without send: true is an error.
    #
    # pkg:gem/resend#lib/resend/broadcasts.rb:13
    def create(params = T.unsafe(nil)); end

    # https://resend.com/docs/api-reference/broadcasts/duplicate-broadcast
    # @note Creates a new draft with the same content as the source, named after it with " (copy)" appended.
    #
    # pkg:gem/resend#lib/resend/broadcasts.rb:57
    def duplicate(broadcast_id = T.unsafe(nil)); end

    # https://resend.com/docs/api-reference/broadcasts/get-broadcast
    #
    # pkg:gem/resend#lib/resend/broadcasts.rb:69
    def get(broadcast_id = T.unsafe(nil)); end

    # https://resend.com/docs/api-reference/broadcasts/list-broadcasts
    #
    # pkg:gem/resend#lib/resend/broadcasts.rb:39
    def list(params = T.unsafe(nil)); end

    # https://resend.com/docs/api-reference/broadcasts/list-broadcast-recipients
    # @param broadcast_id [String] the broadcast id
    # @param params [Hash] the parameters
    # @option params [String] :type the recipient event type to filter by (required):
    #   sent, delivered, opened, clicked, bounced, complained, unsubscribed, suppressed
    # @option params [String] :email filter recipients by email address (optional)
    # @option params [String] :bounce_type filter bounced recipients by bounce type (optional,
    #   only valid when type is bounced): permanent, transient, undetermined
    # @option params [Integer] :limit the maximum number of results to return (optional)
    # @option params [String] :after the cursor for pagination (optional)
    # @option params [String] :before the cursor for pagination (optional)
    #
    # pkg:gem/resend#lib/resend/broadcasts.rb:85
    def recipients(broadcast_id = T.unsafe(nil), params = T.unsafe(nil)); end

    # https://resend.com/docs/api-reference/broadcasts/delete-broadcast
    #
    # pkg:gem/resend#lib/resend/broadcasts.rb:63
    def remove(broadcast_id = T.unsafe(nil)); end

    # https://resend.com/docs/api-reference/broadcasts/send-broadcast
    #
    # pkg:gem/resend#lib/resend/broadcasts.rb:33
    def send(params = T.unsafe(nil)); end

    # https://resend.com/docs/api-reference/broadcasts/update-broadcast
    # @note Supports both segment_id and audience_id. At least one may be required.
    #   audience_id is deprecated - use segment_id instead.
    #
    # pkg:gem/resend#lib/resend/broadcasts.rb:24
    def update(params = T.unsafe(nil)); end
  end
end

# Client class.
#
# pkg:gem/resend#lib/resend/client.rb:8
class Resend::Client
  include ::Resend::Emails

  # pkg:gem/resend#lib/resend/client.rb:13
  def initialize(api_key); end

  # pkg:gem/resend#lib/resend/client.rb:11
  def api_key; end
end

# Module for managing contact properties
#
# Contact properties allow you to store custom data about your contacts
#
# pkg:gem/resend#lib/resend/contact_properties.rb:7
module Resend::ContactProperties
  class << self
    # Create a custom property for your contacts
    #
    # @param params [Hash] Parameters for creating a contact property
    # @option params [String] :key The property key (max 50 characters, alphanumeric and underscores only) (required)
    # @option params [String] :type The property type ('string' or 'number') (required)
    # @option params [String, Integer] :fallback_value The default value when property is not set (must match type)
    #
    # @return [Hash] Response containing the created contact property
    #
    # @example Create a string property
    #   Resend::ContactProperties.create({
    #     key: 'company_name',
    #     type: 'string',
    #     fallback_value: 'Acme Corp'
    #   })
    #
    # @example Create a number property
    #   Resend::ContactProperties.create({
    #     key: 'age',
    #     type: 'number',
    #     fallback_value: 0
    #   })
    #
    # pkg:gem/resend#lib/resend/contact_properties.rb:31
    def create(params); end

    # Retrieve a contact property by its ID
    #
    # @param contact_property_id [String] The Contact Property ID
    #
    # @return [Hash] Response containing the contact property details
    #
    # @example Get a contact property
    #   Resend::ContactProperties.get('b6d24b8e-af0b-4c3c-be0c-359bbd97381e')
    #
    # pkg:gem/resend#lib/resend/contact_properties.rb:44
    def get(contact_property_id = T.unsafe(nil)); end

    # Retrieve a list of contact properties
    #
    # @param params [Hash] Optional query parameters
    # @option params [Integer] :limit Number of contact properties to retrieve (1-100, default: 20)
    # @option params [String] :after The ID after which to retrieve more contact properties
    # @option params [String] :before The ID before which to retrieve more contact properties
    #
    # @return [Hash] Response containing list of contact properties
    #
    # @example List all contact properties
    #   Resend::ContactProperties.list
    #
    # @example List with pagination
    #   Resend::ContactProperties.list({ limit: 10, after: 'cursor_123' })
    #
    # pkg:gem/resend#lib/resend/contact_properties.rb:63
    def list(params = T.unsafe(nil)); end

    # Remove an existing contact property
    #
    # @param contact_property_id [String] The Contact Property ID
    #
    # @return [Hash] Response containing the deleted property ID and confirmation
    #
    # @example Delete a contact property
    #   Resend::ContactProperties.remove('b6d24b8e-af0b-4c3c-be0c-359bbd97381e')
    #
    # pkg:gem/resend#lib/resend/contact_properties.rb:100
    def remove(contact_property_id = T.unsafe(nil)); end

    # Update an existing contact property
    #
    # Note: The 'key' and 'type' fields cannot be changed after creation
    #
    # @param params [Hash] Parameters for updating a contact property
    # @option params [String] :id The Contact Property ID (required)
    # @option params [String, Integer] :fallback_value The default value when property is not set
    #   (must match property type)
    #
    # @return [Hash] Response containing the updated contact property
    #
    # @example Update fallback value
    #   Resend::ContactProperties.update({
    #     id: 'b6d24b8e-af0b-4c3c-be0c-359bbd97381e',
    #     fallback_value: 'Example Company'
    #   })
    #
    # pkg:gem/resend#lib/resend/contact_properties.rb:84
    def update(params); end
  end
end

# Contacts api wrapper
#
# pkg:gem/resend#lib/resend/contacts.rb:5
module Resend::Contacts
  class << self
    # https://resend.com/docs/api-reference/contacts/create-contact
    #
    # pkg:gem/resend#lib/resend/contacts.rb:8
    def create(params); end

    # Retrieves a contact
    #
    # @param params [Hash] the parameters
    # @option params [String] :id either the contact id or contact's email (required)
    # @option params [String] :audience_id optional audience id to scope the operation
    #
    # @example Get contact by ID
    #   Resend::Contacts.get(id: "contact_123")
    #
    # @example Get contact scoped to an audience
    #   Resend::Contacts.get(id: "contact_123", audience_id: "aud_456")
    #
    # https://resend.com/docs/api-reference/contacts/get-contact
    #
    # pkg:gem/resend#lib/resend/contacts.rb:34
    def get(params = T.unsafe(nil)); end

    # List contacts
    #
    # @param params [Hash] optional parameters including pagination
    # @option params [String] :audience_id optional audience id to scope the operation
    # @option params [Integer] :limit number of records to return
    # @option params [String] :cursor pagination cursor
    #
    # @example List all contacts
    #   Resend::Contacts.list
    #
    # @example List contacts with pagination
    #   Resend::Contacts.list(limit: 10)
    #
    # @example List contacts scoped to a segment
    #   Resend::Contacts.list(segment_id: "seg_456", limit: 10)
    #
    # @example List contacts scoped to an audience
    #   Resend::Contacts.list(audience_id: "aud_456", limit: 10)
    #
    # https://resend.com/docs/api-reference/contacts/list-contacts
    #
    # pkg:gem/resend#lib/resend/contacts.rb:68
    def list(params = T.unsafe(nil)); end

    # Remove a contact
    #
    # @param params [Hash] the parameters
    # @option params [String] :id either the contact id or contact email (required)
    # @option params [String] :audience_id optional audience id to scope the operation
    #
    # @example Remove contact by ID
    #   Resend::Contacts.remove(id: "contact_123")
    #
    # @example Remove contact scoped to an audience
    #   Resend::Contacts.remove(id: "contact_123", audience_id: "aud_456")
    #
    # https://resend.com/docs/api-reference/contacts/delete-contact
    #
    # pkg:gem/resend#lib/resend/contacts.rb:97
    def remove(params = T.unsafe(nil)); end

    # Update a contact
    #
    # @param params [Hash] the contact params
    # https://resend.com/docs/api-reference/contacts/update-contact
    #
    # pkg:gem/resend#lib/resend/contacts.rb:115
    def update(params); end
  end
end

# Contact Imports API wrapper
#
# pkg:gem/resend#lib/resend/contacts/imports.rb:6
module Resend::Contacts::Imports
  class << self
    # Create a new contact import from a CSV file.
    #
    # @param params [Hash] the parameters
    # @option params [String, IO] :file CSV file content (required). Maximum size is 50MB.
    # @option params [Hash, String] :column_map optional mapping of contact fields to CSV columns.
    #   Accepts a Hash (will be JSON-encoded) or a pre-encoded JSON String.
    # @option params [String] :on_conflict optional conflict strategy: 'upsert' or 'skip' (default 'skip').
    # @option params [Array, String] :segments optional list of segment IDs to add contacts to.
    #   Accepts an Array of segment ID strings (will be JSON-encoded as [{"id":"..."}])
    #   or a pre-encoded JSON String.
    # @option params [Array, String] :topics optional list of topic subscription objects.
    #   Each element must be a Hash with `id` (String) and `subscription` ('opt_in' or 'opt_out').
    #   Accepts an Array of Hashes (will be JSON-encoded) or a pre-encoded JSON String.
    #
    # https://resend.com/docs/api-reference/contacts/create-contact-import
    #
    # pkg:gem/resend#lib/resend/contacts/imports.rb:24
    def create(params); end

    # Retrieve a single contact import by ID.
    #
    # @param id [String] the contact import ID (required)
    #
    # https://resend.com/docs/api-reference/contacts/get-contact-import
    #
    # pkg:gem/resend#lib/resend/contacts/imports.rb:41
    def get(id); end

    # Retrieve a list of contact imports.
    #
    # @param params [Hash] optional filtering and pagination parameters
    # @option params [String] :status filter by status: 'queued', 'in_progress', 'completed', or 'failed'
    # @option params [Integer] :limit number of results to return
    # @option params [String] :after cursor for forward pagination
    # @option params [String] :before cursor for backward pagination
    #
    # https://resend.com/docs/api-reference/contacts/list-contact-imports
    #
    # pkg:gem/resend#lib/resend/contacts/imports.rb:57
    def list(params = T.unsafe(nil)); end
  end
end

# Contact Segments api wrapper
#
# pkg:gem/resend#lib/resend/contacts/segments.rb:6
module Resend::Contacts::Segments
  class << self
    # Add a contact to a segment
    #
    # @param params [Hash] the parameters
    # @option params [String] :contact_id the contact id (either contact_id or email is required)
    # @option params [String] :email the contact email (either contact_id or email is required)
    # @option params [String] :segment_id the segment id (required)
    #
    # https://resend.com/docs/api-reference/contacts/add-contact-to-segment
    #
    # pkg:gem/resend#lib/resend/contacts/segments.rb:37
    def add(params); end

    # List all segments for a contact
    #
    # @param params [Hash] the parameters
    # @option params [String] :contact_id the contact id (either contact_id or email is required)
    # @option params [String] :email the contact email (either contact_id or email is required)
    # @option params [Integer] :limit the maximum number of results to return (optional)
    # @option params [String] :after the cursor for pagination (optional)
    # @option params [String] :before the cursor for pagination (optional)
    #
    # https://resend.com/docs/api-reference/contacts/list-contact-segments
    #
    # pkg:gem/resend#lib/resend/contacts/segments.rb:19
    def list(params); end

    # Remove a contact from a segment
    #
    # @param params [Hash] the parameters
    # @option params [String] :contact_id the contact id (either contact_id or email is required)
    # @option params [String] :email the contact email (either contact_id or email is required)
    # @option params [String] :segment_id the segment id (required)
    #
    # https://resend.com/docs/api-reference/contacts/remove-contact-from-segment
    #
    # pkg:gem/resend#lib/resend/contacts/segments.rb:55
    def remove(params); end
  end
end

# Module for managing contact topic subscriptions
#
# Allows you to manage which topics contacts are subscribed to
#
# pkg:gem/resend#lib/resend/contacts/topics.rb:8
module Resend::Contacts::Topics
  class << self
    # Retrieve a list of topics subscriptions for a contact
    #
    # @param params [Hash] Parameters for listing topics
    # @option params [String] :id The Contact ID (either :id or :email must be provided)
    # @option params [String] :email The Contact Email (either :id or :email must be provided)
    # @option params [Integer] :limit Number of topics to retrieve (1-100)
    # @option params [String] :after The ID after which to retrieve more topics
    # @option params [String] :before The ID before which to retrieve more topics
    #
    # @return [Hash] Response containing list of topics with subscription status
    #
    # @example List topics by contact ID
    #   Resend::Contacts::Topics.list(id: 'e169aa45-1ecf-4183-9955-b1499d5701d3')
    #
    # @example List topics by contact email
    #   Resend::Contacts::Topics.list(email: 'steve.wozniak@gmail.com')
    #
    # @example List topics with pagination
    #   Resend::Contacts::Topics.list(id: 'contact-id', limit: 10, after: 'cursor_123')
    #
    # pkg:gem/resend#lib/resend/contacts/topics.rb:29
    def list(params = T.unsafe(nil)); end

    # Update topic subscriptions for a contact
    #
    # @param params [Hash] Parameters for updating topics
    # @option params [String] :id The Contact ID (either :id or :email must be provided)
    # @option params [String] :email The Contact Email (either :id or :email must be provided)
    # @option params [Array<Hash>] :topics Array of topic subscription updates
    #   Each topic hash should contain:
    #   - :id [String] The Topic ID (required)
    #   - :subscription [String] The subscription action: 'opt_in' or 'opt_out' (required)
    #
    # @return [Hash] Response containing the contact ID
    #
    # @example Update by contact ID
    #   Resend::Contacts::Topics.update({
    #     id: 'e169aa45-1ecf-4183-9955-b1499d5701d3',
    #     topics: [
    #       { id: 'b6d24b8e-af0b-4c3c-be0c-359bbd97381e', subscription: 'opt_out' },
    #       { id: '07d84122-7224-4881-9c31-1c048e204602', subscription: 'opt_in' }
    #     ]
    #   })
    #
    # @example Update by contact email
    #   Resend::Contacts::Topics.update({
    #     email: 'steve.wozniak@gmail.com',
    #     topics: [
    #       { id: '07d84122-7224-4881-9c31-1c048e204602', subscription: 'opt_out' }
    #     ]
    #   })
    #
    # pkg:gem/resend#lib/resend/contacts/topics.rb:68
    def update(params); end
  end
end

# domains api wrapper
#
# pkg:gem/resend#lib/resend/domains.rb:5
module Resend::Domains
  class << self
    # https://resend.com/docs/api-reference/domains/create-domain
    #
    # pkg:gem/resend#lib/resend/domains.rb:8
    def create(params); end

    # https://resend.com/docs/api-reference/domains/get-domain
    #
    # pkg:gem/resend#lib/resend/domains.rb:20
    def get(domain_id = T.unsafe(nil)); end

    # https://resend.com/docs/api-reference/domains/list-domains
    #
    # pkg:gem/resend#lib/resend/domains.rb:26
    def list(params = T.unsafe(nil)); end

    # https://resend.com/docs/api-reference/domains/delete-domain
    #
    # pkg:gem/resend#lib/resend/domains.rb:32
    def remove(domain_id = T.unsafe(nil)); end

    # https://resend.com/docs/api-reference/domains/update-domain
    #
    # pkg:gem/resend#lib/resend/domains.rb:14
    def update(params); end

    # https://resend.com/docs/api-reference/domains/verify-domain
    #
    # pkg:gem/resend#lib/resend/domains.rb:38
    def verify(domain_id = T.unsafe(nil)); end
  end
end

# Domain Claims API wrapper
#
# pkg:gem/resend#lib/resend/domains/claims.rb:6
module Resend::Domains::Claims
  class << self
    # Start a claim for a domain that another Resend account has already verified.
    # The domain is recreated under your account with fresh DKIM keys, so the
    # previous account's DNS records cannot be reused. Returns a TXT record to add
    # to your DNS to prove ownership. Uses the same request body as creating a domain.
    #
    # @param params [Hash] the parameters
    # @option params [String] :name the name of the domain you want to claim (required)
    # @option params [String] :region the region where emails will be sent from.
    #   Possible values: 'us-east-1' | 'eu-west-1' | 'sa-east-1' | 'ap-northeast-1'
    # @option params [String] :custom_return_path subdomain for the Return-Path address (default 'send')
    # @option params [String] :tracking_subdomain the custom subdomain used for click and open tracking links
    # @option params [Boolean] :click_tracking track clicks within the body of each HTML email
    # @option params [Boolean] :open_tracking track the open rate of each email
    #
    # https://resend.com/docs/api-reference/domains/claim-domain
    #
    # pkg:gem/resend#lib/resend/domains/claims.rb:24
    def create(params); end

    # Retrieve the latest claim for the placeholder domain created by the claim.
    #
    # @param domain_id [String] the ID of the placeholder domain created by the claim
    #
    # https://resend.com/docs/api-reference/domains/get-domain-claim
    #
    # pkg:gem/resend#lib/resend/domains/claims.rb:35
    def get(domain_id = T.unsafe(nil)); end

    # Trigger asynchronous DNS verification and ownership transfer for a domain claim.
    # The claim stays 'pending' while verification runs; poll `get` for status. Once
    # 'completed', the transferred domain has new DKIM records that must be added to
    # DNS and verified via Resend::Domains.verify.
    #
    # @param domain_id [String] the ID of the placeholder domain created by the claim
    #
    # https://resend.com/docs/api-reference/domains/verify-domain-claim
    #
    # pkg:gem/resend#lib/resend/domains/claims.rb:49
    def verify(domain_id = T.unsafe(nil)); end
  end
end

# Module responsible for wrapping email sending API
#
# pkg:gem/resend#lib/resend/emails.rb:5
module Resend::Emails
  class << self
    # Cancel a scheduled email.
    # see more: https://resend.com/docs/api-reference/emails/cancel-email
    #
    # pkg:gem/resend#lib/resend/emails.rb:30
    def cancel(email_id = T.unsafe(nil)); end

    # Retrieve a single email.
    # see more: https://resend.com/docs/api-reference/emails/retrieve-email
    #
    # pkg:gem/resend#lib/resend/emails.rb:16
    def get(email_id = T.unsafe(nil)); end

    # List emails with optional pagination.
    # see more: https://resend.com/docs/api-reference/emails/list-emails
    #
    # @param options [Hash] Optional parameters for pagination
    # @option options [Integer] :limit Maximum number of emails to return (1-100, default 20)
    # @option options [String] :after Cursor for pagination (newer emails)
    # @option options [String] :before Cursor for pagination (older emails)
    #
    # pkg:gem/resend#lib/resend/emails.rb:53
    def list(options = T.unsafe(nil)); end

    # Retrieve email metrics.
    # see more: https://resend.com/docs/api-reference/emails/metrics
    #
    # @param options [Hash] Optional parameters for filtering and shaping the metrics response
    # @option options [String] :start_date ISO 8601 date/datetime. Defaults to 6 days before :end_date
    # @option options [String] :end_date ISO 8601 date/datetime. Defaults to now
    # @option options [String] :timezone IANA timezone, e.g. "America/New_York". Defaults to "UTC"
    # @option options [String] :granularity Bucket size used when :period is in :dimensions.
    #   One of "hourly", "daily", "weekly", "monthly". Defaults to "daily"
    # @option options [Array<String>] :metrics Metrics to include. Defaults to all metrics.
    # @option options [Array<String>] :dimensions Dimensions to break down by: "period", "domain",
    #   "email", "broadcast". Defaults to none, which returns totals only.
    # @option options [Array<String>] :domain_id Restrict to these sending domain IDs (max 100)
    # @option options [Array<String>] :email_id Restrict to these email IDs (max 100)
    # @option options [Array<String>] :broadcast_id Restrict to these broadcast IDs (max 100)
    #
    # pkg:gem/resend#lib/resend/emails.rb:80
    def metrics(options = T.unsafe(nil)); end

    # Sends or schedules an email.
    # see more: https://resend.com/docs/api-reference/emails/send-email
    #
    # pkg:gem/resend#lib/resend/emails.rb:9
    def send(params, options: T.unsafe(nil)); end

    # Create a shareable link for a sent or received email.
    #
    # @param email_id [String] The email id (sent or received).
    # @param params [Hash] Optional parameters
    # @option params [String] :expires_in Human-readable duration (e.g. "10m", "2 hours",
    #   "1 day"). Defaults to "48h" and is capped at 48 hours.
    #
    # pkg:gem/resend#lib/resend/emails.rb:41
    def share(email_id, params = T.unsafe(nil)); end

    # Update a scheduled email.
    # see more: https://resend.com/docs/api-reference/emails/update-email
    #
    # pkg:gem/resend#lib/resend/emails.rb:23
    def update(params); end

    private

    # pkg:gem/resend#lib/resend/emails.rb:119
    def blank?(value); end

    # Builds the metrics query hash, filtering out nil values and joining
    # list-style params (metrics, dimensions, domain_id, email_id, broadcast_id)
    # into comma-separated strings as expected by the API.
    #
    # pkg:gem/resend#lib/resend/emails.rb:103
    def build_metrics_query(options); end

    # The `email` and `broadcast` dimensions/filters are mutually exclusive.
    #
    # pkg:gem/resend#lib/resend/emails.rb:89
    def validate_metrics_options(options); end
  end
end

# Module for sent email attachments API operations
#
# pkg:gem/resend#lib/resend/emails/attachments.rb:6
module Resend::Emails::Attachments
  class << self
    # Retrieve a single attachment from a sent email
    #
    # @param params [Hash] Parameters for retrieving the attachment
    # @option params [String] :id The attachment ID (required)
    # @option params [String] :email_id The email ID (required)
    # @return [Hash] The attachment object
    #
    # @example
    #   Resend::Emails::Attachments.get(
    #     id: "2a0c9ce0-3112-4728-976e-47ddcd16a318",
    #     email_id: "4ef9a417-02e9-4d39-ad75-9611e0fcc33c"
    #   )
    #
    # pkg:gem/resend#lib/resend/emails/attachments.rb:20
    def get(params = T.unsafe(nil)); end

    # List attachments from a sent email with optional pagination
    #
    # @param params [Hash] Parameters for listing attachments
    # @option params [String] :email_id The email ID (required)
    # @option params [Integer] :limit Maximum number of attachments to return (1-100)
    # @option params [String] :after Cursor for pagination (newer attachments)
    # @option params [String] :before Cursor for pagination (older attachments)
    # @return [Hash] List of attachments with pagination info
    #
    # @example List all attachments
    #   Resend::Emails::Attachments.list(
    #     email_id: "4ef9a417-02e9-4d39-ad75-9611e0fcc33c"
    #   )
    #
    # @example List with custom limit
    #   Resend::Emails::Attachments.list(
    #     email_id: "4ef9a417-02e9-4d39-ad75-9611e0fcc33c",
    #     limit: 50
    #   )
    #
    # @example List with pagination
    #   Resend::Emails::Attachments.list(
    #     email_id: "4ef9a417-02e9-4d39-ad75-9611e0fcc33c",
    #     limit: 20,
    #     after: "attachment_id_123"
    #   )
    #
    # pkg:gem/resend#lib/resend/emails/attachments.rb:54
    def list(params = T.unsafe(nil)); end
  end
end

# Module for receiving emails API operations
#
# pkg:gem/resend#lib/resend/emails/receiving.rb:6
module Resend::Emails::Receiving
  class << self
    # Retrieve a single received email
    #
    # @param email_id [String] The ID of the received email
    # @param params [Hash] Optional query parameters
    # @option params [String] :html_format Format of the HTML content (e.g., "sanitized", "raw")
    # @return [Hash] The received email object
    #
    # @example
    #   Resend::Emails::Receiving.get("4ef9a417-02e9-4d39-ad75-9611e0fcc33c")
    #
    # @example With html_format
    #   Resend::Emails::Receiving.get("4ef9a417-02e9-4d39-ad75-9611e0fcc33c", html_format: "sanitized")
    #
    # pkg:gem/resend#lib/resend/emails/receiving.rb:20
    def get(email_id = T.unsafe(nil), params = T.unsafe(nil)); end

    # List received emails with optional pagination
    #
    # @param params [Hash] Optional parameters for pagination
    # @option params [Integer] :limit Maximum number of emails to return (1-100)
    # @option params [String] :after Cursor for pagination (newer emails)
    # @option params [String] :before Cursor for pagination (older emails)
    # @return [Hash] List of received emails with pagination info
    #
    # @example List all received emails
    #   Resend::Emails::Receiving.list
    #
    # @example List with custom limit
    #   Resend::Emails::Receiving.list(limit: 50)
    #
    # @example List with pagination
    #   Resend::Emails::Receiving.list(limit: 20, after: "email_id_123")
    #
    # pkg:gem/resend#lib/resend/emails/receiving.rb:44
    def list(params = T.unsafe(nil)); end
  end
end

# Module for received email attachments API operations
#
# pkg:gem/resend#lib/resend/emails/receiving/attachments.rb:7
module Resend::Emails::Receiving::Attachments
  class << self
    # Retrieve a single attachment from a received email
    #
    # @param params [Hash] Parameters for retrieving the attachment
    # @option params [String] :id The attachment ID (required)
    # @option params [String] :email_id The email ID (required)
    # @return [Hash] The attachment object
    #
    # @example
    #   Resend::Emails::Receiving::Attachments.get(
    #     id: "2a0c9ce0-3112-4728-976e-47ddcd16a318",
    #     email_id: "4ef9a417-02e9-4d39-ad75-9611e0fcc33c"
    #   )
    #
    # pkg:gem/resend#lib/resend/emails/receiving/attachments.rb:21
    def get(params = T.unsafe(nil)); end

    # List attachments from a received email with optional pagination
    #
    # @param params [Hash] Parameters for listing attachments
    # @option params [String] :email_id The email ID (required)
    # @option params [Integer] :limit Maximum number of attachments to return (1-100)
    # @option params [String] :after Cursor for pagination (newer attachments)
    # @option params [String] :before Cursor for pagination (older attachments)
    # @return [Hash] List of attachments with pagination info
    #
    # @example List all attachments
    #   Resend::Emails::Receiving::Attachments.list(
    #     email_id: "4ef9a417-02e9-4d39-ad75-9611e0fcc33c"
    #   )
    #
    # @example List with custom limit
    #   Resend::Emails::Receiving::Attachments.list(
    #     email_id: "4ef9a417-02e9-4d39-ad75-9611e0fcc33c",
    #     limit: 50
    #   )
    #
    # @example List with pagination
    #   Resend::Emails::Receiving::Attachments.list(
    #     email_id: "4ef9a417-02e9-4d39-ad75-9611e0fcc33c",
    #     limit: 20,
    #     after: "attachment_id_123"
    #   )
    #
    # pkg:gem/resend#lib/resend/emails/receiving/attachments.rb:55
    def list(params = T.unsafe(nil)); end
  end
end

# Errors wrapper class
# For more info: https://resend.com/docs/api-reference/error-codes
#
# pkg:gem/resend#lib/resend/errors.rb:6
class Resend::Error < ::StandardError
  # pkg:gem/resend#lib/resend/errors.rb:46
  def initialize(msg, code = T.unsafe(nil), headers = T.unsafe(nil)); end

  # pkg:gem/resend#lib/resend/errors.rb:44
  def headers; end
end

# 4xx HTTP status code
#
# pkg:gem/resend#lib/resend/errors.rb:8
class Resend::Error::ClientError < ::Resend::Error; end

# pkg:gem/resend#lib/resend/errors.rb:35
Resend::Error::ERRORS = T.let(T.unsafe(nil), Hash)

# code 500
#
# pkg:gem/resend#lib/resend/errors.rb:14
class Resend::Error::InternalServerError < ::Resend::Error::ServerError; end

# code 422
#
# pkg:gem/resend#lib/resend/errors.rb:17
class Resend::Error::InvalidRequestError < ::Resend::Error::ServerError; end

# code 404
#
# pkg:gem/resend#lib/resend/errors.rb:33
class Resend::Error::NotFoundError < ::Resend::Error::ServerError; end

# code 429
#
# pkg:gem/resend#lib/resend/errors.rb:20
class Resend::Error::RateLimitExceededError < ::Resend::Error::ServerError
  # pkg:gem/resend#lib/resend/errors.rb:23
  def initialize(msg, code = T.unsafe(nil), headers = T.unsafe(nil)); end

  # pkg:gem/resend#lib/resend/errors.rb:21
  def rate_limit_limit; end

  # pkg:gem/resend#lib/resend/errors.rb:21
  def rate_limit_remaining; end

  # pkg:gem/resend#lib/resend/errors.rb:21
  def rate_limit_reset; end

  # pkg:gem/resend#lib/resend/errors.rb:21
  def retry_after; end
end

# 5xx HTTP status code
#
# pkg:gem/resend#lib/resend/errors.rb:11
class Resend::Error::ServerError < ::Resend::Error; end

# events api wrapper
#
# pkg:gem/resend#lib/resend/events.rb:5
module Resend::Events
  class << self
    # https://resend.com/docs/api-reference/events/create-event
    #
    # pkg:gem/resend#lib/resend/events.rb:8
    def create(params = T.unsafe(nil)); end

    # https://resend.com/docs/api-reference/events/get-event
    # identifier can be a UUID or an event name (e.g. "user.signed_up")
    #
    # pkg:gem/resend#lib/resend/events.rb:14
    def get(identifier = T.unsafe(nil)); end

    # https://resend.com/docs/api-reference/events/list-events
    #
    # pkg:gem/resend#lib/resend/events.rb:40
    def list(params = T.unsafe(nil)); end

    # https://resend.com/docs/api-reference/events/delete-event
    # identifier can be a UUID or an event name (e.g. "user.signed_up")
    #
    # pkg:gem/resend#lib/resend/events.rb:29
    def remove(identifier = T.unsafe(nil)); end

    # https://resend.com/docs/api-reference/events/send-event
    #
    # pkg:gem/resend#lib/resend/events.rb:35
    def send(params = T.unsafe(nil)); end

    # https://resend.com/docs/api-reference/events/update-event
    #
    # pkg:gem/resend#lib/resend/events.rb:20
    def update(params = T.unsafe(nil)); end
  end
end

# logs api wrapper
#
# pkg:gem/resend#lib/resend/logs.rb:5
module Resend::Logs
  class << self
    # https://resend.com/docs/api-reference/logs/retrieve-log
    #
    # pkg:gem/resend#lib/resend/logs.rb:8
    def get(log_id = T.unsafe(nil)); end

    # https://resend.com/docs/api-reference/logs/list-logs
    #
    # pkg:gem/resend#lib/resend/logs.rb:14
    def list(params = T.unsafe(nil)); end
  end
end

# Mailer class used by railtie
#
# pkg:gem/resend#lib/resend/mailer.rb:7
class Resend::Mailer
  # pkg:gem/resend#lib/resend/mailer.rb:23
  def initialize(config); end

  # Builds the payload for sending
  #
  # @param Mail mail rails mail object
  #
  # @return Hash hash with all Resend params
  #
  # pkg:gem/resend#lib/resend/mailer.rb:53
  def build_resend_params(mail); end

  # Remove nils from header values
  #
  # pkg:gem/resend#lib/resend/mailer.rb:115
  def cleanup_headers(headers); end

  # pkg:gem/resend#lib/resend/mailer.rb:8
  def config; end

  # pkg:gem/resend#lib/resend/mailer.rb:8
  def config=(_arg0); end

  # Overwritten deliver! method
  #
  # @param Mail mail
  #
  # @return Object resend response
  #
  # pkg:gem/resend#lib/resend/mailer.rb:38
  def deliver!(mail); end

  # Add cc, bcc, reply_to fields
  #
  # @param Mail mail Rails Mail Object
  #
  # @return Hash hash containing cc/bcc/reply_to attrs
  #
  # pkg:gem/resend#lib/resend/mailer.rb:165
  def get_addons(mail); end

  # Handle attachments when present
  #
  # @return Array attachments array
  #
  # pkg:gem/resend#lib/resend/mailer.rb:215
  def get_attachments(mail); end

  # Gets the body of the email
  #
  # @param Mail mail Rails Mail Object
  #
  # @return Hash hash containing html/text or both attrs
  #
  # pkg:gem/resend#lib/resend/mailer.rb:180
  def get_contents(mail); end

  # Properly gets the `from` attr
  #
  # @param Mail input object
  #
  # @return String `from` string
  #
  # pkg:gem/resend#lib/resend/mailer.rb:201
  def get_from(input); end

  # Add custom headers fields.
  #
  # Both ways are supported:
  #
  #   1. Through the `#mail()` method ie:
  #     mail(headers: { "X-Custom-Header" => "value" })
  #
  #   2. Through the Rails `#headers` method ie:
  #     headers["X-Custom-Header"] = "value"
  #
  #
  # setting the header values through the `#mail` method will overwrite values set
  # through the `#headers` method using the same key.
  #
  # @param Mail mail Rails Mail object
  #
  # @return Hash hash with headers param
  #
  # pkg:gem/resend#lib/resend/mailer.rb:86
  def get_headers(mail); end

  # Adds additional options fields.
  # Currently supports only :idempotency_key
  #
  # @param Mail mail Rails Mail object
  # @return Hash hash with headers param
  #
  # pkg:gem/resend#lib/resend/mailer.rb:105
  def get_options(mail); end

  # Add tags fields
  #
  # @param Mail mail Rails Mail object
  #
  # @return Hash hash with tags param
  #
  # pkg:gem/resend#lib/resend/mailer.rb:152
  def get_tags(mail); end

  # Gets the values of the headers that are set through the `#headers` method
  #
  # @param Mail mail Rails Mail object
  # @return Hash hash with headers values
  #
  # pkg:gem/resend#lib/resend/mailer.rb:136
  def headers_values(mail); end

  # Gets the values of the headers that are set through the `#mail` method
  #
  # @param Mail mail Rails Mail object
  # @return Hash hash with mail headers values
  #
  # pkg:gem/resend#lib/resend/mailer.rb:123
  def mail_headers_values(mail); end

  # pkg:gem/resend#lib/resend/mailer.rb:8
  def settings; end

  # pkg:gem/resend#lib/resend/mailer.rb:8
  def settings=(_arg0); end

  # Get all headers that are not ignored
  #
  # @param Mail mail
  #
  # @return Array headers
  #
  # pkg:gem/resend#lib/resend/mailer.rb:237
  def unignored_headers(mail); end
end

# These are set as `headers` by the Rails API, but these will be filtered out
# when constructing the Resend API payload, since they're are sent as post params.
# https://resend.com/docs/api-reference/emails/send-email
#
# pkg:gem/resend#lib/resend/mailer.rb:13
Resend::Mailer::IGNORED_HEADERS = T.let(T.unsafe(nil), Array)

# pkg:gem/resend#lib/resend/mailer.rb:21
Resend::Mailer::SUPPORTED_OPTIONS = T.let(T.unsafe(nil), Array)

# Handles multipart/form-data requests (file uploads).
# Builds the multipart body directly instead of relying on HTTParty's
# duck-typing file detection, which requires a :path method.
#
# pkg:gem/resend#lib/resend/multipart_request.rb:9
class Resend::MultipartRequest < ::Resend::Request
  private

  # pkg:gem/resend#lib/resend/multipart_request.rb:21
  def build_multipart_body(boundary); end

  # pkg:gem/resend#lib/resend/multipart_request.rb:15
  def build_request_options; end

  # pkg:gem/resend#lib/resend/multipart_request.rb:52
  def optional_fields; end

  # pkg:gem/resend#lib/resend/multipart_request.rb:31
  def part(boundary, name, value, filename: T.unsafe(nil), content_type: T.unsafe(nil)); end

  # pkg:gem/resend#lib/resend/multipart_request.rb:42
  def read_file(file_data); end

  # pkg:gem/resend#lib/resend/multipart_request.rb:61
  def serialize_json(value); end
end

# pkg:gem/resend#lib/resend/multipart_request.rb:10
Resend::MultipartRequest::NEWLINE = T.let(T.unsafe(nil), String)

# oauth grants api wrapper
#
# pkg:gem/resend#lib/resend/oauth_grants.rb:5
module Resend::OAuthGrants
  class << self
    # https://resend.com/docs/api-reference/oauth/list-grants
    #
    # pkg:gem/resend#lib/resend/oauth_grants.rb:8
    def list(params = T.unsafe(nil)); end

    # https://resend.com/docs/api-reference/oauth/revoke-grant
    #
    # pkg:gem/resend#lib/resend/oauth_grants.rb:14
    def revoke(oauth_grant_id = T.unsafe(nil)); end
  end
end

# Helper class for building paginated query strings
#
# pkg:gem/resend#lib/resend/pagination_helper.rb:5
class Resend::PaginationHelper
  class << self
    # Builds a paginated path with query parameters
    #
    # @param base_path [String] the base API path
    # @param query_params [Hash] optional pagination parameters
    # @option query_params [Integer] :limit Number of items to retrieve (max 100)
    # @option query_params [String] :after ID after which to retrieve more items
    # @option query_params [String] :before ID before which to retrieve more items
    # @return [String] the path with query parameters
    #
    # pkg:gem/resend#lib/resend/pagination_helper.rb:15
    def build_paginated_path(base_path, query_params = T.unsafe(nil)); end
  end
end

# Main railtime class
#
# pkg:gem/resend#lib/resend/railtie.rb:8
class Resend::Railtie < ::Rails::Railtie; end

# This class is responsible for making the appropriate HTTP calls
# and raising the specific errors based on the response.
#
# pkg:gem/resend#lib/resend/request.rb:6
class Resend::Request
  # pkg:gem/resend#lib/resend/request.rb:11
  def initialize(path = T.unsafe(nil), body = T.unsafe(nil), verb = T.unsafe(nil), options: T.unsafe(nil)); end

  # pkg:gem/resend#lib/resend/request.rb:9
  def body; end

  # pkg:gem/resend#lib/resend/request.rb:9
  def body=(_arg0); end

  # pkg:gem/resend#lib/resend/request.rb:43
  def handle_error!(data, resp = T.unsafe(nil)); end

  # pkg:gem/resend#lib/resend/request.rb:9
  def options; end

  # pkg:gem/resend#lib/resend/request.rb:9
  def options=(_arg0); end

  # Performs the HTTP call
  #
  # pkg:gem/resend#lib/resend/request.rb:32
  def perform; end

  # pkg:gem/resend#lib/resend/request.rb:9
  def verb; end

  # pkg:gem/resend#lib/resend/request.rb:9
  def verb=(_arg0); end

  private

  # pkg:gem/resend#lib/resend/request.rb:55
  def build_request_options; end

  # pkg:gem/resend#lib/resend/request.rb:101
  def check_json!(resp); end

  # pkg:gem/resend#lib/resend/request.rb:80
  def error_response?(resp); end

  # Extract and normalize headers from the HTTParty response
  #
  # pkg:gem/resend#lib/resend/request.rb:112
  def extract_headers(resp); end

  # pkg:gem/resend#lib/resend/request.rb:67
  def get_request_with_query?; end

  # pkg:gem/resend#lib/resend/request.rb:71
  def process_response(resp); end

  # pkg:gem/resend#lib/resend/request.rb:93
  def set_batch_validation; end

  # pkg:gem/resend#lib/resend/request.rb:84
  def set_idempotency_key; end
end

# pkg:gem/resend#lib/resend/request.rb:7
Resend::Request::BASE_URL = T.let(T.unsafe(nil), String)

# Response wrapper that maintains backwards compatibility while exposing headers
#
# This class wraps API responses and behaves like a Hash for backwards compatibility,
# while also providing access to response headers via the #headers method.
#
# @example Backwards compatible hash access
#   response = Resend::Emails.send(params)
#   response[:id]  # => "49a3999c-0ce1-4ea6-ab68-afcd6dc2e794"
#
# @example Accessing response headers
#   response = Resend::Emails.send(params)
#   response.headers  # => {"content-type" => "application/json", ...}
#   response.headers['x-ratelimit-remaining']  # => "50"
#
# pkg:gem/resend#lib/resend/response.rb:17
class Resend::Response
  include ::Enumerable

  # @param data [Hash] The response data
  # @param headers [Hash, HTTParty::Response] The response headers
  #
  # pkg:gem/resend#lib/resend/response.rb:22
  def initialize(data, headers); end

  # Hash-like access via []
  # @param key [Symbol, String] The key to access
  # @return [Object] The value at the key
  #
  # pkg:gem/resend#lib/resend/response.rb:34
  def [](key); end

  # Hash-like assignment via []=
  # @param key [Symbol, String] The key to set
  # @param value [Object] The value to set
  #
  # pkg:gem/resend#lib/resend/response.rb:41
  def []=(key, value); end

  # Serialize response data for encoders that call as_json, such as ActiveSupport
  # @param args [Array] Options forwarded to Hash#as_json when it is defined
  # @return [Hash] The response data in as_json form
  #
  # pkg:gem/resend#lib/resend/response.rb:69
  def as_json(*args); end

  # Dig into nested hash structure
  # @param keys [Array<Symbol, String>] Keys to dig through
  # @return [Object] The value at the nested key path
  #
  # pkg:gem/resend#lib/resend/response.rb:48
  def dig(*keys); end

  # Enable enumeration over the data
  #
  # pkg:gem/resend#lib/resend/response.rb:95
  def each(&block); end

  # Check if response is empty
  # @return [Boolean] True if data is empty
  #
  # pkg:gem/resend#lib/resend/response.rb:108
  def empty?; end

  # pkg:gem/resend#lib/resend/response.rb:92
  def has_key?(key); end

  # Access response headers
  # @return [Hash] Response headers as a hash with lowercase string keys
  #
  # pkg:gem/resend#lib/resend/response.rb:29
  def headers; end

  # String representation for debugging
  # @return [String] String representation of the response
  #
  # pkg:gem/resend#lib/resend/response.rb:130
  def inspect; end

  # Check if key exists
  # @param key [Symbol, String] The key to check
  # @return [Boolean] True if key exists
  #
  # pkg:gem/resend#lib/resend/response.rb:88
  def key?(key); end

  # Get all keys from the data
  # @return [Array] Array of keys
  #
  # pkg:gem/resend#lib/resend/response.rb:75
  def keys; end

  # Delegate unknown methods to the underlying data hash
  #
  # pkg:gem/resend#lib/resend/response.rb:118
  def method_missing(method_name, *args, &block); end

  # Convert to plain hash
  # @return [Hash] The underlying data hash
  #
  # pkg:gem/resend#lib/resend/response.rb:54
  def to_h; end

  # pkg:gem/resend#lib/resend/response.rb:58
  def to_hash; end

  # Serialize response data without response headers
  # @return [String] JSON representation of the response data
  #
  # pkg:gem/resend#lib/resend/response.rb:62
  def to_json(*args); end

  # Transform keys in the underlying data
  # @return [Resend::Response] Self for chaining
  #
  # pkg:gem/resend#lib/resend/response.rb:101
  def transform_keys!(&block); end

  # Get all values from the data
  # @return [Array] Array of values
  #
  # pkg:gem/resend#lib/resend/response.rb:81
  def values; end

  private

  # Normalize headers to a simple hash with lowercase string keys
  # @param headers [Hash, HTTParty::Response, nil] The headers to normalize
  # @return [Hash] Normalized headers hash
  #
  # pkg:gem/resend#lib/resend/response.rb:139
  def normalize_headers(headers); end

  # Respond to hash-like methods
  #
  # pkg:gem/resend#lib/resend/response.rb:113
  def respond_to_missing?(method_name, include_private = T.unsafe(nil)); end
end

# Segments api wrapper
#
# pkg:gem/resend#lib/resend/segments.rb:5
module Resend::Segments
  class << self
    # https://resend.com/docs/api-reference/segments/create-segment
    #
    # pkg:gem/resend#lib/resend/segments.rb:8
    def create(params); end

    # https://resend.com/docs/api-reference/segments/get-segment
    #
    # pkg:gem/resend#lib/resend/segments.rb:14
    def get(segment_id = T.unsafe(nil)); end

    # https://resend.com/docs/api-reference/segments/list-segments
    #
    # pkg:gem/resend#lib/resend/segments.rb:26
    def list(params = T.unsafe(nil)); end

    # https://resend.com/docs/api-reference/segments/delete-segment
    #
    # pkg:gem/resend#lib/resend/segments.rb:32
    def remove(segment_id = T.unsafe(nil)); end

    # https://resend.com/docs/api-reference/segments/update-segment
    #
    # pkg:gem/resend#lib/resend/segments.rb:20
    def update(params = T.unsafe(nil)); end
  end
end

# Suppressions API wrapper
#
# pkg:gem/resend#lib/resend/suppressions.rb:5
module Resend::Suppressions
  class << self
    # Add an email address to the suppression list. Suppressed addresses are
    # skipped by future sends. Adding an address that is already suppressed
    # succeeds and returns the existing suppression.
    #
    # @param params [Hash] the parameters
    # @option params [String] :email the email address to suppress (required).
    #   The API lowercases and trims it.
    #
    # https://resend.com/docs/api-reference/suppressions/add-suppression
    #
    # pkg:gem/resend#lib/resend/suppressions.rb:17
    def add(params); end

    # Retrieve a single suppression. The API returns 404 'Suppression not found'
    # when the address or ID is not suppressed.
    #
    # @param id_or_email [String] the suppression ID or the suppressed email address (required)
    #
    # https://resend.com/docs/api-reference/suppressions/get-suppression
    #
    # pkg:gem/resend#lib/resend/suppressions.rb:44
    def get(id_or_email); end

    # Retrieve a list of suppressions. Each entry has `id`, `email`, `origin`,
    # `source_id` and `created_at`; unlike `get`, list entries carry no `object` key.
    #
    # @param params [Hash] optional filtering and pagination parameters
    # @option params [String] :origin filter by origin: 'bounce', 'complaint' or 'manual'
    # @option params [Integer] :limit number of results to return (1-100)
    # @option params [String] :after cursor for forward pagination
    # @option params [String] :before cursor for backward pagination
    #
    # https://resend.com/docs/api-reference/suppressions/list-suppressions
    #
    # pkg:gem/resend#lib/resend/suppressions.rb:32
    def list(params = T.unsafe(nil)); end

    # Remove a single suppression, which allows sending to that address again.
    # The API returns 404 'Suppression not found' when the address or ID is not suppressed.
    #
    # @param id_or_email [String] the suppression ID or the suppressed email address (required)
    #
    # https://resend.com/docs/api-reference/suppressions/remove-suppression
    #
    # pkg:gem/resend#lib/resend/suppressions.rb:57
    def remove(id_or_email); end
  end
end

# Suppressions Batch API wrapper
#
# pkg:gem/resend#lib/resend/suppressions/batch.rb:6
module Resend::Suppressions::Batch
  class << self
    # Add up to 100 email addresses to the suppression list at once. Addresses that
    # are already suppressed come back with their existing suppression instead of failing.
    #
    # @param params [Hash] the parameters
    # @option params [Array<String>] :emails the email addresses to suppress (required, 1 to 100).
    #   The API lowercases and trims them.
    #
    # https://resend.com/docs/api-reference/suppressions/add-suppressions
    #
    # pkg:gem/resend#lib/resend/suppressions/batch.rb:17
    def add(params); end

    # Remove up to 100 suppressions at once, either by email address or by
    # suppression ID. Provide exactly one of `emails` or `ids`.
    #
    # @param params [Hash] the parameters
    # @option params [Array<String>] :emails the email addresses to remove (1 to 100)
    # @option params [Array<String>] :ids the suppression IDs to remove (1 to 100), as UUIDs
    #
    # https://resend.com/docs/api-reference/suppressions/remove-suppressions
    #
    # pkg:gem/resend#lib/resend/suppressions/batch.rb:30
    def remove(params); end
  end
end

# Templates api wrapper
#
# pkg:gem/resend#lib/resend/templates.rb:5
module Resend::Templates
  class << self
    # https://resend.com/docs/api-reference/templates/create-template
    #
    # pkg:gem/resend#lib/resend/templates.rb:8
    def create(params = T.unsafe(nil)); end

    # https://resend.com/docs/api-reference/templates/duplicate-template
    #
    # pkg:gem/resend#lib/resend/templates.rb:32
    def duplicate(template_id = T.unsafe(nil)); end

    # https://resend.com/docs/api-reference/templates/get-template
    #
    # pkg:gem/resend#lib/resend/templates.rb:14
    def get(template_id = T.unsafe(nil)); end

    # https://resend.com/docs/api-reference/templates/list-templates
    #
    # pkg:gem/resend#lib/resend/templates.rb:38
    def list(params = T.unsafe(nil)); end

    # https://resend.com/docs/api-reference/templates/publish-template
    #
    # pkg:gem/resend#lib/resend/templates.rb:26
    def publish(template_id = T.unsafe(nil)); end

    # https://resend.com/docs/api-reference/templates/delete-template
    #
    # pkg:gem/resend#lib/resend/templates.rb:44
    def remove(template_id = T.unsafe(nil)); end

    # https://resend.com/docs/api-reference/templates/update-template
    #
    # pkg:gem/resend#lib/resend/templates.rb:20
    def update(template_id, params = T.unsafe(nil)); end
  end
end

# Topics api wrapper
#
# pkg:gem/resend#lib/resend/topics.rb:5
module Resend::Topics
  class << self
    # https://resend.com/docs/api-reference/topics/create-topic
    #
    # pkg:gem/resend#lib/resend/topics.rb:8
    def create(params = T.unsafe(nil)); end

    # https://resend.com/docs/api-reference/topics/get-topic
    #
    # pkg:gem/resend#lib/resend/topics.rb:14
    def get(topic_id = T.unsafe(nil)); end

    # https://resend.com/docs/api-reference/topics/list-topics
    #
    # pkg:gem/resend#lib/resend/topics.rb:26
    def list(params = T.unsafe(nil)); end

    # https://resend.com/docs/api-reference/topics/delete-topic
    #
    # pkg:gem/resend#lib/resend/topics.rb:32
    def remove(topic_id = T.unsafe(nil)); end

    # https://resend.com/docs/api-reference/topics/update-topic
    #
    # pkg:gem/resend#lib/resend/topics.rb:20
    def update(params = T.unsafe(nil)); end
  end
end

# pkg:gem/resend#lib/resend/version.rb:4
Resend::VERSION = T.let(T.unsafe(nil), String)

# The Webhooks module provides methods for managing webhooks via the Resend API.
# Webhooks allow you to receive real-time notifications about email events.
#
# Default tolerance for timestamp validation (5 minutes)
#
# pkg:gem/resend#lib/resend/webhooks.rb:11
Resend::WEBHOOK_TOLERANCE_SECONDS = T.let(T.unsafe(nil), Integer)

# @example Create a webhook
#   Resend::Webhooks.create(
#     endpoint: "https://webhook.example.com/handler",
#     events: ["email.sent", "email.delivered", "email.bounced"]
#   )
#
# @example List all webhooks
#   Resend::Webhooks.list
#
# @example Retrieve a specific webhook
#   Resend::Webhooks.get("4dd369bc-aa82-4ff3-97de-514ae3000ee0")
#
# @example Update a webhook
#   Resend::Webhooks.update(
#     webhook_id: "430eed87-632a-4ea6-90db-0aace67ec228",
#     endpoint: "https://new-webhook.example.com/handler",
#     events: ["email.sent", "email.delivered"],
#     status: "enabled"
#   )
#
# @example Delete a webhook
#   Resend::Webhooks.remove("4dd369bc-aa82-4ff3-97de-514ae3000ee0")
#
# pkg:gem/resend#lib/resend/webhooks.rb:35
module Resend::Webhooks
  class << self
    # Create a new webhook to receive real-time notifications about email events
    #
    # @param params [Hash] The webhook parameters
    # @option params [String] :endpoint The URL where webhook events will be sent (required)
    # @option params [Array<String>] :events Array of event types to subscribe to (required)
    #
    # @return [Hash] The webhook object containing id, object type, and signing_secret
    #
    # @example
    #   Resend::Webhooks.create(
    #     endpoint: "https://webhook.example.com/handler",
    #     events: ["email.sent", "email.delivered", "email.bounced"]
    #   )
    #
    # pkg:gem/resend#lib/resend/webhooks.rb:50
    def create(params = T.unsafe(nil)); end

    # Retrieve a single webhook for the authenticated user
    #
    # @param webhook_id [String] The webhook ID
    #
    # @return [Hash] The webhook object with full details
    #
    # @example
    #   Resend::Webhooks.get("4dd369bc-aa82-4ff3-97de-514ae3000ee0")
    #
    # pkg:gem/resend#lib/resend/webhooks.rb:82
    def get(webhook_id = T.unsafe(nil)); end

    # Retrieve a webhook event
    #
    # @param webhook_id [String] The webhook ID
    # @param event_id [String] The webhook event ID
    #
    # @return [Hash] The webhook event with full details
    #
    # @example
    #   Resend::Webhooks.get_event("4dd369bc-aa82-4ff3-97de-514ae3000ee0", "msg_123")
    #
    # pkg:gem/resend#lib/resend/webhooks.rb:115
    def get_event(webhook_id, event_id); end

    # Retrieve a list of webhooks for the authenticated user
    #
    # @param params [Hash] The pagination parameters
    # @option params [Integer] :limit Number of webhooks to retrieve (max: 100, min: 1)
    # @option params [String] :after The ID after which to retrieve more webhooks (for pagination)
    # @option params [String] :before The ID before which to retrieve more webhooks (for pagination)
    #
    # @return [Hash] A paginated list of webhook objects
    #
    # @example
    #   Resend::Webhooks.list
    #
    # @example With pagination
    #   Resend::Webhooks.list(limit: 20, after: "4dd369bc-aa82-4ff3-97de-514ae3000ee0")
    #
    # pkg:gem/resend#lib/resend/webhooks.rb:69
    def list(params = T.unsafe(nil)); end

    # Retrieve delivery attempts for a webhook event
    #
    # @param webhook_id [String] The webhook ID
    # @param event_id [String] The webhook event ID
    # @param params [Hash] The pagination parameters
    # @option params [Integer] :limit Number of delivery attempts to retrieve (max: 100, min: 1)
    # @option params [String] :after The ID after which to retrieve more delivery attempts
    #
    # @return [Hash] A paginated list of webhook event delivery attempts
    #
    # @example
    #   Resend::Webhooks.list_event_attempts("4dd369bc-aa82-4ff3-97de-514ae3000ee0", "msg_123")
    #
    # @example With pagination
    #   Resend::Webhooks.list_event_attempts(
    #     "4dd369bc-aa82-4ff3-97de-514ae3000ee0",
    #     "msg_123",
    #     limit: 20,
    #     after: "atmpt_123"
    #   )
    #
    # pkg:gem/resend#lib/resend/webhooks.rb:156
    def list_event_attempts(webhook_id, event_id, params = T.unsafe(nil)); end

    # Retrieve webhook events
    #
    # @param webhook_id [String] The webhook ID
    # @param params [Hash] The pagination parameters
    # @option params [Integer] :limit Number of webhook events to retrieve (max: 100, min: 1)
    # @option params [String] :after The ID after which to retrieve more webhook events
    #
    # @return [Hash] A paginated list of webhook events
    #
    # @example
    #   Resend::Webhooks.list_events("4dd369bc-aa82-4ff3-97de-514ae3000ee0")
    #
    # @example With pagination
    #   Resend::Webhooks.list_events("4dd369bc-aa82-4ff3-97de-514ae3000ee0", limit: 20, after: "msg_123")
    #
    # pkg:gem/resend#lib/resend/webhooks.rb:101
    def list_events(webhook_id, params = T.unsafe(nil)); end

    # Remove an existing webhook
    #
    # @param webhook_id [String] The webhook ID
    #
    # @return [Hash] Confirmation object with id, object type, and deleted status
    #
    # @example
    #   Resend::Webhooks.remove("4dd369bc-aa82-4ff3-97de-514ae3000ee0")
    #
    # pkg:gem/resend#lib/resend/webhooks.rb:208
    def remove(webhook_id = T.unsafe(nil)); end

    # Replay a webhook event
    #
    # Queues one more delivery of the event to the webhook. Manual replays do not schedule automatic retries.
    #
    # @param webhook_id [String] The webhook ID
    # @param event_id [String] The webhook event ID
    #
    # @return [Hash] The replayed webhook event id and object type
    #
    # @example
    #   Resend::Webhooks.replay_event("4dd369bc-aa82-4ff3-97de-514ae3000ee0", "msg_123")
    #
    # pkg:gem/resend#lib/resend/webhooks.rb:131
    def replay_event(webhook_id, event_id); end

    # Rotate the signing secret of a webhook
    #
    # Generates a new signing secret for the webhook. The previous secret keeps working for 24 hours.
    #
    # @param webhook_id [String] The webhook ID
    #
    # @return [Hash] The webhook object containing id, object type, and the new signing_secret
    #
    # @example
    #   Resend::Webhooks.rotate_signing_secret("4dd369bc-aa82-4ff3-97de-514ae3000ee0")
    #
    # pkg:gem/resend#lib/resend/webhooks.rb:195
    def rotate_signing_secret(webhook_id); end

    # Update an existing webhook configuration
    #
    # @param params [Hash] The webhook update parameters
    # @option params [String] :webhook_id The webhook ID (required)
    # @option params [String] :endpoint The URL where webhook events will be sent
    # @option params [Array<String>] :events Array of event types to subscribe to
    # @option params [String] :status The webhook status ("enabled" or "disabled")
    #
    # @return [Hash] The updated webhook object
    #
    # @example
    #   Resend::Webhooks.update(
    #     webhook_id: "430eed87-632a-4ea6-90db-0aace67ec228",
    #     endpoint: "https://new-webhook.example.com/handler",
    #     events: ["email.sent", "email.delivered"],
    #     status: "enabled"
    #   )
    #
    # pkg:gem/resend#lib/resend/webhooks.rb:179
    def update(params = T.unsafe(nil)); end

    # Verify a webhook payload using HMAC-SHA256 signature validation
    # This validates that the webhook request came from Resend and hasn't been tampered with
    #
    # @param params [Hash] The webhook verification parameters
    # @option params [String] :payload The raw webhook payload body (required)
    # @option params [Hash] :headers The webhook headers containing svix-id, svix-timestamp,
    #   and svix-signature (required)
    # @option params [String] :webhook_secret The signing secret from webhook creation (required)
    #
    # @return [Boolean] true if verification succeeds
    # @raise [StandardError] If verification fails or required parameters are missing
    #
    # @example
    #   Resend::Webhooks.verify(
    #     payload: request.body.read,
    #     headers: {
    #       svix_id: "id_1234567890abcdefghijklmnopqrstuvwxyz",
    #       svix_timestamp: "1616161616",
    #       svix_signature: "v1,signature_here"
    #     },
    #     webhook_secret: "whsec_1234567890abcdez"
    #   )
    #
    # pkg:gem/resend#lib/resend/webhooks.rb:235
    def verify(params = T.unsafe(nil)); end

    private

    # Decode the signing secret (strip whsec_ prefix and base64 decode)
    #
    # pkg:gem/resend#lib/resend/webhooks.rb:288
    def decode_secret(webhook_secret); end

    # Generate HMAC-SHA256 signature and return it as base64
    #
    # pkg:gem/resend#lib/resend/webhooks.rb:310
    def generate_signature(secret, content); end

    # Constant-time string comparison to prevent timing attacks
    #
    # Note: We implement this manually for Ruby 2.7 compatibility.
    # Ruby 3.0+ could use OpenSSL.fixed_length_secure_compare instead.
    #
    # pkg:gem/resend#lib/resend/webhooks.rb:319
    def secure_compare(str_a, str_b); end

    # Validate required headers are present
    #
    # pkg:gem/resend#lib/resend/webhooks.rb:270
    def validate_headers(headers); end

    # Validate payload is present
    #
    # pkg:gem/resend#lib/resend/webhooks.rb:260
    def validate_payload(payload); end

    # Validate required parameters
    #
    # pkg:gem/resend#lib/resend/webhooks.rb:253
    def validate_required_params(payload, headers, webhook_secret); end

    # Validate timestamp to prevent replay attacks
    #
    # pkg:gem/resend#lib/resend/webhooks.rb:277
    def validate_timestamp(timestamp_header); end

    # Validate webhook secret is present
    #
    # pkg:gem/resend#lib/resend/webhooks.rb:265
    def validate_webhook_secret(webhook_secret); end

    # Verify signature using constant-time comparison
    #
    # pkg:gem/resend#lib/resend/webhooks.rb:296
    def verify_signature(signature_header, expected_signature); end
  end
end
