# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `ruby2ruby` gem.
# Please instead update this file by running `bin/tapioca gem ruby2ruby`.


# pkg:gem/ruby2ruby#lib/ruby2ruby.rb:17
Regexp::CODES = T.let(T.unsafe(nil), Hash)

# Generate ruby code from a sexp.
#
# pkg:gem/ruby2ruby#lib/ruby2ruby.rb:33
class Ruby2Ruby < ::SexpProcessor
  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:82
  def initialize; end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:383
  def __var(name); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:353
  def comments(exp); end

  # Generate a post-or-pre conditional loop.
  #
  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:1330
  def cond_loop(exp, name); end

  # Utility method to escape something interpolated.
  #
  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:1355
  def dthing_escape(type, lit); end

  # Indent all lines of +s+ to the current indent level.
  #
  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:1372
  def indent(s); end

  # Wrap appropriate expressions in matching parens.
  #
  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:1379
  def parenthesize(exp); end

  # Processors
  #
  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:97
  def process_alias(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:103
  def process_and(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:109
  def process_arglist(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:118
  def process_args(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:158
  def process_array(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:635
  def process_array_pat(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:162
  def process_attrasgn(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:184
  def process_back_ref(exp); end

  # TODO: figure out how to do rescue and ensure ENTIRELY w/o begin
  #
  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:191
  def process_begin(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:205
  def process_block(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:219
  def process_block_pass(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:227
  def process_break(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:239
  def process_call(exp, safe_call = T.unsafe(nil)); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:313
  def process_case(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:342
  def process_cdecl(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:359
  def process_class(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:363
  def process_colon2(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:369
  def process_colon3(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:375
  def process_const(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:394
  def process_cvar(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:400
  def process_cvasgn(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:406
  def process_cvdecl(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:412
  def process_defined(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:421
  def process_defn(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:459
  def process_defs(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:471
  def process_dot2(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:477
  def process_dot3(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:483
  def process_dregx(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:491
  def process_dregx_once(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:495
  def process_dstr(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:499
  def process_dsym(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:503
  def process_dxstr(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:507
  def process_ensure(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:521
  def process_evstr(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:527
  def process_false(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:624
  def process_find_pat(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:531
  def process_flip2(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:537
  def process_flip3(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:543
  def process_for(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:557
  def process_forward_args(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:561
  def process_gasgn(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:565
  def process_gvar(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:571
  def process_hash(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:658
  def process_hash_pat(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:598
  def process_iasgn(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:695
  def process_if(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:608
  def process_in(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:740
  def process_iter(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:804
  def process_ivar(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:652
  def process_kwrest(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:810
  def process_kwsplat(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:734
  def process_lambda(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:815
  def process_lasgn(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:832
  def process_lit(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:842
  def process_lvar(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:848
  def process_masgn(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:873
  def process_match(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:879
  def process_match2(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:889
  def process_match3(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:903
  def process_module(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:907
  def process_next(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:918
  def process_nil(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:922
  def process_not(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:927
  def process_nth_ref(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:932
  def process_op_asgn(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:953
  def process_op_asgn1(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:964
  def process_op_asgn2(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:975
  def process_op_asgn_and(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:982
  def process_op_asgn_or(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:989
  def process_or(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:1003
  def process_postexe(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:691
  def process_preexe(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:1007
  def process_redo(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:1011
  def process_resbody(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:1030
  def process_rescue(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:1060
  def process_retry(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:1064
  def process_return(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:1077
  def process_safe_attrasgn(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:309
  def process_safe_call(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:1095
  def process_safe_op_asgn(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:1105
  def process_safe_op_asgn2(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:1117
  def process_sclass(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:1126
  def process_self(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:1130
  def process_splat(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:1139
  def process_str(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:1144
  def process_super(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:1154
  def process_svalue(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:1162
  def process_to_ary(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:1168
  def process_true(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:1172
  def process_undef(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:1178
  def process_until(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:1182
  def process_valias(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:1188
  def process_when(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:1203
  def process_while(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:1207
  def process_xstr(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:1211
  def process_yield(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:1225
  def process_zsuper(exp); end

  # Return the appropriate regexp flags for a given numeric code.
  #
  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:1391
  def re_opt(options); end

  # Rewriters:
  #
  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:1232
  def rewrite_attrasgn(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:1242
  def rewrite_call(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:1250
  def rewrite_ensure(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:1255
  def rewrite_if(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:1266
  def rewrite_resbody(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:1274
  def rewrite_rescue(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:1291
  def rewrite_svalue(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:1302
  def rewrite_until(exp); end

  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:1313
  def rewrite_while(exp); end

  # Return a splatted symbol for +sym+.
  #
  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:1400
  def splat(sym); end

  # Utility method to generate something interpolated.
  #
  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:1407
  def util_dthing(type, exp); end

  # Utility method to generate ether a module or class.
  #
  # pkg:gem/ruby2ruby#lib/ruby2ruby.rb:1430
  def util_module_or_class(exp, is_class = T.unsafe(nil)); end
end

# Nodes that represent assignment and probably need () around them.
#
# TODO: this should be replaced with full precedence support :/
#
# pkg:gem/ruby2ruby#lib/ruby2ruby.rb:47
Ruby2Ruby::ASSIGN_NODES = T.let(T.unsafe(nil), Array)

# binary operation messages
#
# pkg:gem/ruby2ruby#lib/ruby2ruby.rb:40
Ruby2Ruby::BINARY = T.let(T.unsafe(nil), Array)

# Some sexp types are OK without parens when appearing as hash values.
# This list can include `:call`s because they're always printed with parens
# around their arguments. For example:
#
#     { :foo => (bar("baz")) } # The outer parens are unnecessary
#     { :foo => bar("baz") }   # This is the normal code style
#
# pkg:gem/ruby2ruby#lib/ruby2ruby.rb:72
Ruby2Ruby::HASH_VAL_NO_PAREN = T.let(T.unsafe(nil), Array)

# cutoff for one-liners
#
# pkg:gem/ruby2ruby#lib/ruby2ruby.rb:37
Ruby2Ruby::LINE_LENGTH = T.let(T.unsafe(nil), Integer)

# pkg:gem/ruby2ruby#lib/ruby2ruby.rb:738
Ruby2Ruby::MUST_BE_CURLY = T.let(T.unsafe(nil), Array)

# pkg:gem/ruby2ruby#lib/ruby2ruby.rb:34
Ruby2Ruby::VERSION = T.let(T.unsafe(nil), String)
