# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `schematist` gem.
# Please instead update this file by running `bin/tapioca gem schematist`.


# pkg:gem/schematist#lib/schematist/version.rb:3
module Schematist; end

# Annotations describe a schema for humans and tools. They carry no validation weight.
#
# pkg:gem/schematist#lib/schematist.rb:12
Schematist::ANNOTATIONS = T.let(T.unsafe(nil), Hash)

# Core keywords identify a schema and point at other schemas.
#
# pkg:gem/schematist#lib/schematist.rb:23
Schematist::CORE_KEYWORDS = T.let(T.unsafe(nil), Hash)

# pkg:gem/schematist#lib/schematist/dsl/schema_builders.rb:4
module Schematist::DSL
  include ::Schematist::DSL::SchemaBuilders
  include ::Schematist::DSL::PrimitiveTypes
  include ::Schematist::DSL::ComplexTypes
  include ::Schematist::DSL::Conditionals
  include ::Schematist::DSL::Utilities
end

# pkg:gem/schematist#lib/schematist/dsl/complex_types.rb:5
module Schematist::DSL::ComplexTypes
  # pkg:gem/schematist#lib/schematist/dsl/complex_types.rb:26
  def all_of(name = T.unsafe(nil), description: T.unsafe(nil), required: T.unsafe(nil), requires: T.unsafe(nil), **options, &block); end

  # pkg:gem/schematist#lib/schematist/dsl/complex_types.rb:18
  def any_of(name = T.unsafe(nil), description: T.unsafe(nil), required: T.unsafe(nil), requires: T.unsafe(nil), **options, &block); end

  # pkg:gem/schematist#lib/schematist/dsl/complex_types.rb:10
  def array(name = T.unsafe(nil), description: T.unsafe(nil), required: T.unsafe(nil), requires: T.unsafe(nil), **options, &block); end

  # pkg:gem/schematist#lib/schematist/dsl/complex_types.rb:30
  def none_of(name = T.unsafe(nil), description: T.unsafe(nil), required: T.unsafe(nil), requires: T.unsafe(nil), **options, &block); end

  # pkg:gem/schematist#lib/schematist/dsl/complex_types.rb:6
  def object(name = T.unsafe(nil), description: T.unsafe(nil), required: T.unsafe(nil), requires: T.unsafe(nil), **options, &block); end

  # pkg:gem/schematist#lib/schematist/dsl/complex_types.rb:22
  def one_of(name = T.unsafe(nil), description: T.unsafe(nil), required: T.unsafe(nil), requires: T.unsafe(nil), **options, &block); end

  # pkg:gem/schematist#lib/schematist/dsl/complex_types.rb:41
  def optional(name, description: T.unsafe(nil), &block); end

  # Emits a schema fragment verbatim, for the corners of JSON Schema this DSL does not cover
  #
  # pkg:gem/schematist#lib/schematist/dsl/complex_types.rb:35
  def raw(name, schema = T.unsafe(nil), required: T.unsafe(nil), requires: T.unsafe(nil)); end

  # pkg:gem/schematist#lib/schematist/dsl/complex_types.rb:14
  def tuple(name = T.unsafe(nil), description: T.unsafe(nil), required: T.unsafe(nil), requires: T.unsafe(nil), **options, &block); end
end

# A branch of a conditional. Backed by a schema class, so anything you can write in a schema
# you can write in a branch: nested objects, arrays, composition, references, raw fragments.
# `requires` and `validates` stay as shorthands for the two common cases.
#
# pkg:gem/schematist#lib/schematist/dsl/conditional_builder.rb:8
class Schematist::DSL::ConditionalBuilder
  # pkg:gem/schematist#lib/schematist/dsl/conditional_builder.rb:21
  def initialize; end

  # pkg:gem/schematist#lib/schematist/dsl/conditional_builder.rb:59
  def empty?; end

  # Everything else is the ordinary schema DSL, evaluated against the branch's schema class
  #
  # pkg:gem/schematist#lib/schematist/dsl/conditional_builder.rb:74
  def method_missing(name, *_arg1, **_arg2, &_arg3); end

  # pkg:gem/schematist#lib/schematist/dsl/conditional_builder.rb:63
  def required_fields; end

  # Requires properties without saying anything else about them
  #
  # pkg:gem/schematist#lib/schematist/dsl/conditional_builder.rb:26
  def requires(*fields); end

  # pkg:gem/schematist#lib/schematist/dsl/conditional_builder.rb:48
  def to_schema; end

  # pkg:gem/schematist#lib/schematist/dsl/conditional_builder.rb:30
  def validates(field, **options); end

  # A branch that only lists required properties becomes dependentRequired rather than
  # dependentSchemas, which is the smaller thing to say when it is all you mean.
  #
  # pkg:gem/schematist#lib/schematist/dsl/conditional_builder.rb:69
  def validations_empty?; end

  private

  # pkg:gem/schematist#lib/schematist/dsl/conditional_builder.rb:95
  def additional_properties_set?; end

  # pkg:gem/schematist#lib/schematist/dsl/conditional_builder.rb:86
  def branch_properties; end

  # pkg:gem/schematist#lib/schematist/dsl/conditional_builder.rb:91
  def branch_required; end

  # pkg:gem/schematist#lib/schematist/dsl/conditional_builder.rb:99
  def required; end

  # pkg:gem/schematist#lib/schematist/dsl/conditional_builder.rb:80
  def respond_to_missing?(name, include_private = T.unsafe(nil)); end

  # pkg:gem/schematist#lib/schematist/dsl/conditional_builder.rb:103
  def validations; end
end

# pkg:gem/schematist#lib/schematist/dsl/conditional_builder.rb:9
Schematist::DSL::ConditionalBuilder::VALIDATES_KEY_MAP = T.let(T.unsafe(nil), Hash)

# pkg:gem/schematist#lib/schematist/dsl/conditional_context.rb:5
class Schematist::DSL::ConditionalContext
  # pkg:gem/schematist#lib/schematist/dsl/conditional_context.rb:6
  def initialize(then_builder, else_builder); end

  # Everything else describes the then branch
  #
  # pkg:gem/schematist#lib/schematist/dsl/conditional_context.rb:16
  def method_missing(name, *_arg1, **_arg2, &_arg3); end

  # pkg:gem/schematist#lib/schematist/dsl/conditional_context.rb:11
  def otherwise(&block); end

  private

  # pkg:gem/schematist#lib/schematist/dsl/conditional_context.rb:22
  def respond_to_missing?(name, include_private = T.unsafe(nil)); end
end

# pkg:gem/schematist#lib/schematist/dsl/conditionals.rb:5
module Schematist::DSL::Conditionals
  # pkg:gem/schematist#lib/schematist/dsl/conditionals.rb:6
  def conditions; end

  # pkg:gem/schematist#lib/schematist/dsl/conditionals.rb:10
  def dependencies; end

  # pkg:gem/schematist#lib/schematist/dsl/conditionals.rb:14
  def dependent(property, &block); end

  # Matches on property values, or on any schema when one is passed explicitly:
  #   given(status: "shipped") { ... }
  #   given({required: %w[tax_id]}) { ... }
  #
  # pkg:gem/schematist#lib/schematist/dsl/conditionals.rb:24
  def given(condition = T.unsafe(nil), **properties, &block); end

  private

  # pkg:gem/schematist#lib/schematist/dsl/conditionals.rb:74
  def coerce_condition(value); end

  # pkg:gem/schematist#lib/schematist/dsl/conditionals.rb:46
  def merge_conditions(schema, schema_class); end
end

# pkg:gem/schematist#lib/schematist/dsl/primitive_types.rb:5
module Schematist::DSL::PrimitiveTypes
  # pkg:gem/schematist#lib/schematist/dsl/primitive_types.rb:18
  def boolean(name = T.unsafe(nil), description: T.unsafe(nil), required: T.unsafe(nil), requires: T.unsafe(nil), **options, &block); end

  # pkg:gem/schematist#lib/schematist/dsl/primitive_types.rb:14
  def integer(name = T.unsafe(nil), description: T.unsafe(nil), required: T.unsafe(nil), requires: T.unsafe(nil), **options, &block); end

  # pkg:gem/schematist#lib/schematist/dsl/primitive_types.rb:22
  def null(name = T.unsafe(nil), description: T.unsafe(nil), required: T.unsafe(nil), requires: T.unsafe(nil), **options, &block); end

  # pkg:gem/schematist#lib/schematist/dsl/primitive_types.rb:10
  def number(name = T.unsafe(nil), description: T.unsafe(nil), required: T.unsafe(nil), requires: T.unsafe(nil), **options, &block); end

  # pkg:gem/schematist#lib/schematist/dsl/primitive_types.rb:6
  def string(name = T.unsafe(nil), description: T.unsafe(nil), required: T.unsafe(nil), requires: T.unsafe(nil), **options, &block); end
end

# pkg:gem/schematist#lib/schematist/dsl/schema_builders.rb:5
module Schematist::DSL::SchemaBuilders
  # pkg:gem/schematist#lib/schematist/dsl/schema_builders.rb:142
  def all_of_schema(description: T.unsafe(nil), unevaluated_properties: T.unsafe(nil), unevaluated_items: T.unsafe(nil), **annotations, &block); end

  # pkg:gem/schematist#lib/schematist/dsl/schema_builders.rb:120
  def any_of_schema(description: T.unsafe(nil), unevaluated_properties: T.unsafe(nil), unevaluated_items: T.unsafe(nil), **annotations, &block); end

  # pkg:gem/schematist#lib/schematist/dsl/schema_builders.rb:87
  def array_schema(description: T.unsafe(nil), of: T.unsafe(nil), min_items: T.unsafe(nil), max_items: T.unsafe(nil), unique: T.unsafe(nil), unevaluated_items: T.unsafe(nil), **annotations, &block); end

  # pkg:gem/schematist#lib/schematist/dsl/schema_builders.rb:60
  def boolean_schema(description: T.unsafe(nil), enum: T.unsafe(nil), const: T.unsafe(nil), **annotations, &block); end

  # pkg:gem/schematist#lib/schematist/dsl/schema_builders.rb:43
  def integer_schema(description: T.unsafe(nil), minimum: T.unsafe(nil), maximum: T.unsafe(nil), greater_than: T.unsafe(nil), less_than: T.unsafe(nil), multiple_of: T.unsafe(nil), enum: T.unsafe(nil), const: T.unsafe(nil), format: T.unsafe(nil), **annotations, &block); end

  # pkg:gem/schematist#lib/schematist/dsl/schema_builders.rb:153
  def none_of_schema(description: T.unsafe(nil), unevaluated_properties: T.unsafe(nil), unevaluated_items: T.unsafe(nil), **annotations, &block); end

  # pkg:gem/schematist#lib/schematist/dsl/schema_builders.rb:66
  def null_schema(description: T.unsafe(nil), enum: T.unsafe(nil), **annotations, &block); end

  # pkg:gem/schematist#lib/schematist/dsl/schema_builders.rb:26
  def number_schema(description: T.unsafe(nil), minimum: T.unsafe(nil), maximum: T.unsafe(nil), greater_than: T.unsafe(nil), less_than: T.unsafe(nil), multiple_of: T.unsafe(nil), enum: T.unsafe(nil), const: T.unsafe(nil), format: T.unsafe(nil), **annotations, &block); end

  # pkg:gem/schematist#lib/schematist/dsl/schema_builders.rb:72
  def object_schema(description: T.unsafe(nil), of: T.unsafe(nil), reference: T.unsafe(nil), min_properties: T.unsafe(nil), max_properties: T.unsafe(nil), unevaluated_properties: T.unsafe(nil), **annotations, &block); end

  # pkg:gem/schematist#lib/schematist/dsl/schema_builders.rb:131
  def one_of_schema(description: T.unsafe(nil), unevaluated_properties: T.unsafe(nil), unevaluated_items: T.unsafe(nil), **annotations, &block); end

  # pkg:gem/schematist#lib/schematist/dsl/schema_builders.rb:9
  def string_schema(description: T.unsafe(nil), enum: T.unsafe(nil), const: T.unsafe(nil), min_length: T.unsafe(nil), max_length: T.unsafe(nil), pattern: T.unsafe(nil), format: T.unsafe(nil), content_encoding: T.unsafe(nil), content_media_type: T.unsafe(nil), **annotations, &block); end

  # pkg:gem/schematist#lib/schematist/dsl/schema_builders.rb:101
  def tuple_schema(description: T.unsafe(nil), of: T.unsafe(nil), min_items: T.unsafe(nil), max_items: T.unsafe(nil), unevaluated_items: T.unsafe(nil), **annotations, &block); end

  private

  # Annotations set inside the block are defaults; options and keyword annotations win over them.
  #
  # pkg:gem/schematist#lib/schematist/dsl/schema_builders.rb:168
  def annotate(schema, annotations, schema_block = T.unsafe(nil)); end

  # pkg:gem/schematist#lib/schematist/dsl/schema_builders.rb:176
  def build_object_schema(description, &block); end

  # pkg:gem/schematist#lib/schematist/dsl/schema_builders.rb:229
  def collect_schema_block(&block); end

  # pkg:gem/schematist#lib/schematist/dsl/schema_builders.rb:225
  def collect_schemas_from_block(&_arg0); end

  # pkg:gem/schematist#lib/schematist/dsl/schema_builders.rb:197
  def determine_array_items(of, schema_block = T.unsafe(nil)); end

  # pkg:gem/schematist#lib/schematist/dsl/schema_builders.rb:206
  def determine_object_reference(of, description = T.unsafe(nil)); end

  # pkg:gem/schematist#lib/schematist/dsl/schema_builders.rb:286
  def schema_class_to_inline_schema(schema_class_or_instance); end
end

# What a schema block yields: the schemas declared in it, and the keywords set on the enclosing node
#
# pkg:gem/schematist#lib/schematist/dsl/schema_builders.rb:7
class Schematist::DSL::SchemaBuilders::SchemaBlock < ::Struct
  # pkg:gem/schematist#lib/schematist/dsl/schema_builders.rb:7
  def keywords; end

  # pkg:gem/schematist#lib/schematist/dsl/schema_builders.rb:7
  def keywords=(_); end

  # pkg:gem/schematist#lib/schematist/dsl/schema_builders.rb:7
  def schemas; end

  # pkg:gem/schematist#lib/schematist/dsl/schema_builders.rb:7
  def schemas=(_); end

  class << self
    # pkg:gem/schematist#lib/schematist/dsl/schema_builders.rb:7
    def [](*_arg0); end

    # pkg:gem/schematist#lib/schematist/dsl/schema_builders.rb:7
    def inspect; end

    # pkg:gem/schematist#lib/schematist/dsl/schema_builders.rb:7
    def keyword_init?; end

    # pkg:gem/schematist#lib/schematist/dsl/schema_builders.rb:7
    def members; end

    # pkg:gem/schematist#lib/schematist/dsl/schema_builders.rb:7
    def new(*_arg0); end
  end
end

# pkg:gem/schematist#lib/schematist/dsl/utilities.rb:5
module Schematist::DSL::Utilities
  # Schema definition and reference methods
  #
  # pkg:gem/schematist#lib/schematist/dsl/utilities.rb:7
  def define(name, &_arg1); end

  # Constrains every property name, as JSON Schema propertyNames
  #
  # pkg:gem/schematist#lib/schematist/dsl/utilities.rb:27
  def keys(&block); end

  # Constrains the names of properties matching a pattern, as JSON Schema patternProperties
  #
  # pkg:gem/schematist#lib/schematist/dsl/utilities.rb:19
  def keys_matching(pattern, &block); end

  # pkg:gem/schematist#lib/schematist/dsl/utilities.rb:14
  def object_keywords; end

  # pkg:gem/schematist#lib/schematist/dsl/utilities.rb:31
  def reference(schema_name); end

  private

  # pkg:gem/schematist#lib/schematist/dsl/utilities.rb:71
  def add_property(name, definition, required:, requires: T.unsafe(nil)); end

  # Declares a property when given a name, and what this schema is when not.
  #
  # pkg:gem/schematist#lib/schematist/dsl/utilities.rb:55
  def add_property_or_self(name, definition, required:, requires: T.unsafe(nil)); end

  # Merges everything a schema class collects beyond its properties: annotations, core keywords,
  # key constraints, conditionals. Annotations are defaults, so an option passed to the enclosing
  # builder wins over them.
  #
  # pkg:gem/schematist#lib/schematist/dsl/utilities.rb:64
  def merge_schema_keywords(schema, schema_class); end

  # pkg:gem/schematist#lib/schematist/dsl/utilities.rb:90
  def primitive_type?(type); end

  # pkg:gem/schematist#lib/schematist/dsl/utilities.rb:94
  def schema_class?(type); end

  # What a schema class means as a schema: whatever it declared itself to be, or an object
  # built from its properties.
  #
  # pkg:gem/schematist#lib/schematist/dsl/utilities.rb:43
  def schema_for(schema_class); end
end

# Base error class for all schema-related errors
#
# pkg:gem/schematist#lib/schematist/errors.rb:5
class Schematist::Error < ::StandardError; end

# pkg:gem/schematist#lib/schematist/helpers.rb:4
module Schematist::Helpers
  # pkg:gem/schematist#lib/schematist/helpers.rb:5
  def schema(name = T.unsafe(nil), description: T.unsafe(nil), &block); end
end

# Raised when an invalid array type is specified
#
# pkg:gem/schematist#lib/schematist/errors.rb:15
class Schematist::InvalidArrayTypeError < ::Schematist::Error; end

# Raised when an invalid object type is specified
#
# pkg:gem/schematist#lib/schematist/errors.rb:18
class Schematist::InvalidObjectTypeError < ::Schematist::Error; end

# Raised when schema definition is invalid
#
# pkg:gem/schematist#lib/schematist/errors.rb:21
class Schematist::InvalidSchemaError < ::Schematist::Error; end

# Raised when an invalid schema type is specified
#
# pkg:gem/schematist#lib/schematist/errors.rb:8
class Schematist::InvalidSchemaTypeError < ::Schematist::Error
  # pkg:gem/schematist#lib/schematist/errors.rb:9
  def initialize(type); end
end

# pkg:gem/schematist#lib/schematist/json_output.rb:4
module Schematist::JsonOutput
  # pkg:gem/schematist#lib/schematist/json_output.rb:22
  def to_json(*_args); end

  # A Draft 2020-12 JSON Schema document, string-keyed and ready for any JSON Schema validator
  #
  # pkg:gem/schematist#lib/schematist/json_output.rb:8
  def to_json_schema; end

  private

  # JSON Schema documents are string-keyed. Symbols survive a Ruby comparison but not a JSON round trip.
  #
  # pkg:gem/schematist#lib/schematist/json_output.rb:39
  def json_compatible(value); end

  # Values declared as procs are resolved here, so one schema class can render differently per instance
  #
  # pkg:gem/schematist#lib/schematist/json_output.rb:53
  def resolve_runtime_values(value); end

  # pkg:gem/schematist#lib/schematist/json_output.rb:29
  def schema_body; end
end

# pkg:gem/schematist#lib/schematist/json_output.rb:5
Schematist::JsonOutput::DRAFT_2020_12 = T.let(T.unsafe(nil), String)

# Raised when maximum limits are exceeded
#
# pkg:gem/schematist#lib/schematist/errors.rb:27
class Schematist::LimitExceededError < ::Schematist::Error; end

# pkg:gem/schematist#lib/schematist.rb:9
Schematist::PRIMITIVE_TYPES = T.let(T.unsafe(nil), Array)

# pkg:gem/schematist#lib/schematist/schema.rb:4
class Schematist::Schema
  include ::Schematist::JsonOutput
  extend ::Schematist::DSL::SchemaBuilders
  extend ::Schematist::DSL::PrimitiveTypes
  extend ::Schematist::DSL::ComplexTypes
  extend ::Schematist::DSL::Conditionals
  extend ::Schematist::DSL::Utilities
  extend ::Schematist::DSL

  # pkg:gem/schematist#lib/schematist/schema.rb:156
  def initialize(name = T.unsafe(nil), description: T.unsafe(nil)); end

  # pkg:gem/schematist#lib/schematist/schema.rb:169
  def method_missing(method_name, *_arg1, **_arg2, &_arg3); end

  # pkg:gem/schematist#lib/schematist/schema.rb:165
  def valid?; end

  # pkg:gem/schematist#lib/schematist/schema.rb:161
  def validate!; end

  private

  # pkg:gem/schematist#lib/schematist/schema.rb:177
  def respond_to_missing?(method_name, include_private = T.unsafe(nil)); end

  class << self
    # pkg:gem/schematist#lib/schematist/schema.rb:117
    def additional_properties(value = T.unsafe(nil)); end

    # pkg:gem/schematist#lib/schematist/schema.rb:74
    def anchor(*args); end

    # pkg:gem/schematist#lib/schematist/schema.rb:34
    def annotations; end

    # pkg:gem/schematist#lib/schematist/schema.rb:78
    def comment(*args); end

    # pkg:gem/schematist#lib/schematist/schema.rb:66
    def core_keywords; end

    # pkg:gem/schematist#lib/schematist/schema.rb:9
    def create(&block); end

    # pkg:gem/schematist#lib/schematist/schema.rb:46
    def default(*args); end

    # pkg:gem/schematist#lib/schematist/schema.rb:23
    def definitions; end

    # pkg:gem/schematist#lib/schematist/schema.rb:54
    def deprecated(*args); end

    # pkg:gem/schematist#lib/schematist/schema.rb:42
    def description(*args); end

    # pkg:gem/schematist#lib/schematist/schema.rb:82
    def dynamic_anchor(*args); end

    # pkg:gem/schematist#lib/schematist/schema.rb:86
    def dynamic_ref(*args); end

    # pkg:gem/schematist#lib/schematist/schema.rb:50
    def examples(*args); end

    # pkg:gem/schematist#lib/schematist/schema.rb:70
    def id(*args); end

    # pkg:gem/schematist#lib/schematist/schema.rb:105
    def max_properties(value = T.unsafe(nil)); end

    # pkg:gem/schematist#lib/schematist/schema.rb:101
    def min_properties(value = T.unsafe(nil)); end

    # pkg:gem/schematist#lib/schematist/schema.rb:27
    def name(name = T.unsafe(nil)); end

    # pkg:gem/schematist#lib/schematist/schema.rb:15
    def properties; end

    # pkg:gem/schematist#lib/schematist/schema.rb:58
    def read_only(*args); end

    # pkg:gem/schematist#lib/schematist/schema.rb:19
    def required_properties; end

    # The schema this class is, when it is not an object built from properties. Set by
    # calling a type without a name: `string enum: %w[a b]` rather than `string :status`.
    #
    # pkg:gem/schematist#lib/schematist/schema.rb:96
    def self_schema(definition = T.unsafe(nil)); end

    # pkg:gem/schematist#lib/schematist/schema.rb:38
    def title(*args); end

    # pkg:gem/schematist#lib/schematist/schema.rb:113
    def unevaluated_items(value = T.unsafe(nil)); end

    # pkg:gem/schematist#lib/schematist/schema.rb:109
    def unevaluated_properties(value = T.unsafe(nil)); end

    # pkg:gem/schematist#lib/schematist/schema.rb:128
    def valid?; end

    # pkg:gem/schematist#lib/schematist/schema.rb:123
    def validate!; end

    # pkg:gem/schematist#lib/schematist/schema.rb:90
    def vocabulary(*args); end

    # pkg:gem/schematist#lib/schematist/schema.rb:62
    def write_only(*args); end

    private

    # pkg:gem/schematist#lib/schematist/schema.rb:141
    def annotation(name, *args); end

    # pkg:gem/schematist#lib/schematist/schema.rb:145
    def core_keyword(name, *args); end

    # pkg:gem/schematist#lib/schematist/schema.rb:135
    def object_keyword(keyword, value); end

    # pkg:gem/schematist#lib/schematist/schema.rb:149
    def read_or_write(store, keyword, *args); end
  end
end

# pkg:gem/schematist#lib/schematist/version.rb:4
Schematist::VERSION = T.let(T.unsafe(nil), String)

# Raised when schema validation fails
#
# pkg:gem/schematist#lib/schematist/errors.rb:24
class Schematist::ValidationError < ::Schematist::Error; end

# pkg:gem/schematist#lib/schematist/validator.rb:4
class Schematist::Validator
  # Permanent mark (completely processed)
  #
  # pkg:gem/schematist#lib/schematist/validator.rb:10
  def initialize(schema_class); end

  # pkg:gem/schematist#lib/schematist/validator.rb:19
  def valid?; end

  # pkg:gem/schematist#lib/schematist/validator.rb:14
  def validate!; end

  private

  # pkg:gem/schematist#lib/schematist/validator.rb:62
  def extract_references(property); end

  # pkg:gem/schematist#lib/schematist/validator.rb:28
  def validate_circular_references!; end

  # DFS visit function
  #
  # pkg:gem/schematist#lib/schematist/validator.rb:42
  def visit(node, definitions, marks); end
end

# Temporary mark (currently being processed)
#
# pkg:gem/schematist#lib/schematist/validator.rb:8
Schematist::Validator::BLACK = T.let(T.unsafe(nil), Symbol)

# No mark (unvisited)
#
# pkg:gem/schematist#lib/schematist/validator.rb:7
Schematist::Validator::GRAY = T.let(T.unsafe(nil), Symbol)

# Node states for DFS-based topological sort
#
# pkg:gem/schematist#lib/schematist/validator.rb:6
Schematist::Validator::WHITE = T.let(T.unsafe(nil), Symbol)
