# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `starry` gem.
# Please instead update this file by running `bin/tapioca gem starry`.


# pkg:gem/starry#lib/starry.rb:3
module Starry
  class << self
    # pkg:gem/starry#lib/starry.rb:129
    def parse_dictionary(input, symbolize_names: T.unsafe(nil)); end

    # pkg:gem/starry#lib/starry.rb:134
    def parse_item(input, symbolize_names: T.unsafe(nil)); end

    # pkg:gem/starry#lib/starry.rb:124
    def parse_list(input, symbolize_names: T.unsafe(nil)); end

    # pkg:gem/starry#lib/starry.rb:10
    def serialize(input); end

    # pkg:gem/starry#lib/starry.rb:66
    def serialize_bare_item(input); end

    # pkg:gem/starry#lib/starry.rb:46
    def serialize_dictionary(input); end

    # pkg:gem/starry#lib/starry.rb:58
    def serialize_item(input); end

    # pkg:gem/starry#lib/starry.rb:39
    def serialize_key(input); end

    # pkg:gem/starry#lib/starry.rb:23
    def serialize_list(input); end

    # pkg:gem/starry#lib/starry.rb:29
    def serialize_parameters(input); end

    private

    # pkg:gem/starry#lib/starry.rb:139
    def ensure_ascii_only(input); end

    # pkg:gem/starry#lib/starry.rb:102
    def serialize_item_or_inner_list(input); end
  end
end

# pkg:gem/starry#lib/starry/inner_list.rb:3
class Starry::InnerList
  include ::Enumerable
  extend ::Forwardable

  # pkg:gem/starry#lib/starry/inner_list.rb:11
  def initialize(value = T.unsafe(nil), parameters = T.unsafe(nil)); end

  # pkg:gem/starry#lib/starry/inner_list.rb:16
  def ==(other); end

  # pkg:gem/starry#lib/starry/inner_list.rb:27
  def deconstruct(*_arg0); end

  # pkg:gem/starry#lib/starry/inner_list.rb:29
  def deconstruct_keys(keys); end

  # pkg:gem/starry#lib/starry/inner_list.rb:9
  def each(*, **, &); end

  # pkg:gem/starry#lib/starry/inner_list.rb:5
  def parameters; end

  # pkg:gem/starry#lib/starry/inner_list.rb:5
  def parameters=(_arg0); end

  # pkg:gem/starry#lib/starry/inner_list.rb:20
  def to_s; end

  # pkg:gem/starry#lib/starry/inner_list.rb:5
  def value; end

  # pkg:gem/starry#lib/starry/inner_list.rb:5
  def value=(_arg0); end
end

# pkg:gem/starry#lib/starry/item.rb:1
class Starry::Item
  # pkg:gem/starry#lib/starry/item.rb:5
  def initialize(value, parameters = T.unsafe(nil)); end

  # pkg:gem/starry#lib/starry/item.rb:10
  def ==(other); end

  # pkg:gem/starry#lib/starry/item.rb:18
  def deconstruct_keys(keys); end

  # pkg:gem/starry#lib/starry/item.rb:3
  def parameters; end

  # pkg:gem/starry#lib/starry/item.rb:3
  def parameters=(_arg0); end

  # pkg:gem/starry#lib/starry/item.rb:14
  def to_s; end

  # pkg:gem/starry#lib/starry/item.rb:3
  def value; end

  # pkg:gem/starry#lib/starry/item.rb:3
  def value=(_arg0); end
end

# pkg:gem/starry#lib/starry.rb:6
class Starry::ParseError < ::StandardError; end

# pkg:gem/starry#lib/starry/parser.rb:5
class Starry::Parser
  extend ::Forwardable

  # pkg:gem/starry#lib/starry/parser.rb:9
  def initialize(input, symbolize_names: T.unsafe(nil)); end

  # pkg:gem/starry#lib/starry/parser.rb:187
  def check(*, **, &); end

  # pkg:gem/starry#lib/starry/parser.rb:187
  def eos?(*, **, &); end

  # pkg:gem/starry#lib/starry/parser.rb:14
  def parse(type); end

  # pkg:gem/starry#lib/starry/parser.rb:99
  def parse_bare_item; end

  # pkg:gem/starry#lib/starry/parser.rb:178
  def parse_boolean; end

  # pkg:gem/starry#lib/starry/parser.rb:171
  def parse_byte_sequence; end

  # pkg:gem/starry#lib/starry/parser.rb:73
  def parse_dictionary; end

  # pkg:gem/starry#lib/starry/parser.rb:56
  def parse_inner_list; end

  # pkg:gem/starry#lib/starry/parser.rb:142
  def parse_integer_or_decimal; end

  # pkg:gem/starry#lib/starry/parser.rb:93
  def parse_item; end

  # pkg:gem/starry#lib/starry/parser.rb:48
  def parse_item_or_inner_list; end

  # pkg:gem/starry#lib/starry/parser.rb:132
  def parse_key; end

  # pkg:gem/starry#lib/starry/parser.rb:35
  def parse_list; end

  # pkg:gem/starry#lib/starry/parser.rb:116
  def parse_parameters; end

  # pkg:gem/starry#lib/starry/parser.rb:159
  def parse_string; end

  # pkg:gem/starry#lib/starry/parser.rb:166
  def parse_token; end

  # pkg:gem/starry#lib/starry/parser.rb:187
  def scan(*, **, &); end

  private

  # pkg:gem/starry#lib/starry/parser.rb:197
  def consume_ows; end

  # pkg:gem/starry#lib/starry/parser.rb:193
  def consume_sp; end

  # pkg:gem/starry#lib/starry/parser.rb:189
  def expect(regexp); end

  # pkg:gem/starry#lib/starry/parser.rb:201
  def parse_error(_ = T.unsafe(nil)); end
end

# pkg:gem/starry#lib/starry.rb:5
class Starry::SerializeError < ::StandardError; end

# pkg:gem/starry#lib/starry/version.rb:2
Starry::VERSION = T.let(T.unsafe(nil), String)
