# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ArticleJapaneseJob`.
# Please instead update this file by running `bin/tapioca dsl ArticleJapaneseJob`.


class ArticleJapaneseJob
  class << self
    sig do
      params(
        id: ::Integer,
        block: T.nilable(T.proc.params(job: ArticleJapaneseJob).void)
      ).returns(T.any(ArticleJapaneseJob, FalseClass))
    end
    def perform_later(id, &block); end

    sig { params(id: ::Integer).void }
    def perform_now(id); end
  end
end
