# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `GeneratedPathHelpersModule`.
# Please instead update this file by running `bin/tapioca dsl GeneratedPathHelpersModule`.


module GeneratedPathHelpersModule
  include ::ActionDispatch::Routing::UrlFor
  include ::ActionDispatch::Routing::PolymorphicRoutes

  sig { params(args: T.untyped).returns(String) }
  def about_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def accept_following_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def account_blog_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def account_password_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def actor_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_account_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_article_boost_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_article_like_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_articles_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_auth_login_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_auth_logout_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_auth_refresh_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_feed_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_post_boost_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_v1_post_like_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def article_boost_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def article_like_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def article_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def article_post_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def article_posts_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def articles_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def blog_post_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def blog_posts_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def cancel_user_registration_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def destroy_permanently_blog_post_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def destroy_user_session_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def discard_madmin_article_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def discard_madmin_site_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def discord_oauth_callback_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_blog_post_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_madmin_active_storage_attachment_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_madmin_article_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_madmin_preference_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_madmin_role_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_madmin_site_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_madmin_tag_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_madmin_user_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_user_password_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_user_registration_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def fedipub_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def feed_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def follow_followings_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def following_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def followings_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def llms_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def lookup_actors_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def madmin_active_storage_attachment_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def madmin_active_storage_attachments_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def madmin_article_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def madmin_articles_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def madmin_preference_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def madmin_preferences_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def madmin_role_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def madmin_roles_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def madmin_root_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def madmin_site_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def madmin_sites_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def madmin_social_index_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def madmin_tag_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def madmin_tags_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def madmin_user_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def madmin_users_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def mark_unrelated_madmin_article_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def mission_control_jobs_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_article_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_blog_post_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_following_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_madmin_active_storage_attachment_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_madmin_article_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_madmin_preference_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_madmin_role_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_madmin_site_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_madmin_tag_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_madmin_user_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_rails_conductor_inbound_email_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_rails_conductor_inbound_email_source_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_user_confirmation_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_user_oauth_registration_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_user_password_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_user_registration_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_user_session_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def oauth_install_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def oauth_result_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def others_api_v1_articles_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def others_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def post_boost_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def post_like_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def post_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def posts_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def privacy_policy_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def publish_blog_post_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def push_subscription_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def pwa_manifest_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def pwa_service_worker_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_blob_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_blob_representation_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_blob_representation_proxy_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_conductor_inbound_email_incinerate_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_conductor_inbound_email_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_conductor_inbound_email_reroute_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_conductor_inbound_email_sources_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_conductor_inbound_emails_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_direct_uploads_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_disk_service_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_health_check_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_notes_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_properties_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_routes_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_mailers_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_mailgun_inbound_emails_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_mandrill_inbound_emails_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_mandrill_inbound_health_check_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_postmark_inbound_emails_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_relay_inbound_emails_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_representation_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_sendgrid_inbound_emails_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_service_blob_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_service_blob_proxy_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_storage_proxy_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_storage_redirect_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def regenerate_thumbnail_madmin_article_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def reprocess_madmin_article_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def restore_madmin_article_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def restore_madmin_site_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def robots_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def root_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rss_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rswag_api_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rswag_ui_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ruby_llm_monitoring_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def slack_events_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def slack_oauth_callback_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def social_provider_authorize_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def social_provider_callback_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def tag_api_v1_articles_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def tag_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def terms_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def translate_japanese_madmin_article_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def turbo_recede_historical_location_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def turbo_refresh_historical_location_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def turbo_resume_historical_location_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def undiscard_blog_post_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def update_rails_disk_service_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def user_apple_omniauth_authorize_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def user_apple_omniauth_callback_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def user_confirmation_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def user_github_omniauth_authorize_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def user_github_omniauth_callback_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def user_google_oauth2_omniauth_authorize_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def user_google_oauth2_omniauth_callback_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def user_oauth_registration_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def user_password_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def user_profile_base_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def user_profile_blog_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def user_profile_blog_post_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def user_profile_boosts_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def user_profile_comments_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def user_profile_followers_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def user_profile_following_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def user_profile_likes_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def user_profile_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def user_profile_posts_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def user_registration_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def user_session_path(*args); end
end
